### ISSUE TITLE
对局结束后，再次快速进入对局会导致程序判断出错，按esc

### ISSUE THREAD

**Issue by Canda15** [linruowuyin/Fhoe-Rail#10]
详见视频。出发概率不小，每天都会遇到几次

https://github.com/linruowuyin/Fhoe-Rail/assets/124772373/c4c057e5-1773-4c83-83e9-a1aaded31eb6

https://github.com/linruowuyin/Fhoe-Rail/assets/124772373/1bb8b0bf-4923-403a-9869-aa8b2d0917de

**Comment by linruowuyin** [comment]
后面寒假看情况修复，之前用todesk远程确实触发了几次

**Comment by linruowuyin** [comment]
应该不是按esc，我自己有光标录制的录像是进入战斗之后鼠标飘上去点了一下，而且貌似只有远程连接才会有这种情况，后面再观察一下
