### ISSUE TITLE
runtime exception

### ISSUE THREAD

**Issue by software-picker** [linruowuyin/Fhoe-Rail#105]
hate to break to you, but here's a fresh new bug: 
<img width="1729" alt="image" src="https://github.com/linruowuyin/Fhoe-Rail/assets/16222092/15e2a677-7f5d-4084-bcd6-f7c155b0a54c">

**Comment by smjes3** [comment]
请尝试删除config.json后重试，我们将会在今天晚些版本解决这个问题。

Please try deleting the config.json file and retrying. We will address this issue in a later version today.

**Comment by smjes3** [comment]
https://github.com/linruowuyin/Fhoe-Rail/releases/tag/2.073
