### ISSUE TITLE
优先地图选择能设置吗

### ISSUE THREAD

**Issue by skczjun** [linruowuyin/Fhoe-Rail#107]
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/20118957/6e1f414c-8d4a-4196-b650-ed1e2e2708d8)
我是在3月7里面启动的，也试过在他内部找到Fhoe-Rail设置快捷方式启动，但启动之后没有找到修改优先地图的功能。
想问一下有这个修改优先地图设置的配置文件吗

**Comment by smjes3** [comment]
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/33685788/7aab8775-6c02-4d2c-a5bd-868f4e02066f)

快捷方式--debug之后，启动，在下方有一个优先地图。

当前还没有配置文件直接进行修改，你可以说下你的想法有助于我们加入这个功能。

**Comment by skczjun** [comment]
想要一个设置优先地图的功能，比如修改优先地图为仙舟，下次启动锄大地时从仙舟开始跑图，不用每次都手动选择地图。
这是为了方便以后地图越来越多后，跑完一次锄大地时间太长了，有些人，比如每天就开3小时，根本打不完，而且先出的地图怪等级都比较低，经验少，优先从高等级地图打。还有如果能加上哪些地图不打就更好了，比如匹诺康尼跑图费时间又容易出问题，直接跳过。
