### ISSUE TITLE
每次卡稚子的梦最上方传送点

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#110]
3台电脑同时跑锄地任务，每次都会卡在稚子的梦最上方的界域定锚点，截图时间是16:59分和日志上传了帮忙分析一下，谢谢哈
![Screenshot_2024-03-12-16-59-24-02_c8caf204774d15df9c96f9997a2407c4(1)](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/a24e7707-9ee1-41e0-81c2-0ca360360f14)
![Screenshot_2024-03-12-17-16-54-89_589d4bb4f12f057e26f1c0af39598661(1)](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/8f751cc9-1b42-4731-8336-87347ddc40ec)
![Screenshot_2024-03-12-17-17-00-43_589d4bb4f12f057e26f1c0af39598661(1)](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/930d624c-ed19-4477-9e67-ba7730ce6da3)
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14572032/default.log)

**Comment by smjes3** [comment]
使用run开头的地图为疾跑修正后的地图，目前default地图使用疾跑会有一些卡图情况。

**Comment by jelly0925** [comment]
辛苦了，不知道为什么每次会卡在传送点。每天都会遇到呢。

**Comment by smjes3** [comment]
使用了之前走路的配置，然后用疾跑的算法就是有一些地方会出现卡墙，所以目前基本放弃对走路的优化，专注疾跑的版本，在代码中也已经进行了强制疾跑。

**Comment by smjes3** [comment]
理论上新map已解决。
