### ISSUE TITLE
2.074 初始地图为仙舟，卡在工造司

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#115]
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14580761/default.log)
![Snipaste_2024-03-13_09-41-34](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/5864ce4b-5c57-408b-aba0-f8e16114170e)
![2 074卡罗浮1](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/af67d0e7-c579-4651-9432-4b14f60cd663)
![Snipaste_2024-03-13_09-41-34](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/8e7b68c6-27ab-49b7-8408-9e2e196eddb7)

**Comment by smjes3** [comment]
日志似乎无法正常下载，试一下贴出卡住之前的几十条看看

**Comment by smjes3** [comment]
查看日志后，复现问题，打开地图，之后未正确查找到picture\map_3-1_point_2.png，造成了后续行进路线错乱。

在本机测试（同样适用黑天鹅），无此问题。

你看下是否能够复现看看。再跑一遍试试。

**Comment by smjes3** [comment]
查看日志后发现角色初始在工造司，所以选择星球后进来找不到流云渡了，有优先星球的情况下不要在当前星球停留避免出错。

例如想优先仙舟星球，那么角色初始请在别的3个星球上再运行。

之后看情况增加右侧列表拖动功能

**Comment by jelly0925** [comment]
> 查看日志后发现角色初始在工造司，所以选择星球后进来找不到流云渡了，有优先星球的情况下不要在当前星球停留避免出错。
> 
> 例如想优先仙舟星球，那么角色初始请在别的3个星球上再运行。
> 
> 之后看情况增加右侧列表拖动功能

我测试一下哈，能完善一下这个小BUG就更完美了。
