### ISSUE TITLE
设置匹诺康尼为优先星球后，锄完匹诺康尼后就直接结束了，没有按照4-1-2-3的顺序继续锄地

### ISSUE THREAD

**Issue by jowilksasella** [linruowuyin/Fhoe-Rail#118]
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14594576/default.log)
以下是我的配置：    
> ? 选择地图版本 (Use arrow keys)
>     ? 选择地图版本 technique
>     ? 想要跑完自动关机吗？ ↑↑↓↓←→←→BABA
>     ? map最后一次攻击自动转换为秘技攻击？默认为不转换 不转换
>     ? 设置识别怪物超时时间，默认为15秒。需要自定义设置可以直接修改config.json中的detect_fight_status_time为指定的秒数 较长识别时间（15秒）
>     ? 优先星球 匹诺康尼
>     （中间的地图列表太长我就删掉，以免影响观感）
>     ? 请选择起始星球： 优先星球
>     ? 请选择起始星球： 匹诺康尼

> {
>   "version": "",
>   "real_width": 0,
>   "real_height": 0,
>   "map_debug": true,
>   "github_proxy": "",
>   "rawgithub_proxy": "",
>   "webhook_url": "",
>   "start": true,
>   "picture_version": "0",
>   "star_version": "0",
>   "open_map": "m",
>   "script_debug": true,
>   "auto_shutdown": true,
>   "auto_final_fight_e": false,
>   "auto_run_in_map": true,
>   "detect_fight_status_time": 15,
>   "map_version": "technique",
>   "main_map": "4"
> }

              已修改，在config.json中的main_map，设置为"3"即为仙舟，之后默认启动都均为从3-4-1-2的顺序锄地

_Originally posted by @smjes3 in https://github.com/linruowuyin/Fhoe-Rail/issues/107#issuecomment-1991665454_

**Comment by smjes3** [comment]
已发现了这个问题，修复后正在自测中。
