### ISSUE TITLE
使用March3th7卡住

### ISSUE THREAD

**Issue by CX330J** [linruowuyin/Fhoe-Rail#122]
在使用三月七小助手完整启动遇到
检测到需要进行必要的配置，请配置
卡住需要手动配置

**Comment by smjes3** [comment]
更新版本，完整配置一次以后即可。2.074及之前的有这个BUG，会反复提示

**Comment by saki3525** [comment]
这是三月七的问题，怎么跑来这提issues了。不行就原版运行好了。等那边适配。
