### ISSUE TITLE
在过期邮包那里卡住

### ISSUE THREAD

**Issue by bin1129** [linruowuyin/Fhoe-Rail#123]
也不是第一次因为过期邮包或代币卡住了，说真的也没什么用，能不能加个选项不要弄过期邮包和代币

版本：2.075
11:00:41 - INFO   	| calculated.auto_map:652                  	- 2.075 - 执行map_3-1_0文件:5/5 {'fighting': 2}
11:00:41 - INFO   	| calculated.click:122                     	- 2.075 - 点击坐标(1279, 733)
11:00:42 - INFO   	| map.auto_map:297                         	- 2.075 - map_3-1_0用时[1;92m『21.6秒』[0m,总计:[1;92m『41分36.1秒』[0m
11:00:42 - INFO   	| log.webhook_and_log:61                   	- 2.075 - [0;96;40m过期邮包2[0m
11:00:42 - INFO   	| map.auto_map:204                         	- 2.075 - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_3-1_01
11:00:42 - INFO   	| map.auto_map:210                         	- 2.075 - check
11:00:42 - INFO   	| map.auto_map:218                         	- 2.075 - Friday，周二五日，尝试购买
11:00:42 - INFO   	| map.auto_map:210                         	- 2.075 - picture\buy.png
11:00:44 - INFO   	| calculated.click:122                     	- 2.075 - 点击坐标(1649, 789)
11:00:45 - INFO   	| map.auto_map:276                         	- 2.075 - 传送点击（1）
11:00:45 - INFO   	| map.auto_map:210                         	- 2.075 - picture\parcel.png
11:00:47 - INFO   	| calculated.click:122                     	- 2.075 - 点击坐标(684, 837)
11:00:47 - INFO   	| map.auto_map:276                         	- 2.075 - 传送点击（2）
11:00:47 - INFO   	| map.auto_map:210                         	- 2.075 - picture\max.png
11:00:49 - INFO   	| calculated.on_interface:1038             	- 2.075 - 检测到无法购买，耗时 1.4 秒
11:00:49 - INFO   	| calculated.on_interface:1039             	- 2.075 - 检测图片序号为0，匹配度1.000，匹配位置为(1426, 915)
11:00:49 - INFO   	| log.webhook_and_log:61                   	- 2.075 - [0;96;40m流云渡-1[0m
11:00:49 - INFO   	| map.auto_map:204                         	- 2.075 - 路线领航员：[1;95m雪见璃[0m 感谢她(们)的无私奉献，准备开始路线：map_3-1_1
11:00:49 - INFO   	| map.auto_map:210                         	- 2.075 - map
11:00:49 - INFO   	| calculated.on_interface:1038             	- 2.075 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.2 秒
11:00:49 - INFO   	| calculated.on_interface:1039             	- 2.075 - 检测图片序号为0，匹配度0.908，匹配位置为(1463, 805)
11:00:51 - INFO   	| map.map_init:42                          	- 2.075 - 打开地图
11:00:54 - INFO   	| map.map_init:42                          	- 2.075 - 打开地图
11:00:57 - INFO   	| map.map_init:42                          	- 2.075 - 打开地图
11:01:00 - INFO   	| map.map_init:42                          	- 2.075 - 打开地图

**Comment by skczjun** [comment]
我也是，等作者解决吧

**Comment by smjes3** [comment]
2.076已修复
