### ISSUE TITLE
建议固定带队角色的功能

### ISSUE THREAD

**Issue by smallmj** [linruowuyin/Fhoe-Rail#131]
默认使用1号位带队，有时候1号位战斗中死了，战斗后变成2号位带队，结果2号位是个近战，虽然经过传送，1号位复活了，但是一直没有切换到1号位，导致后续流程经常漏怪。建议战斗后或者传送到加一个按键1的步骤。如果能在战斗后检测死亡角色，自动吃药复活再切换到1号位就更好了。

**Comment by smjes3** [comment]
1、关于1号位复活，切换到1号位：
目前增加了方案：执行任意地图传送后，会检测1号位是否存活，存活情况下按一次1进行切换。

2、关于战斗后检测死亡角色，自动吃药复活：
已有方案，但是方案吃药会牵扯到消耗玩家道具物品（理论上我们会尽力避免自动情况下消耗玩家物品），这里如果做个开关进行询问的话，目前配置要询问的已经有点多了，如果需求的人不多会暂时搁置，希望还是尽量带有生存位减少死亡情况产生。

**Comment by smjes3** [comment]
已添加功能：执行任意地图传送后，会检测1号位是否存活，存活情况下按一次1进行切换。
