### ISSUE TITLE
锄大地每次在雅利洛VI号的城郊雪原会卡住

### ISSUE THREAD

**Issue by ChinaYong** [linruowuyin/Fhoe-Rail#132]
卡住是指进入战斗后不会点击自动战斗的按钮。
![9edab0e745cc1d399e9299933370e8e](https://github.com/linruowuyin/Fhoe-Rail/assets/92238755/fccd9e2b-2a2f-4189-a155-754a064be01f)
如图，每次回来都发现界面停留在这个位置...

**Comment by smjes3** [comment]
增加了通过行动条识别是否自动战斗开启。
