### ISSUE TITLE
进入战斗后，大概率无法触发自动战斗

### ISSUE THREAD

**Issue by 1everver** [linruowuyin/Fhoe-Rail#137]
进入战斗后，大概率无法触发自动战斗，这个是什么原因，卡在这个地方，见图

> [](url)
![卡在这个地方](https://github.com/linruowuyin/Fhoe-Rail/assets/104746247/6cf8fcd5-6ccd-4d4f-a357-6ab2239cf1b6)

**Comment by smjes3** [comment]
2.077r修复了这个问题，更新版本后重试看看。

**Comment by smjes3** [comment]
识别自动战斗有30秒的时间，如果介意的话需要在设置-战斗功能-是否沿用战斗设置，改为【是】，以避免每次战斗都需要勾选自动战斗。

**Comment by 1everver** [comment]
已更新最新版本，还是有的时候无法识别成功（还是只有小部分识别成功），已经去设置中勾选自动战斗，解决，谢谢

**Comment by smjes3** [comment]
如果后续还有没勾选自动战斗的情况还卡自动战斗的可以发日志上来看看。
2.077r是增加了一个左侧行动条作为识别自动战斗的开关，目前自测是没问题。
