### ISSUE TITLE
在鳞渊境-6的路线操作中会暂停在地图最小化操作

### ISSUE THREAD

**Issue by William00739** [linruowuyin/Fhoe-Rail#14]
![Screenshot_2024-02-07-09-36-16-303_com wujie connect](https://github.com/linruowuyin/Fhoe-Rail/assets/128281500/42043703-e219-4260-b41c-067c69b3472d)
-5锄完后就停住了，再重选一次还是停住了。

**Comment by linruowuyin** [comment]
类似问题产生的原因是版本更新后原先的截图匹配失灵，重新截一张替换即可
