### ISSUE TITLE
卡白日梦酒店吧台

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#140]
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14626939/default.log)
![锄地卡BUG1](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/60566647-bd1b-4bfa-ba77-d4a58dc88289)
一直卡在这个位置，异常退出。最近版本漏怪有点多啥，几乎所有图都有多处漏怪不清楚啥原因。

**Comment by smjes3** [comment]
花火是近战，不建议使用近战进行锄大地，容易造成大量漏怪。

**Comment by smjes3** [comment]
默认代币购买强制关闭，需要的请在config.json的allow_map_buy开启，并且确保对应NPC能够购买相应代币。
