### ISSUE TITLE
有打算2.1後新增黃泉密技鋤大地嗎 ?

### ISSUE THREAD

**Issue by zihuanfeng520** [linruowuyin/Fhoe-Rail#145]
作者大大有打算適配黃泉的密技嗎?這樣可以一路砍過去，還不需要帶生存位，好奇而已，大大的鋤大地幫了我很多 再謝謝一次!

**Comment by fateholder** [comment]
你算过需要多少秘技点吗？我猜至少也有200多只怪，零食攒的再多，几周也用光了

**Comment by MioBKYan** [comment]
有打算，零食基本可以做到每日信用点和购买材料持平，但录图目测比较困难，具体还要看黄泉出来后的录图情况

**Comment by Nicetrylp** [comment]
是否可以在战斗难度比较高(空间站虫子)，战斗后会改变视角（皮诺康尼3D图）使用黄泉秘籍，第一可以平衡零食消耗与跑图时间，第二录图的工作量也会少点

**Comment by Heipen** [comment]
用黄泉秘技锄大地的话是否可以考虑下顺便打一打地图上的秘技罐子啊？全图秘技罐子也有大几十个吧？全都打了基本也就不怎么耗零食了？

**Comment by smjes3** [comment]
> 用黄泉秘技锄大地的话是否可以考虑下顺便打一打地图上的秘技罐子啊？全图秘技罐子也有大几十个吧？全都打了基本也就不怎么耗零食了？

持续优化中。
