### ISSUE TITLE
关于自动购买零食材料，请问这个是默认开启的吗

### ISSUE THREAD

**Issue by vvincee7** [linruowuyin/Fhoe-Rail#153]
这个功能是伴随秘技锄地的地图绑定的吗，不会在普通锄地里出现吧。因为目前还没有秘技锄地的打算，谢谢大佬

**Comment by smjes3** [comment]
默认关闭，需要开启需要自行去config.json中
将"allow_map_buy": false的false改为true才会开启。

**Comment by vvincee7** [comment]
你好大佬，更新到2.081后有两个问题
1.在config.json中发现多出了"allow_snack_buy"，请问这个是新的用来控制零食材料购买的吗，"allow_map_buy"用来控制过期邮包和代币的购买？
2.修改config.json可以使用改文件后缀改成txt来进行编辑，然后再改回json格式这样的方法吗，我不太懂计算机程序编写相关的知识
以上，谢谢大佬

**Comment by smjes3** [comment]
> 你好大佬，更新到2.081后有两个问题 1.在config.json中发现多出了"allow_snack_buy"，请问这个是新的用来控制零食材料购买的吗，"allow_map_buy"用来控制过期邮包和代币的购买？ 2.修改config.json可以使用改文件后缀改成txt来进行编辑，然后再改回json格式这样的方法吗，我不太懂计算机程序编写相关的知识 以上，谢谢大佬

allow_snack_buy控制零食
allow_map_buy控制过期邮包
均为：True开启，False关闭
config.json，右键-打开方式-选择其他应用-记事本，然后改动即可。改后缀名也可以。
