### ISSUE TITLE
80和最新的81都找不到./map\\20230824013125，用老版本正常，不知道啥情况

### ISSUE THREAD

**Issue by hz0079** [linruowuyin/Fhoe-Rail#160]
11:23:41 - INFO   	| Honkai_Star_Rail.print_version:87        	- 2.079 - 当前版本：2.081
11:23:41 - INFO   	| Honkai_Star_Rail.print_version:88        	- 2.079 - config.json
11:23:41 - ERROR  	| Honkai_Star_Rail.<module>:287            	- 2.081 - Traceback (most recent call last):
  File "Honkai_Star_Rail.py", line 279, in <module>
  File "Honkai_Star_Rail.py", line 116, in main
  File "Honkai_Star_Rail.py", line 22, in choose_map
  File "utils\map.py", line 55, in read_maps
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './map\\20230824013125'

80和最新的81都这个问题，用老版本正常，不知道啥情况

**Comment by smjes3** [comment]
地图文件里面混进了未知的东西，你是用三月七助手更新的还是直接下载的zip。如果是下载的zip的话解压缩到一个全新的文件夹再试试。
