### ISSUE TITLE
2.082版本 有一些小问题想请教

### ISSUE THREAD

**Issue by pizzaed1** [linruowuyin/Fhoe-Rail#163]
请问120侦也可以使用吗!?
和我发现最新版本更新会侦测1号位,我原本3号位是三月七 它会自动帮我切到一号位的火主  这个是代表以后要打的角色都要放一号位吗

**Comment by smjes3** [comment]
跑图角色放到一号位，用于跑图角色死亡以后重新定位到该角色。如果都放置在不同的位置，那不好进行识别。所以在有人提出要支持跑图角色复活后重新定位的时候就定为了一号位。

120帧没试过，理论上应该会有部分漏怪，目前我们测试录图都是在60帧下进行，120帧可以自行尝试一下。

**Comment by pizzaed1** [comment]
了解,感谢大佬解惑
