### ISSUE TITLE
锄大地传送太卜司5，寻路卡住

### ISSUE THREAD

**Issue by skczjun** [linruowuyin/Fhoe-Rail#172]
![QQ图片20240324103515](https://i.postimg.cc/SxT3PcGk/QQ-20240324103515.png)
![QQ图片20240324103516](https://i.postimg.cc/90YNY9M3/QQ-20240324103537.png)
https://i.postimg.cc/SxT3PcGk/QQ-20240324103515.png
https://i.postimg.cc/90YNY9M3/QQ-20240324103537.png

[url=https://postimg.cc/RWtg668D][img]https://i.postimg.cc/RWtg668D/QQ-20240324103515.png[/img][/url]

[url=https://postimg.cc/sG1cVv7K][img]https://i.postimg.cc/sG1cVv7K/QQ-20240324103537.png[/img][/url]
如图，不是在楼梯卡住，就在在门口旮旯卡住

**Comment by skczjun** [comment]
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/20118957/5da45b88-0d4d-4637-a7e5-34c44b4af064)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/20118957/4ac4647e-5ab9-4eae-9750-d473162f4c7a)

**Comment by smjes3** [comment]
请提供相关日志以便排查。
