### ISSUE TITLE
新版本传送识别错误

### ISSUE THREAD

**Issue by 0frostmourne0** [linruowuyin/Fhoe-Rail#19]
2.022版本运行后会卡在“执行传送点击”，传送完成后无法进行后续操作。
手动切换到脚本界面显示如图：

![20240209004350](https://github.com/linruowuyin/Fhoe-Rail/assets/23077424/222b54c3-4f01-45ca-b131-843db7f3c6ed)

可以看到已经成功传送到车厢，但脚本似乎没有识别到点击了传送。手动选择其他地图也有同样问题。

游戏分辨率正确，各个图标无遮挡。
用1.6版本可以正常跑到鳞渊境结束，2.0版本也可以跑起来但无法识别战斗，2.02版本开始就出现这个问题。
尝试过源码运行和集成运行均出现此问题，也换过1台电脑和2个虚拟机均有此问题。

**Comment by saki3525** [comment]
<img width="392" alt="图片_20240209020454" src="https://github.com/linruowuyin/Fhoe-Rail/assets/47911458/a40a6f7a-5b68-4048-95b3-64b354061040">
相同的问题，来看看有没有解决方案的。
log看起来是执行传送成功后就停住了。

**Comment by Hcj0720** [comment]
根据源码来看，是传送后的黑屏判断出了bug，如果使用2.022版本可以在游戏中设置 - 其他 - 系统功能 - 键鼠模式显示底部提示更改为[是]临时解决这个问题

**Comment by yaochenli007** [comment]
作者吧传送完成判定和战斗完成判定用了同一张叫finish_fighting的图，但2.0版本里改成了 M导航 字样的图，我找了半天没找到，换回原来 Enter字样的图就能正常运行了

**Comment by linruowuyin** [comment]
新地图在跑图的时候没有原来的enter，暂时是使用游戏早期版本的小黑边提示，忘了说了

**Comment by 0frostmourne0** [comment]
好的，打开黑条之后运行正常了……
不过3D地图真的麻了，后两张图很容易卡住。
