### ISSUE TITLE
缺少酒店梦境2层左上区域3d图的路线

### ISSUE THREAD

**Issue by UU0510** [linruowuyin/Fhoe-Rail#192]
如图
![屏幕截图(42)](https://github.com/linruowuyin/Fhoe-Rail/assets/78683694/412df74d-5eb8-48bf-bf63-d0917d904376)
map文件夹里找了下, 似乎没有找到这个地方的路线?

**Comment by UU0510** [comment]
版本是2.1.04

**Comment by smjes3** [comment]
https://github.com/linruowuyin/Fhoe-Rail/releases/tag/2.1.05
更新2.1.05

**Comment by UU0510** [comment]
大佬您好, 我跑了下酒店梦境的路线4_3_12看了下, 发现问题出在拖动地图寻找传送点4_3_point_8(酒店梦境最左上方锚点)的时候, 地图拖动的幅度不足, 要传送的锚点显示不出来导致的漏怪, 能否增加拖动地图时候的拖动次数?
