### ISSUE TITLE
[Bug] huangquan图闪退

### ISSUE THREAD

**Issue by vvincee7** [linruowuyin/Fhoe-Rail#196]
### 问题描述

huangquan图在检查完1号位后程序直接闪退/关闭了，日志也停止了 

### 预期行为

正常运行

### 实际行为

程序关闭了

### 自动锄大地脚本版本

2.1.05

### 日志

    2024年03月30日 晴
    今天口腔溃疡不舔了

02:09:55 - INFO   	| fhoe.main:129                            	- 2.1.04 - 
02:09:55 - INFO   	| fhoe.main:130                            	- 2.1.04 - 切换至游戏窗口，请确保跑图角色普攻为远程
02:09:55 - INFO   	| fhoe.main:134                            	- 2.1.04 - 开始运行，请勿移动鼠标和键盘.向着星...呃串台了
02:09:55 - INFO   	| fhoe.main:135                            	- 2.1.04 - 黑塔：7128；雅利洛：19440；罗浮：42596；匹诺康尼：30996
02:09:55 - INFO   	| fhoe.main:136                            	- 2.1.04 - 2.0版本单角色锄满100160经验（fhoe当前做不到）
02:09:55 - INFO   	| fhoe.main:137                            	- 2.1.04 - 免费软件，倒卖的曱甴冚家铲，请尊重他人的劳动成果
02:09:55 - INFO   	| log.webhook_and_log:61                   	- 2.1.04 - [0;96;40m黑塔办公室-1[0m
02:09:55 - INFO   	| calculated.try_click_pass:939            	- 2.1.04 - 判断是否存在月卡
02:09:55 - INFO   	| calculated.try_click_pass:944            	- 2.1.04 - 识别点位(241, 81)
02:09:55 - INFO   	| calculated.try_click_pass:946            	- 2.1.04 - 识别到此刻正在主界面，无月卡，图片匹配度: 0.99 (241, 81)
02:09:55 - INFO   	| calculated.monthly_pass_check:910        	- 2.1.04 - 月卡检查时间更新至：2024-03-30 02:09:55.538119
02:09:55 - INFO   	| map.auto_map:233                         	- 2.1.04 - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_1-1_0
02:09:55 - INFO   	| map.auto_map:239                         	- 2.1.04 - main
02:09:55 - INFO   	| calculated.on_interface:1147             	- 2.1.04 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
02:09:55 - INFO   	| calculated.on_interface:1148             	- 2.1.04 - 检测图片序号为0，匹配度0.991，匹配位置为(233, 64)
02:09:57 - INFO   	| map.auto_map:239                         	- 2.1.04 - picture\guide.png
02:09:58 - INFO   	| calculated.click:135                     	- 2.1.04 - 点击坐标(1599, 55)，坐标来源图片匹配度1.000
02:09:58 - INFO   	| map.auto_map:344                         	- 2.1.04 - 传送点击（1）
02:09:58 - INFO   	| map.auto_map:239                         	- 2.1.04 - picture\index.png
02:10:00 - INFO   	| calculated.click:135                     	- 2.1.04 - 点击坐标(600, 213)，坐标来源图片匹配度1.000
02:10:00 - INFO   	| map.auto_map:344                         	- 2.1.04 - 传送点击（2）
02:10:00 - INFO   	| map.auto_map:239                         	- 2.1.04 - picture\map_0.png
02:10:01 - INFO   	| calculated.click:135                     	- 2.1.04 - 点击坐标(1549, 544)，坐标来源图片匹配度1.000
02:10:03 - INFO   	| calculated.run_mapload_check:1049        	- 2.1.04 - 检测到地图加载map_load，匹配度0.9999955892562866
02:10:03 - INFO   	| calculated.on_interface:1147             	- 2.1.04 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.5 秒
02:10:03 - INFO   	| calculated.on_interface:1148             	- 2.1.04 - 检测图片序号为1，匹配度0.992，匹配位置为(37, 39)
02:10:03 - INFO   	| calculated.run_mapload_check:1074        	- 2.1.04 - 地图载毕，用时 1.6 秒
02:10:04 - INFO   	| map.auto_map:344                         	- 2.1.04 - 传送点击（3）
02:10:04 - INFO   	| map.auto_map:239                         	- 2.1.04 - main
02:10:06 - INFO   	| calculated.on_interface:1155             	- 2.1.04 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.804
02:10:08 - INFO   	| calculated.on_interface:1147             	- 2.1.04 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
02:10:08 - INFO   	| calculated.on_interface:1148             	- 2.1.04 - 检测图片序号为0，匹配度0.992，匹配位置为(233, 64)
02:10:11 - INFO   	| calculated.first_role_check:1179         	- 2.1.04 - 开始判断1号位
02:10:11 - INFO   	| calculated.first_role_check:1194         	- 2.1.04 - 设置1号位为跑图角色

**Comment by smjes3** [comment]
已修复这个问题在2.1.05
