### ISSUE TITLE
请求增加回复秘技点时选择食用哪种零食或者不食用某种零食

### ISSUE THREAD

**Issue by HARUKAL** [linruowuyin/Fhoe-Rail#198]
### 原因

有的零食不能购买或者合成，比如好看的垃圾（目前秘技类就这一种）

### 功能逻辑

1.增加选择哪种零食
2.增加排除哪种零食
3.改变选择零食时鼠标点击的坐标到第二格或者更后面

**Comment by impovemind** [comment]
同感，金垃圾怎么也不能被用了
最好就是能加入识别功能，不过看起来这个脚本好像不使用图像识别，我觉得可以把鼠标移到第二行靠后位置或者第三行靠前位置，主要对应的就是奇巧零食。这玩意稀有度低，排的比较靠后，像我的就是在第三行第一个。

**Comment by impovemind** [comment]
我想可以给个标准，就把所有回复秘技点的食物搞齐，然后鼠标就移到此时奇巧零食在的位置
或者再考虑一下有些真把金垃圾花完的人，就把鼠标移到全齐时奇巧零食前面一位，这样没金垃圾的就对上了，有金垃圾的就把前面一个低稀有度的食物先花完

**Comment by smjes3** [comment]
改为只吃奇巧零食。

**Comment by hz0079** [comment]
只吃奇巧零食就行了，目前就它最实惠
