### ISSUE TITLE
刷图前检查仓库恢复秘技点道具

### ISSUE THREAD

**Issue by hz0079** [linruowuyin/Fhoe-Rail#199]
### 原因

用黄泉跑图节省时间，不然以后图越来越多，花费时间和电费越来越多.....

### 功能简述

刷图前检查仓库恢复秘技点道具

### 功能逻辑

每天跑图前打开背包扫描下道具数量，如不够就去买或者合成，再开始跑图

### 实现参考

整理了每天可获取的道具供作者参考：
每日委托>合成材料>风暴中怒放的花：气态流体25+种子25 可合成 奇巧零食x25                2秘技点

雅利洛-VI >行政区>地图上方右边售货机：奇巧零食x10                                  花费6000        2秘技点
                     磐岩镇>右下角小吃摊：宝石蜥肉串x5、炸岩居蟹x5                    花费18000      4、3秘技点
仙舟-罗浮>星槎海中枢>中间 杂货铺老板：气态流体x100+种子x100=奇巧零食x100   花费52000      2秘技点
                    流云渡>过期邮包收购处：干制应急灯x5                                          花费9000       3秘技点
                    长乐天>右上角 宝饵堂：养心返魂丹x1                                             花费3600       2秘技点
                    金人巷>左下角 美馔阁：招牌红油乱斩牛杂x3                                 花费10800     4秘技点
                                  右边 陈机铺：斗舰福牌x10                                                   花费6000       2秘技点
匹诺康尼>黄金的时刻>右边 梦境贩售店 (梦泡上新)：美梦糖浆x5                   花费9000        3秘技点
                                        下方 冰淇淋推车：美梦糖浆x5                                       花费9000        3秘技点
                                                                                                                     合计花费：123400     共可恢复 50+200+134秘技点

合成机里的 惩戒粮食、惩戒能量、星宇啵啵，都需要垃圾故不推荐

**Comment by hz0079** [comment]
补一个：
克劳克影视乐园>上方 沃尔纳 快餐车老板：美梦糖浆x5                  花费13500     3秘技点

**Comment by smjes3** [comment]
目前方案应该不考虑买这么全，因为每天购买100个奇巧零食已经足够覆盖完整锄地了。跑太多地点去购买效率会降低很多。

仙舟-罗浮>星槎海中枢>中间 杂货铺老板：气态流体x100+种子x100=奇巧零食x100 花费52000 2秘技点

目前只有这个是单次购买量最大的了。

**Comment by hz0079** [comment]
> 目前方案应该不考虑买这么全，因为每天购买100个奇巧零食已经足够覆盖完整锄地了。跑太多地点去购买效率会降低很多。
> 
> 仙舟-罗浮>星槎海中枢>中间 杂货铺老板：气态流体x100+种子x100=奇巧零食x100 花费52000 2秘技点
> 
> 目前只有这个是单次购买量最大的了。

列出来只是方便看，目前确实是杂货铺实惠
