### ISSUE TITLE
新版本卡在执行传送点击（5）

### ISSUE THREAD

**Issue by shellyan** [linruowuyin/Fhoe-Rail#20]
点了传送成功后角色一动不动 
执行传送点击（1）
执行传送点击（2）
执行传送点击（3）
执行传送点击（4）
执行传送点击（5）

**Comment by RKOJIN** [comment]
我也是这个问题

**Comment by dawang1110** [comment]
我也是这个问题。

**Comment by fateholder** [comment]
TIPS：新地图没有原来的“enter”显示，需要开启底部提示用于识别传送成功，否则脚本无法运行

**Comment by DragonQuestXI** [comment]
> 我目前滚到前一个版本了，2.0.2 能用，比起之前的版本，需要按照 2.0.2 的 tips 修改 2.0.2 的 TIPS：新地图没有原来的 “enter” 显示，需要开启底部提示用于识别传送成功，否则脚本无法运行 —— 修改了。还是不成功

很有用，改了之后2.0.23就能用了，不改就卡在观景车厢不动

**Comment by shellyan** [comment]
> 我目前滚到前一个版本了，2.0.2能用，比起之前的版本，需要按照2.0.2的tips修改 2.0.2的TIPS：新地图没有原来的“enter”显示，需要开启底部提示用于识别传送成功，否则脚本无法运行——修改了。还是不成功

我修改底部提示了后新版本就可以用了
