### ISSUE TITLE
[Bug] 楼层按钮识别错误

### ISSUE THREAD

**Issue by 0frostmourne0** [linruowuyin/Fhoe-Rail#200]
### 问题描述

有些地图结束后本身就在“3层”，脚本试图点击“3floor.png”时却点击了“2层”，导致后续无法找到传送点而反复拖拽地图。
可以看到log中“颜色反转后的匹配值为：0.449”，而“坐标(64, 878)”实际对应的是2层(见截图)

### 预期行为

正确点击预期的楼层
或判断当前所在楼层后跳过点击楼层的操作

### 实际行为

点击了错误的楼层

### 截图或录屏

![QQ截图20240330234118](https://github.com/linruowuyin/Fhoe-Rail/assets/23077424/8db10321-07a9-4575-a06c-918f29b3c552)

### 自动锄大地脚本版本

a1250e6

### 日志

> 23:12:11 - INFO   	| map.auto_map:240                         	- 03301255 - picture\fanhui_1.png
23:12:12 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(1772, 131)，坐标来源图片匹配度1.000
23:12:12 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（1）
23:12:12 - INFO   	| map.auto_map:240                         	- 03301255 - picture\3floor.png
23:12:14 - INFO   	| calculated.img_bitwise_check:366         	- 03301255 - 颜色反转后的匹配值为：0.449
23:12:14 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(64, 878)，坐标来源图片匹配度0.985
23:12:14 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（2）
23:12:14 - INFO   	| map.auto_map:240                         	- 03301255 - picture\map_4-3_point_8.png
23:12:15 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向下移动，当前所需匹配值0.975
23:12:22 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向左移动，当前所需匹配值0.975

**Comment by MioBKYan** [comment]
这不是楼层点击错误，你复刻就可发现即使在3层它也不会点到其他楼层，这个拖地图是因为打开地图后找不到map_4-3_point_8.png这个传送点才造成，这个传送点都会拖，是正常的

**Comment by smjes3** [comment]
提供完整log文件我们再分析下，目前已有对楼层进行处理我们自测没有这种情况发生。以下列出两种情况。

```
16:33:09 - INFO   	| map.auto_map:240                         	- 2.1.06 - picture\3floor.png
16:33:10 - INFO   	| calculated.img_bitwise_check:366         	- 2.1.06 - 颜色反转后的匹配值为：0.999
16:33:10 - INFO   	| map.auto_map:315                         	- 2.1.06 - 已在对应楼层，跳过选择楼层
```
这种情况是对比反转前后，取匹配度高的为正确，此时反转高，认为已在该楼层不进行额外点击。

```
16:36:27 - INFO   	| map.auto_map:240                         	- 2.1.06 - picture\3floor.png
16:36:28 - INFO   	| calculated.img_bitwise_check:366         	- 2.1.06 - 颜色反转后的匹配值为：0.980
16:36:29 - INFO   	| calculated.click:135                     	- 2.1.06 - 点击坐标(64, 792)，坐标来源图片匹配度1.000
```
这种情况原图片匹配度高，需要点击。

**Comment by 0frostmourne0** [comment]
完整log是这样的

> 23:10:08 - INFO   	| log.webhook_and_log:61                   	- 03301255 - [0;96;40m酒店梦境-12[0m
23:10:08 - INFO   	| map.auto_map:234                         	- 03301255 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-3_12
23:10:08 - INFO   	| map.auto_map:240                         	- 03301255 - map
23:10:08 - INFO   	| calculated.on_interface:1131             	- 03301255 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
23:10:08 - INFO   	| calculated.on_interface:1132             	- 03301255 - 检测图片序号为0，匹配度0.995，匹配位置为(233, 64)
23:10:11 - INFO   	| map.map_init:38                          	- 03301255 - 识别点位(801, 986)
23:10:11 - INFO   	| map.map_init:39                          	- 03301255 - 地图最小化，识别图片匹配度0.993
23:10:12 - INFO   	| map.auto_map:240                         	- 03301255 - picture\fanhui_1.png
23:10:13 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(1772, 131)，坐标来源图片匹配度1.000
23:10:13 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（1）
23:10:13 - INFO   	| map.auto_map:240                         	- 03301255 - picture\3floor.png
23:10:15 - INFO   	| calculated.img_bitwise_check:366         	- 03301255 - 颜色反转后的匹配值为：0.449
23:10:15 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(64, 878)，坐标来源图片匹配度0.985
23:10:15 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（2）
23:10:15 - INFO   	| map.auto_map:240                         	- 03301255 - picture\map_4-3_point_8.png
23:10:16 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向下移动，当前所需匹配值0.975
23:10:23 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向左移动，当前所需匹配值0.975
23:10:29 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向上移动，当前所需匹配值0.975
23:10:35 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向右移动，当前所需匹配值0.975
23:10:42 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向下移动，当前所需匹配值0.965
23:10:48 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向左移动，当前所需匹配值0.965
23:10:55 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向上移动，当前所需匹配值0.965
23:11:01 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向右移动，当前所需匹配值0.965
23:11:07 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向下移动，当前所需匹配值0.955
23:11:14 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向左移动，当前所需匹配值0.955
23:11:20 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向上移动，当前所需匹配值0.955
23:11:25 - INFO   	| calculated.have_screenshot:273           	- 03301255 - 找到图片，匹配值：0.959
23:11:25 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(798, 333)，坐标来源图片匹配度0.959
23:11:27 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（3）
23:11:27 - INFO   	| map.auto_map:240                         	- 03301255 - picture\transfer.png
23:12:06 - INFO   	| fhoe.choose_map_debug:78                 	- 03301255 - 3_12
23:12:06 - INFO   	| fhoe.choose_map_debug:79                 	- 03301255 - 4-3_12
23:12:06 - INFO   	| fhoe.main:128                            	- 03301255 - 

log里显示“找到图片，匹配值：0.959” ，实际并没有找到点位，此时屏幕上也没有传送按钮
23:11:27 显示“传送点击”就一直卡在那
23:12:06 我手动关掉了程序

**Comment by smjes3** [comment]
帮忙查找一下日志其他地方的picture\3floor.png下方有颜色反转的匹配值是多少，理论上这个0.449是一个离谱的数字，暂时不知道原因。

**Comment by 0frostmourne0** [comment]
> 23:22:15 - INFO   	| map.auto_map:234                         	- 03301255 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-3_15
23:22:15 - INFO   	| map.auto_map:240                         	- 03301255 - map
23:22:15 - INFO   	| calculated.on_interface:1131             	- 03301255 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
23:22:15 - INFO   	| calculated.on_interface:1132             	- 03301255 - 检测图片序号为0，匹配度0.995，匹配位置为(233, 64)
23:22:19 - INFO   	| map.map_init:38                          	- 03301255 - 识别点位(802, 986)
23:22:19 - INFO   	| map.map_init:39                          	- 03301255 - 地图最小化，识别图片匹配度0.996
23:22:19 - INFO   	| map.auto_map:240                         	- 03301255 - picture\fanhui_1.png
23:22:20 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(1772, 131)，坐标来源图片匹配度1.000
23:22:20 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（1）
23:22:20 - INFO   	| map.auto_map:240                         	- 03301255 - picture\3floor.png
23:22:22 - INFO   	| calculated.img_bitwise_check:366         	- 03301255 - 颜色反转后的匹配值为：0.975
23:22:22 - INFO   	| calculated.click:135                     	- 03301255 - 点击坐标(64, 878)，坐标来源图片匹配度0.985
23:22:22 - INFO   	| map.auto_map:345                         	- 03301255 - 传送点击（2）
23:22:22 - INFO   	| map.auto_map:240                         	- 03301255 - picture\map_4-3_point_8.png
23:22:24 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向下移动，当前所需匹配值0.975
23:22:30 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向左移动，当前所需匹配值0.975
23:22:36 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向上移动，当前所需匹配值0.975
23:22:42 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向右移动，当前所需匹配值0.975
23:22:49 - INFO   	| map.find_transfer_point:172              	- 03301255 - 开始移动地图，向下移动，当前所需匹配值0.965

这个map_4-3_15，显示0.975，但它还是点的(64, 878)，也就是2层……

**Comment by smjes3** [comment]
```
16:39:41 - INFO   	| map.auto_map:234                         	- 2.1.06 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-3_15
16:39:41 - INFO   	| map.auto_map:240                         	- 2.1.06 - map
16:39:41 - INFO   	| calculated.on_interface:1131             	- 2.1.06 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
16:39:41 - INFO   	| calculated.on_interface:1132             	- 2.1.06 - 检测图片序号为0，匹配度0.995，匹配位置为(233, 64)
16:39:44 - INFO   	| map.map_init:38                          	- 2.1.06 - 识别点位(802, 986)
16:39:44 - INFO   	| map.map_init:39                          	- 2.1.06 - 地图最小化，识别图片匹配度0.996
16:39:45 - INFO   	| map.auto_map:240                         	- 2.1.06 - picture\fanhui_1.png
16:39:46 - INFO   	| calculated.click:135                     	- 2.1.06 - 点击坐标(1772, 131)，坐标来源图片匹配度1.000
16:39:46 - INFO   	| map.auto_map:345                         	- 2.1.06 - 传送点击（1）
16:39:46 - INFO   	| map.auto_map:240                         	- 2.1.06 - picture\3floor.png
16:39:47 - INFO   	| calculated.img_bitwise_check:366         	- 2.1.06 - 颜色反转后的匹配值为：0.999
16:39:47 - INFO   	| map.auto_map:315                         	- 2.1.06 - 已在对应楼层，跳过选择楼层
```

好奇怪，目前只有你反馈是这样的，bug先挂在这里，我们看下能不能优化图片尝试解决。

**Comment by smjes3** [comment]
更新最新源码或使用2.1.08，看下还会不会，对图片优化增大了不同楼层的图片差异。
@0frostmourne0

**Comment by 0frostmourne0** [comment]
> 12:01:37 - INFO   	| map.auto_map:234                         	- 03310257 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-3_12
12:01:37 - INFO   	| map.auto_map:240                         	- 03310257 - map
12:01:37 - INFO   	| calculated.on_interface:1135             	- 03310257 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
12:01:37 - INFO   	| calculated.on_interface:1136             	- 03310257 - 检测图片序号为0，匹配度0.994，匹配位置为(233, 64)
12:01:40 - INFO   	| map.map_init:38                          	- 03310257 - 识别点位(802, 986)
12:01:40 - INFO   	| map.map_init:39                          	- 03310257 - 地图最小化，识别图片匹配度0.990
12:01:41 - INFO   	| map.auto_map:240                         	- 03310257 - picture\fanhui_1.png
12:01:42 - INFO   	| calculated.click:135                     	- 03310257 - 点击坐标(1772, 131)，坐标来源图片匹配度1.000
12:01:42 - INFO   	| map.auto_map:345                         	- 03310257 - 传送点击（1）
12:01:42 - INFO   	| map.auto_map:240                         	- 03310257 - picture\3floor.png
12:01:43 - INFO   	| calculated.img_bitwise_check:366         	- 03310257 - 颜色反转后的匹配值：0.000，反转前匹配值：1.000
12:01:43 - INFO   	| calculated.click:135                     	- 03310257 - 点击坐标(54, 879)，坐标来源图片匹配度0.966
12:01:43 - INFO   	| map.auto_map:345                         	- 03310257 - 传送点击（2）
12:01:43 - INFO   	| map.auto_map:240                         	- 03310257 - picture\map_4-3_point_8.png
12:01:45 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向下移动，当前所需匹配值0.975
12:01:51 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向左移动，当前所需匹配值0.975
12:01:57 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向上移动，当前所需匹配值0.975
12:02:03 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向右移动，当前所需匹配值0.975
12:02:10 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向下移动，当前所需匹配值0.965
12:02:16 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向左移动，当前所需匹配值0.965
12:02:22 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向上移动，当前所需匹配值0.965
12:02:29 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向右移动，当前所需匹配值0.965
12:02:35 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向下移动，当前所需匹配值0.955
12:02:42 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向左移动，当前所需匹配值0.955
12:02:48 - INFO   	| map.find_transfer_point:172              	- 03310257 - 开始移动地图，向上移动，当前所需匹配值0.955
12:02:52 - INFO   	| calculated.have_screenshot:273           	- 03310257 - 找到图片，匹配值：0.959
12:02:53 - INFO   	| calculated.click:135                     	- 03310257 - 点击坐标(798, 337)，坐标来源图片匹配度0.959
12:02:55 - INFO   	| map.auto_map:345                         	- 03310257 - 传送点击（3）
12:02:55 - INFO   	| map.auto_map:240                         	- 03310257 - picture\transfer.png

map_4-3_12，颜色反转后的匹配值：0.000，好像比之前更离谱了……

**Comment by smjes3** [comment]
> 12:01:43 - INFO | calculated.img_bitwise_check:366 - 03310257 - 颜色反转后的匹配值：0.000，反转前匹配值：1.000
> 12:01:43 - INFO | calculated.click:135 - 03310257 - 点击坐标(54, 879)，坐标来源图片匹配度0.966

这部分好奇怪，如果反转前是1.000，第二条来源图片匹配度应该也是1.000。
我这里尝试改一下参数形式看下是不是传错了。你可以试一下更新最新源码看看。

**Comment by 0frostmourne0** [comment]
> 12:44:26 - INFO   	| map.auto_map:243                         	- 03311238 - picture\3floor.png
12:44:27 - INFO   	| calculated.img_bitwise_check:366         	- 03311238 - 颜色反转后的匹配值：0.000，反转前匹配值：0.000
12:44:27 - INFO   	| map.auto_map:318                         	- 03311238 - 已在对应楼层，跳过选择楼层

最新版正常了，感谢大佬

**Comment by smjes3** [comment]
不对。。。这也没有正常，属于bug状态下误打误撞了，匹配值为0肯定不正常哇。
```
12:50:18 - INFO   	| map.auto_map:243                         	- 03310206 - picture\2floor.png
12:50:19 - INFO   	| calculated.img_bitwise_check:366         	- 03310206 - 颜色反转后的匹配值：0.924，反转前匹配值：1.000
12:50:19 - INFO   	| calculated.click:135                     	- 03310206 - 点击坐标(54, 878)，坐标来源图片匹配度1.000
```
这种两个匹配值的才对，我再看看问题。

**Comment by smjes3** [comment]
> > 12:44:26 - INFO   	| map.auto_map:243                         	- 03311238 - picture\3floor.png
> > 12:44:27 - INFO   	| calculated.img_bitwise_check:366         	- 03311238 - 颜色反转后的匹配值：0.000，反转前匹配值：0.000
> > 12:44:27 - INFO   	| map.auto_map:318                         	- 03311238 - 已在对应楼层，跳过选择楼层
> 
> 最新版正常了，感谢大佬

思前想后找不到问题，怀疑有可能是你本地环境问题，愿意帮助测试的话能试一下打包好环境的版本看看log也会有问题吗？

https://github.com/linruowuyin/Fhoe-Rail/releases/tag/2.1.09

**Comment by 0frostmourne0** [comment]
> 13:31:30 - INFO   	| map.auto_map:348                         	- 2.1.09 - 传送点击（1）
13:31:30 - INFO   	| map.auto_map:243                         	- 2.1.09 - picture\3floor.png
13:31:30 - INFO   	| calculated.img_bitwise_check:366         	- 2.1.09 - 颜色反转后的匹配值：0.000，反转前匹配值：1.000
13:31:30 - INFO   	| calculated.click:135                     	- 2.1.09 - 点击坐标(54, 879)，坐标来源图片匹配度0.966
13:31:31 - INFO   	| map.auto_map:348                         	- 2.1.09 - 传送点击（2）
13:31:31 - INFO   	| map.auto_map:243                         	- 2.1.09 - picture\map_4-3_point_8.png
13:31:32 - INFO   	| map.find_transfer_point:175              	- 2.1.09 - 开始移动地图，向下移动，当前所需匹配值0.975
13:31:38 - INFO   	| map.find_transfer_point:175              	- 2.1.09 - 开始移动地图，向左移动，当前所需匹配值0.975
13:31:44 - INFO   	| map.find_transfer_point:175              	- 2.1.09 - 开始移动地图，向上移动，当前所需匹配值0.975
13:31:51 - INFO   	| map.find_transfer_point:175              	- 2.1.09 - 开始移动地图，向右移动，当前所需匹配值0.975
13:31:53 - INFO   	| calculated.have_screenshot:273           	- 2.1.09 - 找到图片，匹配值：0.997
13:31:54 - INFO   	| calculated.click:135                     	- 2.1.09 - 点击坐标(759, 483)，坐标来源图片匹配度0.997
13:31:56 - INFO   	| map.auto_map:348                         	- 2.1.09 - 传送点击（3）
13:31:56 - INFO   	| map.auto_map:243                         	- 2.1.09 - picture\transfer.png
13:32:00 - INFO   	| calculated.click:135                     	- 2.1.09 - 点击坐标(1655, 970)，坐标来源图片匹配度1.000
13:32:02 - INFO   	| calculated.blackscreen_check:1013        	- 2.1.09 - 当前黑屏，值为0.000 < 10
13:32:04 - INFO   	| calculated.is_blackscreen:1033           	- 2.1.09 - 匹配到finish_fighting.png，匹配度0.994
13:32:04 - INFO   	| calculated.run_mapload_check:1089        	- 2.1.09 - 地图载毕，用时 3.9 秒

这是[2.1.09](https://github.com/linruowuyin/Fhoe-Rail/releases/tag/2.1.09)集成版生成的log。
log里的点击坐标(54, 879)，还是2层……而实际上它想点的应该是3floor.png

**Comment by smjes3** [comment]
> 但是即便楼层错了，最后它还是找到了点位，并且传送了过去……
部分点位图对于跨楼层有做过优化，对楼层的依赖没有很强。所以不太影响。

> log里的点击坐标(54, 879)，还是2层……而实际上它想点的应该是3floor.png
这个问题确实好奇怪，反转前匹配值和坐标来源图片匹配度调用的是同一个方法，不应该不一样。

**Comment by 0frostmourne0** [comment]
要是我的个例的话也没必要折腾了，感觉问题有点迷……
我自己把那些floor3都删了也能勉强用，只要一口气跑下来就不太需要判断楼层。

**Comment by smjes3** [comment]
确实找不到原因了。那这个问题我先关闭了。
