### ISSUE TITLE
黄泉锄地提前结束

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#205]
### 问题描述

黄泉做队长时，锄地到白日梦酒店自动结束了

### 预期行为

不应该提前结束

### 实际行为

提前结束跑图

### 截图或录屏

目前使用黄泉做队长锄地时发现两个BUG
1、卡基座舰段
2、白日梦酒店自动结束锄地
[2.1.08日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14814255/2.1.08.log)
![黄泉锄地卡基座舱段](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/6edc8e23-f2f6-4918-b74d-2ecf73bb5b81)
![黄泉锄地提前结束点01](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/234c8d0a-4f87-4183-a3d4-c45e566184b6)

### 自动锄大地脚本版本

2.1.08

### 日志

目前使用黄泉做队长锄地时发现两个BUG
1、卡基座舰段
2、白日梦酒店自动结束锄地
日志在附件哈
[2.1.08日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14814255/2.1.08.log)

**Comment by smjes3** [comment]
> 1、卡基座舰段

尝试重新运行看下是否必定出现，我这里测没问题，08更之前的版本确实会。

> 2、白日梦酒店自动结束锄地

结束点位正确，后面的地图还没录。

**Comment by jelly0925** [comment]
补充了视频和日志
黄泉队长锄地问题反馈
视频5分14秒寻路异常，6分12秒寻路异常，16分21秒寻路异常，32分16秒角色停留很久，34分路径错误造成漏怪，48分27秒错过怪，白日梦退出锄地。2.1新地图黄泉没有正常进行。
https://www.dropbox.com/scl/fi/y6ro1tv6p9bqh584zmd2q/5-14-6-12-16-21-32-16-34-48-27.mp4?rlkey=z31kzc3uz6ftc9kf5dzokq53n&dl=0
[2.1.09日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14814805/2.1.09.log)

**Comment by MioBKYan** [comment]
黄泉新地图还没增加，只能锄到酒店，刚提交了今天优化的29张图，晚点更新后明天再看看还漏多少

**Comment by smjes3** [comment]
> 补充了视频和日志 黄泉队长锄地问题反馈 视频5分14秒寻路异常，6分12秒寻路异常，16分21秒寻路异常，32分16秒角色停留很久，34分路径错误造成漏怪，48分27秒错过怪，白日梦退出锄地。2.1新地图黄泉没有正常进行。 

5:14，空跑寻路异常，但是第一次跑应该没问题，因为太仆司-4落地左侧是有一个紫色罐子
6:12，待修复
16:21，空跑寻路异常，但是第一次跑应该没问题，因为丹鼎司-1落地左侧是有一个紫色罐子
32:16，已修复
34:00，漏怪待观察
48:27，漏怪待观察

**Comment by jelly0925** [comment]
早上好呀，周一黄泉锄地好卡在领取模拟宇宙积分奖励，正常版本好像不会版本2.1.10

**Comment by smjes3** [comment]
这块逻辑没改，日志发上来看看哈。

**Comment by jelly0925** [comment]
2.1.11问题跟进
13分错过怪物，14分24错过怪物，29分05错过怪物，36分路径错误，37分30移动漏怪，43分13路径未经过，46分15路径错误，55分20错过怪，1时28分54的怪一直没经过。
https://www.dropbox.com/scl/fi/y5g9l08i3xfbprplp4b28/13-14-24-29-05-36-37-30-43-13-46-15-55-20.mp4?rlkey=b48vze7b9t5h6nh9lh41u7bdz&dl=0
[2.1.11日志文件.log](https://gi
![2 1 11bug截图01](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/39f0cdea-4773-41e8-92b9-9f827d345fc8)
thub.com/linruowuyin/Fhoe-Rail/files/14825388/2.1.11.log)

**Comment by jelly0925** [comment]
黄泉今天锄地一直卡在快速恢复界面，
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14833100/default.log)
https://www.dropbox.com/scl/fi/feakzn6k766xpii8eb6jm/.mp4?rlkey=kbws18zn92vwpdpcfdh65wowg&dl=0
![反复在这个界面弹出关闭](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/c6b948c5-4298-4397-8586-0ce9432a5fef)

**Comment by smjes3** [comment]
> 黄泉今天锄地一直卡在快速恢复界面

黄泉目前只吃七巧零食。经过多人反馈不想吃垃圾做成的食物后的改动，所以需要至少单次备足100左右奇巧零食。

**Comment by jelly0925** [comment]
> > 黄泉今天锄地一直卡在快速恢复界面
> 
> 黄泉目前只吃七巧零食。经过多人反馈不想吃垃圾做成的食物后的改动，所以需要至少单次备足100左右奇巧零食。

哦
