### ISSUE TITLE
[Bug] 黄泉锄地没打中怪

### ISSUE THREAD

**Issue by xibaibai9527** [linruowuyin/Fhoe-Rail#210]
### 问题描述

残响回廊第一个怪，就是怪物在大球旁边来回巡逻，黄泉只用了一次秘技，并没有打中怪物。随后就被怪物偷袭了。
进入战斗后，莫名其妙的一直按esc，而不是自动战斗。

因为怪物一直在走动，秘技的寻怪没什么优化，还是应该多用几次。

另外，我是从三月七小助手那边过来的，边缘通路·丰饶花蕾 那边的几个怪全都漏了，但换到这边走了一遍又能锄上了。
三月七那边被偷袭后可自动战斗。

另外询问一下，如果战斗界面死了，会自动吃复活药吗，因为黄泉三带一，有几个1级角色想练

### 预期行为

-

### 实际行为

-

### 自动锄大地脚本版本

2.1.10

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14822170/default.log)
[三月七.log](https://github.com/linruowuyin/Fhoe-Rail/files/14822173/default.log)

**Comment by xibaibai9527** [comment]
好了，跑完一遍了，弄明白了，原来漏怪才是正常的……
如果能优化一下算法就好了，根据小地图红点、怪物发现时的问号（和问号旁边的箭头）来确定怪物的方向

另外能否不打金人，我这练度打的很勉强啊

**Comment by smjes3** [comment]
> 因为怪物一直在走动，秘技的寻怪没什么优化，还是应该多用几次。

请等待路线优化

> 三月七那边被偷袭后可自动战斗。

三月七使用的就是这个项目。目前被偷袭后有概率没有识别到战斗，这个是目前方案缺陷，还没有好办法，随着地图优化，遇袭概率会大大降低

> 如果战斗界面死了，会自动吃复活药吗

不会，自行保证能够打得过。

> 另外能否不打金人，我这练度打的很勉强啊

自行保证能够打得过。

**Comment by vvincee7** [comment]
一级角色建议拉到60级再开始，经验大头都在后面其实

**Comment by xibaibai9527** [comment]
谢谢回复
另外金人那里自己找到了解决办法，地图文件3-4-2，不要直接删除，而是进去清空按键就行了

**Comment by smjes3** [comment]
> 没打中怪，然后2-3-1被认为执行完毕，进入2-3-2了，打开地图了，但这个间隙被怪物偷袭，于是不停的在按esc

确实是这样，这块方案还在思考。

**Comment by smjes3** [comment]
增加地图打开速度尝试解决该问题。
