### ISSUE TITLE
[Bug] 黄泉跑图时，吃药恢复战技点会经常卡住 不点确定键

### ISSUE THREAD

**Issue by yangysc** [linruowuyin/Fhoe-Rail#211]
### 问题描述

如截图所示，在吃药恢复战技点时候，经常卡住不自动点确定键，直到人工干预

### 预期行为

自动点确定键

### 实际行为

经常卡住不自动点确定键

### 截图或录屏

![image](https://github.com/linruowuyin/Fhoe-Rail/assets/8980981/8d033219-47a5-441f-9062-9dca9a883969)

### 自动锄大地脚本版本

2.1.10

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14822698/default.log)

**Comment by smjes3** [comment]
```
16:46:19 - INFO   	| calculated.click:135                     	- 2.1.09 - 点击坐标(1109, 386)，坐标来源图片匹配度0.985
```

经过日志查询，此处提示点击了奇巧零食，但是实际未点击到，怀疑某个代码引起，尝试进行修复。

**Comment by Scelus-et-poena** [comment]
还是会出现这种情况

**Comment by smjes3** [comment]
> 还是会出现这种情况

发送一下日志，是2.1.11版本吗

**Comment by Scelus-et-poena** [comment]
> > 还是会出现这种情况
> 
> 发送一下日志，是2.1.11版本吗

是2.1.11版本的。这是2024.4.3中午12点开的

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14846694/default.log)
一把

**Comment by Scelus-et-poena** [comment]
> > 是2.1.11版本的。这是2024.4.3中午12点开的一把
> 
> 你发的日志没有表明出现了该情况。
> 
> 你需要给我出现该情况那天的日志才可以哈。

就是这个啊

**Comment by smjes3** [comment]
日志显示每次均检测到了奇巧零食，并且点击两次进行食用，你卡住的准确时间点能知道吗，目前看你的日志是没问题

**Comment by yangysc** [comment]
Hi, @smjes3 
如下图所示，2.1.12版本。
感觉不是识别的问题，而是偶尔出现没有点击**确定键**的问题。现在还是在卡着（日志如下），人为点一下确定就能继续运行。
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14848190/default.log)

![image](https://github.com/linruowuyin/Fhoe-Rail/assets/8980981/350c0b68-d379-44d9-88ce-3abfa6f2b727)

**Comment by 0frostmourne0** [comment]
用昨天的版本确实卡了一次，然后换了今天的版本把log搞没了……
当时看log大概意思是脚本以为进战斗了，在等待战斗结束，而实际画面是奇巧零食。
这种触发概率非常低，全程只触发了一次。

**Comment by smjes3** [comment]
> Hi, @smjes3 如下图所示，2.1.12版本。 感觉不是识别的问题，而是偶尔出现没有点击**确定键**的问题。现在还是在卡着（日志如下，卡的时间太久报错了，cmd log截图见最后），人为点一下确定就能继续运行。 

知悉，怀疑是E之后识别秘技不足的时间不足导致的低概率事件，这里尝试修复试试。

**Comment by smjes3** [comment]
提交2.1.13r，改了秘技不足的识别，理论上加了0.2秒应该没问题了。
