### ISSUE TITLE
无法点击匹诺康尼大地图了

### ISSUE THREAD

**Issue by xibaibai9527** [linruowuyin/Fhoe-Rail#224]
### 问题描述

打到4-2-3稚子的梦地图时，因为不小心转了一下视角，所以我停下脚本重新运行，发现不管怎么弄都不能自动点击大地图的匹诺康尼星球，直接在选择星球的地方停住了

### 预期行为

-

### 实际行为

-

### 自动锄大地脚本版本

2.1.13r

### 日志

    2024年04月03日 晴
    明天就周六了我知道你不上班，但是我怕你睡懒觉不吃早饭饿坏自己，我早晨4点去菜市场买了新鲜活鸡给你炖鸡汤，阿姨给我用箱子装了起来，我骑上我280买的电动车哼着小调回家，心想你一定会被我感动的，箱子半路开了，鸡跑了，拐到了一个胡同里，凌晨4点的胡同还有穿超短裙和大叔聊天的美女，不禁感叹这个世界变了，她问我找什么，…………。对不起，我爱你

19:03:48 - INFO   	| fhoe.main:129                            	- 2.1.13r - 
19:03:48 - INFO   	| fhoe.main:130                            	- 2.1.13r - 切换至游戏窗口，请确保跑图角色普攻为远程
19:03:48 - INFO   	| fhoe.main:134                            	- 2.1.13r - 开始运行，请勿移动鼠标和键盘.向着星...呃串台了
19:03:48 - INFO   	| fhoe.main:135                            	- 2.1.13r - 黑塔：7128；雅利洛：19440；罗浮：42596；匹诺康尼：30996
19:03:48 - INFO   	| fhoe.main:136                            	- 2.1.13r - 2.0版本单角色锄满100160经验（fhoe当前做不到）
19:03:48 - INFO   	| fhoe.main:137                            	- 2.1.13r - 免费软件，倒卖的曱甴冚家铲，请尊重他人的劳动成果
19:03:48 - INFO   	| log.webhook_and_log:61                   	- 2.1.13r - [0;96;40m稚子的梦-2[0m
19:03:48 - INFO   	| calculated.try_click_pass:968            	- 2.1.13r - 判断是否存在月卡
19:03:48 - INFO   	| calculated.try_click_pass:973            	- 2.1.13r - 识别点位(241, 81)
19:03:48 - INFO   	| calculated.try_click_pass:975            	- 2.1.13r - 识别到此刻正在主界面，无月卡，图片匹配度: 0.94 (241, 81)
19:03:49 - INFO   	| calculated.monthly_pass_check:939        	- 2.1.13r - 月卡检查时间更新至：2024-04-03 19:03:48.757064
19:03:49 - INFO   	| map.auto_map:245                         	- 2.1.13r - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-2_2
19:03:49 - INFO   	| map.auto_map:251                         	- 2.1.13r - map
19:03:52 - INFO   	| map.map_init:39                          	- 2.1.13r - 识别点位(625, 986)
19:03:52 - INFO   	| map.map_init:41                          	- 2.1.13r - 地图最小化，识别图片匹配度0.998
19:03:53 - INFO   	| map.auto_map:251                         	- 2.1.13r - picture\map_4-2_point_1.png
19:03:54 - INFO   	| calculated.click:137                     	- 2.1.13r - 点击坐标(854, 522)，坐标来源图片匹配度0.954
19:03:55 - INFO   	| map.auto_map:359                         	- 2.1.13r - 传送点击（1）
19:03:55 - INFO   	| map.auto_map:251                         	- 2.1.13r - picture\transfer.png
19:07:26 - INFO   	| fhoe.print_version:91                    	- 2.1.13r - 当前版本：2.1.13r
19:07:26 - INFO   	| fhoe.print_version:92                    	- 2.1.13r - config.json
19:07:29 - INFO   	| fhoe.choose_map_debug:51                 	- 2.1.13r - 设置完成
19:07:40 - INFO   	| fhoe.choose_map_debug:51                 	- 2.1.13r - 设置完成
19:07:44 - INFO   	| fhoe.choose_map_debug:78                 	- 2.1.13r - 2_3
19:07:44 - INFO   	| fhoe.choose_map_debug:79                 	- 2.1.13r - 4-2_3
19:07:44 - INFO   	| fhoe.main:128                            	- 2.1.13r -

**Comment by xibaibai9527** [comment]
刚刚回退到了2.1.12，稚子的梦能进行了，但在4-4-6又出现了同样的问题
正常使用没事，但只要停止后继续，就会在选择星球界面，不停的拖曳地图

**Comment by smjes3** [comment]
日志传送完整文件上来，目前你给的日志看不出问题。

拖拽地图是正常的，主要是等待拖拽结束后是否能找到星球？

还有就是你中途关闭，再继续的时候理论上你没办法很准确了解该从哪里开始的话，最保险的是比如4-4-6关闭，那么建议你4-4-1开始。如果你要从4-4-6继续，你需要自己会看map.json文件了解4-4-6是从什么操作起始的。

**Comment by xibaibai9527** [comment]
> 00:03:42 - INFO   	| fhoe.main:129                            	- 2.1.12 - 
> 00:03:42 - INFO   	| fhoe.main:130                            	- 2.1.12 - 切换至游戏窗口，请确保跑图角色普攻为远程
> 00:03:43 - INFO   	| fhoe.main:134                            	- 2.1.12 - 开始运行，请勿移动鼠标和键盘.向着星...呃串台了
> 00:03:43 - INFO   	| fhoe.main:135                            	- 2.1.12 - 黑塔：7128；雅利洛：19440；罗浮：42596；匹诺康尼：30996
> 00:03:43 - INFO   	| fhoe.main:136                            	- 2.1.12 - 2.0版本单角色锄满100160经验（fhoe当前做不到）
> 00:03:43 - INFO   	| fhoe.main:137                            	- 2.1.12 - 免费软件，倒卖的曱甴冚家铲，请尊重他人的劳动成果
> 00:03:43 - INFO   	| log.webhook_and_log:61                   	- 2.1.12 - [0;96;40m朝露公馆-6[0m
> 00:03:43 - INFO   	| calculated.try_click_pass:958            	- 2.1.12 - 判断是否存在月卡
> 00:03:43 - INFO   	| calculated.try_click_pass:963            	- 2.1.12 - 识别点位(241, 81)
> 00:03:43 - INFO   	| calculated.try_click_pass:965            	- 2.1.12 - 识别到此刻正在主界面，无月卡，图片匹配度: 0.98 (241, 81)
> 00:03:43 - INFO   	| calculated.monthly_pass_check:929        	- 2.1.12 - 月卡检查时间更新至：2024-04-04 00:03:43.131965
> 00:03:43 - INFO   	| map.auto_map:237                         	- 2.1.12 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-4_6
> 00:03:43 - INFO   	| map.auto_map:243                         	- 2.1.12 - map
> 00:03:43 - INFO   	| calculated.on_interface:1166             	- 2.1.12 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
> 00:03:43 - INFO   	| calculated.on_interface:1167             	- 2.1.12 - 检测图片序号为0，匹配度0.982，匹配位置为(233, 64)
> 00:03:46 - INFO   	| map.map_init:39                          	- 2.1.12 - 识别点位(625, 986)
> 00:03:46 - INFO   	| map.map_init:41                          	- 2.1.12 - 地图最小化，识别图片匹配度0.998
> 00:03:47 - INFO   	| map.auto_map:243                         	- 2.1.12 - picture\fanhui_1.png
> 00:03:48 - INFO   	| calculated.click:135                     	- 2.1.12 - 点击坐标(1799, 131)，坐标来源图片匹配度0.953
> 00:03:48 - INFO   	| map.auto_map:348                         	- 2.1.12 - 传送点击（1）
> 00:03:48 - INFO   	| map.auto_map:243                         	- 2.1.12 - picture\2floor.png
> 00:03:49 - INFO   	| calculated.img_bitwise_check:366         	- 2.1.12 - 颜色反转后的匹配值：0.804，反转前匹配值：0.873
> 00:04:19 - INFO   	| calculated.click_target:422              	- 2.1.12 - 查找图片超时 picture\2floor.png ，最相似图片匹配值 0.8776182532310486，所需匹配值 0.93
> 00:04:19 - INFO   	| map.auto_map:348                         	- 2.1.12 - 传送点击（2）
> 00:04:19 - INFO   	| log.webhook_and_log:61                   	- 2.1.12 - [0;96;40m朝露公馆-6[0m
> 00:04:19 - INFO   	| map.auto_map:237                         	- 2.1.12 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-4_6
> 00:04:19 - INFO   	| map.auto_map:243                         	- 2.1.12 - map
> 00:04:22 - INFO   	| calculated.on_interface:1174             	- 2.1.12 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.871


我又看了一遍，好像是卡在这里了：
00:03:47 - INFO   	| map.auto_map:243                         	- 2.1.12 - picture\fanhui_1.png
00:03:48 - INFO   	| calculated.click:135                     	- 2.1.12 - 点击坐标(1799, 131)，坐标来源图片匹配度0.953

说是点击了返回按钮，这个应该是3d大地图的吧？
但实际情况是，(1799, 131) 这个坐标正是“星轨航图”的位置，不知道为什么被匹配上了
所以说，正常从4-4-6开始不应该点进星球界面的吧？

**Comment by xibaibai9527** [comment]
> 00:30:16 - INFO   	| map.auto_map:237                         	- 2.1.12 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-5_1
> 00:30:16 - INFO   	| map.auto_map:243                         	- 2.1.12 - map
> 00:30:16 - INFO   	| calculated.on_interface:1166             	- 2.1.12 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
> 00:30:16 - INFO   	| calculated.on_interface:1167             	- 2.1.12 - 检测图片序号为0，匹配度0.982，匹配位置为(233, 64)
> 00:30:19 - INFO   	| map.map_init:39                          	- 2.1.12 - 识别点位(625, 986)
> 00:30:19 - INFO   	| map.map_init:41                          	- 2.1.12 - 地图最小化，识别图片匹配度0.998
> 00:30:21 - INFO   	| map.auto_map:243                         	- 2.1.12 - picture\fanhui_1.png
> 00:30:21 - INFO   	| calculated.click:135                     	- 2.1.12 - 点击坐标(1799, 131)，坐标来源图片匹配度0.953
> 00:30:22 - INFO   	| map.auto_map:348                         	- 2.1.12 - 传送点击（1）
> 00:30:22 - INFO   	| map.auto_map:243                         	- 2.1.12 - picture\orientation_1.png
> 00:30:25 - INFO   	| calculated.click:135                     	- 2.1.12 - 点击坐标(331, 380)，坐标来源图片匹配度0.930
> 00:30:25 - INFO   	| map.auto_map:348                         	- 2.1.12 - 传送点击（2）
> 00:30:25 - INFO   	| map.auto_map:243                         	- 2.1.12 - picture\orientation_5.png
> 00:30:26 - INFO   	| map.find_transfer_point:175              	- 2.1.12 - 开始移动地图，向下移动，当前所需匹配值0.975
> 00:30:32 - INFO   	| map.find_transfer_point:175              	- 2.1.12 - 开始移动地图，向左移动，当前所需匹配值0.975
> 00:30:37 - INFO   	| map.find_transfer_point:175              	- 2.1.12 - 开始移动地图，向上移动，当前所需匹配值0.975
> 00:30:43 - INFO   	| map.find_transfer_point:175              	- 2.1.12 - 开始移动地图，向右移动，当前所需匹配值0.975
> 

我现在都不知道发生什么事了，在4-5-1重新开始，匹配星球的阶段，我眼睁睁看着它点到了雅利洛6号
为什么从4-4-6一路走下去就正常，从4-5-1断开重连就不正常呢

**Comment by xibaibai9527** [comment]
看到最新的14版了，更新后好了

**Comment by smjes3** [comment]
> 00:03:47 - INFO | map.auto_map:243 - 2.1.12 - picture\fanhui_1.png
> 00:03:48 - INFO | calculated.click:135 - 2.1.12 - 点击坐标(1799, 131)，坐标来源图片匹配度0.953

14版本增加了返回的识别阈值防止点击到星轨航图，你说的这个我昨天确实发现了。
