### ISSUE TITLE
2.1.15 黄泉队长朝露公馆2个3D图怪没有打

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#229]
### 问题描述

朝露公馆--城市沙盘锄地结束从视频3时12分12秒到3时22分42秒鼠标都在移动地图，脚本跳过了朝露公馆的两个3D地图。

### 预期行为

朝露公馆--城市沙盘锄地结束应该正常切图

### 实际行为

朝露公馆--城市沙盘锄地结束卡移动地图很久

### 截图或录屏

视频编码有点问题，使用EDGE浏览器打开视频时间才是正常的，3小时左右，谷歌打开视频只显示30分钟
https://www.dropbox.com/scl/fi/ei9hxwnm1ljmus7f4vs2r/2024-04-05-07-07-21-2.1.15.mp4?rlkey=rfg795zdq5ec3m7ie31ku5cf3&dl=0
![朝露公馆BUG01](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/8f57d8eb-2c05-4a6f-b93e-717bf64dfc2d)

### 自动锄大地脚本版本

2.1.15

### 日志

[2.1.15日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14879528/2.1.15.log)

**Comment by smjes3** [comment]
颜色反转比对莫名出错造成的，这里把比对出错后重试5次尝试修复看看。
