### ISSUE TITLE
2.0.0.4版本锄大地有闪退、卡住传送等问题

### ISSUE THREAD

**Issue by BROWNBRONY** [linruowuyin/Fhoe-Rail#23]
> 2024-02-10 08:01:32,885 | INFO | 当前界面：模拟宇宙-主界面
> 2024-02-10 08:01:33,298 | DEBUG | 键盘按下 esc
> 2024-02-10 08:01:33,307 | DEBUG | 执行了一个操作
> 2024-02-10 08:01:33,309 | DEBUG | 等待：主界面
> 2024-02-10 08:01:33,810 | DEBUG | 目标图片：./assets/images/screen/main.png 相似度：0.25958988070487976
> 2024-02-10 08:01:34,818 | DEBUG | 等待：主界面
> 2024-02-10 08:01:35,338 | DEBUG | 目标图片：./assets/images/screen/main.png 相似度：0.8952875137329102
> 2024-02-10 08:01:36,346 | DEBUG | 等待：主界面
> 2024-02-10 08:01:37,016 | DEBUG | 目标图片：./assets/images/screen/main.png 相似度：0.9961727857589722
> 2024-02-10 08:01:37,033 | INFO | 切换到：主界面
> Honkai_Star_Rail.main:69 - 3.1 -
> 
>     2024年02月10日 晴
>     孩子生下来吧，我跟他姓
> 
> Honkai_Star_Rail.main:70 - 3.1 -
> Honkai_Star_Rail.main:71 - 3.1 - 切换至游戏窗口，请确保跑图角色普攻为远程
> Honkai_Star_Rail.main:75 - 3.1 - 开始运行，请勿移动鼠标和键盘.向着星...呃串台了
> Honkai_Star_Rail.main:76 - 3.1 - 黑塔：7128；雅利洛：19440；罗浮：42596；匹诺康尼：30996
> Honkai_Star_Rail.main:77 - 3.1 - 2.0版本单角色锄满100160经验（fhoe当前做不到）
> Honkai_Star_Rail.main:78 - 3.1 - 免费软件，倒卖的曱甴冚家铲，请尊重他人的劳动成果
> log.webhook_and_log:38 - 3.1 - 观景车厢
> map.auto_map:97 - 3.1 - 路线领航员：lrwy 感谢她(们)的无私奉献
> map.map_init:34 - 3.1 - 打开地图
> map.map_init:29 - 3.1 - 地图最小化
> map.auto_map:108 - 3.1 - 执行传送点击（1）
> map.auto_map:108 - 3.1 - 执行传送点击（2）
> map.auto_map:108 - 3.1 - 执行传送点击（3）
> map.auto_map:108 - 3.1 - 执行传送点击（4）
> map.auto_map:108 - 3.1 - 执行传送点击（5）

问题反馈：
1.锄大地完整运行时会最终卡在map.auto_map:108 - 3.1 - 执行传送点击（5）页面，并不会往下面运行。
2.锄大地单独运行某一地图时会直接退出程序（秒退）
p.s. 2.0.0.0版本更新后就已经出现匹诺康尼-白日梦酒店梦境-6卡住不继续运行的情况，同样是卡在“> map.auto_map:108 - 3.1 - 执行传送点击（5）”

**Comment by linruowuyin** [comment]
收到，排查中

**Comment by linruowuyin** [comment]
1.卡在传送点击是否是没开启小黑边的问题？刚试了一下都是正常的；
2.锄大地单独运行某一地图时会直接退出程序（秒退），具体是哪一地图呢

**Comment by linruowuyin** [comment]
选择地图功能目前是失灵的，晚点发25版本

**Comment by DragonQuestXI** [comment]
> 选择地图功能目前是失灵的，晚点发25版本

请问还需要提高画质吗，目前是分辨率1980 1080，渲染精度1.0，环境光非常高，其他全非常低或关

**Comment by BROWNBRONY** [comment]
1.卡在传送点击是否是没开启小黑边的问题？刚试了一下都是正常的；
q：如何开启小黑边呢，目前是1920*1080全屏，其他图形设置为系统默认
2.锄大地单独运行某一地图时会直接退出程序（秒退），具体是哪一地图呢
q：除了观景车厢外全部地图单独运行时会退出程序，而单独运行观景车厢就会在“map.auto_map:108 - 3.1 - 执行传送点击（5）”卡住

**Comment by BROWNBRONY** [comment]
[](https://github.com/linruowuyin/Fhoe-Rail/issues/25)
已找到小黑边，问题已解决
谢谢
