### ISSUE TITLE
[Bug] 黄泉总是进战斗后不停esc问题

### ISSUE THREAD

**Issue by xibaibai9527** [linruowuyin/Fhoe-Rail#231]
### 问题描述

黄泉总是进战斗后不停esc，每天大概都遇到两三次

经查，大概问题是没打中怪物，开启地图准备传送走了，但是这时候被怪物偷袭
进战斗不是问题，问题是完全不打怪，而是在不停esc，可能是脚本当现在还是在地图界面呢

作者上次说了会加快地图打开的速度，但这解决不了问题，问题的原因出自黄泉的秘技后摇特别长，这个时候是打不开地图的，有一秒多，必须等收刀完全才算结束。期间被怪偷袭的概率很大。

建议的解决方法：
最好的方法是地图全优化，漏怪的原因我猜测是每个人的硬盘不同，加载速度不同，所以地图制作者能砍到怪的地图位置，换一个人，怪物可能走到别的地方去了。这就得加大冗余，不是简单的工作量。
第二种方法，收刀后移动一下，快速取消后摇（但也有半秒）
或者收刀后平a一下，也能取消后摇，这个方法快，但有可能砍中怪物，得在后面再加一层判定
再就是当超过N次找不到图片的话，多加一个判断模块，判断是否进入战斗了。

这三种方法都应该能解决当前的问题吧，希望作者采纳

### 预期行为

-

### 实际行为

-

### 自动锄大地脚本版本

2.1.15

### 日志

-

**Comment by smjes3** [comment]
> 最好的方法是地图全优化，漏怪的原因我猜测是每个人的硬盘不同，加载速度不同，所以地图制作者能砍到怪的地图位置，换一个人，怪物可能走到别的地方去了。这就得加大冗余，不是简单的工作量。

不合适，只能算是尽量兼容。

> 第二种方法，收刀后移动一下，快速取消后摇（但也有半秒）

依然解决不了

> 收刀后平a一下，也能取消后摇，这个方法快，但有可能砍中怪物，得在后面再加一层判定

算是一个办法但是也可能砍不到。

> 当超过N次找不到图片的话，多加一个判断模块，判断是否进入战斗了。

可以ESC之后判断一下是不是在战斗试试。
