### ISSUE TITLE
[Bug] 鳞渊镜最后位置漏怪

### ISSUE THREAD

**Issue by belthil17** [linruowuyin/Fhoe-Rail#235]
### 问题描述

在使用黄泉版本锄大地后，设优先地图为匹诺康妮，打开两次锄大地的设置。每天在截图位置，都会漏掉一只怪，非常稳定，而且 每天能复现。
锄大地设置如下：
{"version":"2.1.16r","real_width":0,"real_height":0,"map_debug":false,"github_proxy":"","rawgithub_proxy":"","webhook_url":"","start":true,"picture_version":"0","star_version":"0","open_map":"m","script_debug":false,"auto_shutdown":0,"taskkill_name":"","auto_final_fight_e":true,"auto_run_in_map":true,"detect_fight_status_time":15,"map_version":"HuangQuan","main_map":"4","allow_run_again":true,"allow_run_next_day":false,"allow_map_buy":true,"allow_snack_buy":true,"auto_final_fight_e_cnt":20,"allow_fight_e_buy_prop":true}

### 预期行为

正常情况下，黄泉应该在此处多次E，尝试把所有怪都斩杀死。

### 实际行为

实际上只会少量E，然后因为这只怪的位置因为离墙壁较远，单纯E做不到斩杀，就会漏怪

### 截图或录屏

![photo_2024-04-04_11-32-11](https://github.com/linruowuyin/Fhoe-Rail/assets/52347608/008e1fb1-e8b4-4ad9-9275-a83850ac77ae)
![photo_2024-04-06_10-44-23](https://github.com/linruowuyin/Fhoe-Rail/assets/52347608/8f1f1290-47f7-490b-b8b5-0131ae679b03)

### 自动锄大地脚本版本

2.1.16r或者2.1.15均出现

### 日志

[日志文件.2024-04-05_04-16-44_016354.log](https://github.com/linruowuyin/Fhoe-Rail/files/14892079/2024-04-05_04-16-44_016354.log)
[日志文件.2024-04-04_01-06-16_442453.log](https://github.com/linruowuyin/Fhoe-Rail/files/14892080/2024-04-04_01-06-16_442453.log)
[日志文件.2024-04-03_04-14-44_568119.log](https://github.com/linruowuyin/Fhoe-Rail/files/14892081/2024-04-03_04-14-44_568119.log)
[日志文件.2024-04-02_04-13-15_917495.log](https://github.com/linruowuyin/Fhoe-Rail/files/14892082/2024-04-02_04-13-15_917495.log)
[日志文件.2024-04-01_04-23-09_649312.log](https://github.com/linruowuyin/Fhoe-Rail/files/14892083/2024-04-01_04-23-09_649312.log)

**Comment by smjes3** [comment]
#238 修了
