### ISSUE TITLE
[Bug] 黄泉锄地没有秘技点时，反复开关吃零食界面，不吃零食

### ISSUE THREAD

**Issue by yingxr** [linruowuyin/Fhoe-Rail#239]
### 问题描述

使用黄泉锄地，当秘技点为0后，点击E时发生
反复的弹出和退出补充秘技点窗口，不使用奇巧零食

### 预期行为

弹出补充秘技点窗口，点击奇巧零食，点击确定，继续使用黄泉的秘技锄地

### 实际行为

弹出补充秘技点窗口，2秒后退出补充秘技点窗口，秘技点仍然为0，接下来点击E时，重复此处的“实际行为”

### 截图或录屏

 
[202404072051.zip](https://github.com/linruowuyin/Fhoe-Rail/files/14897233/202404072051.zip)

### 自动锄大地脚本版本

2.1.16r

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14897221/default.log)

**Comment by smjes3** [comment]
config.json
请检查配置
"allow_fight_e_buy_prop":true

**Comment by yingxr** [comment]
问题已解决，感谢
这一误会的起因是我在`config.json`中直接修改了自选地图，导致"allow_fight_e_buy_prop"没有自动修改，所以不应当这样做

**Comment by smjes3** [comment]
> 问题已解决，感谢 这一误会的起因是我在`config.json`中直接修改了自选地图，导致"allow_fight_e_buy_prop"没有自动修改，所以不应当这样做

已增加一个判断，现在支持直接在config.json中修改自选地图且不会造成相关联动的配置错误。
