### ISSUE TITLE
2.0之后最近几个版本都是卡在观景车厢不执行"执行传送点击（5）"

### ISSUE THREAD

**Issue by mainytht** [linruowuyin/Fhoe-Rail#24]
之前的没问题，最后提示是
地图最小化
执行传送点击（1）
执行传送点击（2）
执行传送点击（3）
执行传送点击（4）
执行传送点击（5）

**Comment by mainytht** [comment]
包括2.0.25

**Comment by linruowuyin** [comment]
没开小黑边
![Uploading PixPin_2024-02-09_09-21-28.png…]()

**Comment by linruowuyin** [comment]
已处理完毕，使用灯泡代替小黑边。
