### ISSUE TITLE
残响回廊出现每日任务时，无法正常传送

### ISSUE THREAD

**Issue by HuangXianJin** [linruowuyin/Fhoe-Rail#240]
### 问题描述

残响回廊出现每日任务时，无法正常传送

### 预期行为

正常传送

### 实际行为

无法正常传送

### 自动锄大地脚本版本

2.1.7

### 日志

06:04:21 - INFO   	| map.auto_map:426                         	- 2.1.17 - map_2-2_5用时[1;92m『4.2秒』[0m,总计:[1;92m『8分22.7秒』[0m
06:04:21 - INFO   	| log.webhook_and_log:61                   	- 2.1.17 - [0;96;40m残响回廊-1[0m
06:04:21 - INFO   	| map.auto_map:274                         	- 2.1.17 - 路线领航员：[1;95m喵不可言,Starry-Wind,CDCP,lrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_2-3_1
06:04:21 - INFO   	| map.auto_map:280                         	- 2.1.17 - map
06:04:21 - INFO   	| map.map_init:34                          	- 2.1.17 - 打开地图
06:04:24 - INFO   	| calculated.on_interface:1207             	- 2.1.17 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
06:04:24 - INFO   	| calculated.on_interface:1208             	- 2.1.17 - 检测图片序号为0，匹配度0.993，匹配位置为(1193, 629)
06:04:24 - INFO   	| map.map_init:34                          	- 2.1.17 - 打开地图
06:04:27 - INFO   	| map.map_init:40                          	- 2.1.17 - 识别点位(1585, 1551)
06:04:27 - INFO   	| map.auto_map:280                         	- 2.1.17 - picture\orientation_1.png
06:04:28 - INFO   	| calculated.click:138                     	- 2.1.17 - 点击坐标(2601, 704)，坐标来源图片匹配度1.000
06:04:29 - INFO   	| map.auto_map:399                         	- 2.1.17 - 传送点击（1）
06:04:29 - INFO   	| map.auto_map:280                         	- 2.1.17 - picture\orientation_3.png
06:04:30 - INFO   	| calculated.have_screenshot:271           	- 2.1.17 - 找到图片，匹配值：0.993
06:04:30 - INFO   	| calculated.click:138                     	- 2.1.17 - 点击坐标(1904, 954)，坐标来源图片匹配度0.993
06:04:32 - INFO   	| map.auto_map:399                         	- 2.1.17 - 传送点击（2）
06:04:32 - INFO   	| map.auto_map:280                         	- 2.1.17 - picture\map_2-3.png
06:04:33 - INFO   	| calculated.click:138                     	- 2.1.17 - 点击坐标(2502, 1279)，坐标来源图片匹配度1.000
06:04:33 - INFO   	| map.auto_map:399                         	- 2.1.17 - 传送点击（3）
06:04:33 - INFO   	| map.auto_map:280                         	- 2.1.17 - picture\map_2-3_point_4.png
06:04:35 - INFO   	| calculated.click:138                     	- 2.1.17 - 点击坐标(1656, 1195)，坐标来源图片匹配度0.976
06:04:35 - INFO   	| map.auto_map:399                         	- 2.1.17 - 传送点击（4）
06:04:35 - INFO   	| map.auto_map:280                         	- 2.1.17 - picture\transfer.png
06:05:05 - INFO   	| calculated.click_target:433              	- 2.1.17 - 查找图片超时 picture\transfer.png ，最相似图片匹配值 0.8882873058319092，所需匹配值 0.93
06:05:05 - INFO   	| log.webhook_and_log:61                   	- 2.1.17 - [0;96;40m残响回廊-2[0m
06:05:05 - INFO   	| map.auto_map:274                         	- 2.1.17 - 路线领航员：[1;95m喵不可言,Starry-Wind,小明[0m 感谢她(们)的无私奉献，准备开始路线：map_2-3_2
06:05:05 - INFO   	| map.auto_map:280                         	- 2.1.17 - map
06:05:05 - INFO   	| map.map_init:34                          	- 2.1.17 - 打开地图
06:05:09 - INFO   	| calculated.on_interface:1207             	- 2.1.17 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
06:05:09 - INFO   	| calculated.on_interface:1208             	- 2.1.17 - 检测图片序号为0，匹配度0.993，匹配位置为(1193, 629)
06:05:09 - INFO   	| map.map_init:34                          	- 2.1.17 - 打开地图
06:05:12 - INFO   	| map.map_init:40                          	- 2.1.17 - 识别点位(1585, 1551)
06:05:12 - INFO   	| map.auto_map:280                         	- 2.1.17 - picture\map_2-3_point_2.png
06:05:43 - INFO   	| calculated.click_target:433              	- 2.1.17 - 查找图片超时 picture\map_2-3_point_2.png ，最相似图片匹配值 0.9160802364349365，所需匹配值 0.93
06:05:43 - INFO   	| map.auto_map:399                         	- 2.1.17 - 传送点击（1）
06:05:43 - INFO   	| log.webhook_and_log:61                   	- 2.1.17 - [0;96;40m残响回廊-2[0m
06:05:43 - INFO   	| map.auto_map:274                         	- 2.1.17 - 路线领航员：[1;95m喵不可言,Starry-Wind,小明[0m 感谢她(们)的无私奉献，准备开始路线：map_2-3_2
06:05:43 - INFO   	| map.auto_map:280                         	- 2.1.17 - map``

**Comment by smjes3** [comment]
目前暂无通用方案修复偶尔出现的日常任务影响传送点的问题。

打算采用在地图中增加一个冗余图片，避免日常任务影响。现在需要有该地区出现日常任务点击后的一个截图帮助提供下。

类似于
![map_2-5_point_3](https://github.com/linruowuyin/Fhoe-Rail/assets/33685788/a009d9d7-b8bd-445c-95ed-3053d8b1ca3e)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/33685788/a1e845f4-3aec-4602-9af4-7273b8726a20)

**Comment by smjes3** [comment]
没有再次出现
