### ISSUE TITLE
每天游戏会重置游戏界面右上角的自动按钮，造成角色和NPC对话

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#241]
### 问题描述

昨天开启了游戏凌晨4点自动锄地，今天早上去看的时候发现角色卡在会话界面（后面是我手动进行的），因为自动按钮是灰的造成对话没有完成，所以造成了锄地停止。因网络或者游戏卡顿原因难免会造成角色锄地线路异常，有概率触发NPC对话。

### 预期行为

看能不能添加一个简单判断，在脚本触发会话的时候自动取消或者把右上角的自动按钮点击一次。

### 实际行为

每天游戏重置游戏界面右上角的自动按钮行为

### 截图或录屏

https://www.dropbox.com/scl/fi/r32t6o36ba8ysojyjae7e/4-8.mp4?rlkey=g1o9qvdxki45tgpflnxr8oc5d&dl=0
录屏时间2:24:57前后的视频可以看一下哈。
![锄地自动按钮优化](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/1a414a4e-9a69-4077-b61d-46856665baa2)

### 自动锄大地脚本版本

2.1.17

### 日志

[2.1.17日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14905968/2.1.17.log)

**Comment by vvincee7** [comment]
话说今天早上我也卡在了购买艾迪恩代币的对话那里，原来是这个原因吗

**Comment by smjes3** [comment]
> 话说今天早上我也卡在了购买艾迪恩代币的对话那里，原来是这个原因吗

不是一个原因。

**Comment by vvincee7** [comment]
看了一下，日志长这样

06:53:52 - INFO   	| log.webhook_and_log:61                   	- 2.1.16r - [0;96;40m艾迪恩代币-1[0m
06:53:52 - INFO   	| map.auto_map:243                         	- 2.1.16r - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_4-1_0
06:53:52 - INFO   	| map.auto_map:249                         	- 2.1.16r - need_allow_map_buy
06:53:52 - INFO   	| map.auto_map:249                         	- 2.1.16r - check
06:53:52 - INFO   	| map.auto_map:258                         	- 2.1.16r - 今天Monday，尝试购买
06:53:52 - INFO   	| map.auto_map:249                         	- 2.1.16r - map
06:53:52 - INFO   	| map.map_init:34                          	- 2.1.16r - 打开地图
06:53:55 - INFO   	| map.map_init:40                          	- 2.1.16r - 识别点位(625, 986)
06:53:55 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\fanhui_1.png
06:53:56 - INFO   	| map.auto_map:338                         	- 2.1.16r - 检测到星轨航图，不进行点击'返回'
06:53:56 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（1）
06:53:56 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\orientation_1.png
06:53:58 - INFO   	| calculated.click:138                     	- 2.1.16r - 点击坐标(1665, 139)，坐标来源图片匹配度0.999
06:53:58 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（2）
06:53:58 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\orientation_5.png
06:53:59 - INFO   	| calculated.have_screenshot:271           	- 2.1.16r - 找到图片，匹配值：0.988
06:53:59 - INFO   	| calculated.click:138                     	- 2.1.16r - 点击坐标(1374, 400)，坐标来源图片匹配度0.990
06:54:01 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（3）
06:54:01 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\map_4-0.png
06:54:08 - INFO   	| calculated.click:138                     	- 2.1.16r - 点击坐标(1723, 387)，坐标来源图片匹配度0.998
06:54:08 - INFO   	| calculated.click_target:427              	- 2.1.16r - 阴阳变转
06:54:08 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（4）
06:54:08 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\map_4-1_point_0.png
06:54:10 - INFO   	| calculated.click:138                     	- 2.1.16r - 点击坐标(780, 387)，坐标来源图片匹配度0.998
06:54:10 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（5）
06:54:10 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\transfer.png
06:54:11 - INFO   	| calculated.click:138                     	- 2.1.16r - 点击坐标(1655, 970)，坐标来源图片匹配度1.000
06:54:12 - INFO   	| calculated.run_mapload_check:1104        	- 2.1.16r - 检测到地图加载map_load，匹配度0.9999955892562866
06:54:16 - INFO   	| calculated.on_interface:1207             	- 2.1.16r - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 3.9 秒
06:54:16 - INFO   	| calculated.on_interface:1208             	- 2.1.16r - 检测图片序号为0，匹配度0.989，匹配位置为(233, 64)
06:54:16 - INFO   	| calculated.run_mapload_check:1129        	- 2.1.16r - 地图载毕，用时 5.0 秒
06:54:17 - INFO   	| map.auto_map:317                         	- 2.1.16r - 地图加载前的传送点为 picture\map_4-1_point_0.png
06:54:18 - INFO   	| calculated.first_role_check:1240         	- 2.1.16r - 开始判断1号位
06:54:18 - INFO   	| calculated.first_role_check:1255         	- 2.1.16r - 设置1号位为跑图角色
06:54:18 - INFO   	| calculated.auto_map:771                  	- 2.1.16r - 执行map_4-1_0文件:1/3 {'w': 9.5}
06:54:24 - INFO   	| calculated.auto_map:771                  	- 2.1.16r - 执行map_4-1_0文件:2/3 {'f': 2}
06:54:24 - INFO   	| calculated.check_f_img:686               	- 2.1.16r - 扫描'F'图标
06:54:27 - INFO   	| calculated.check_f_img:696               	- 2.1.16r - 扫描'F'：target，匹配度：1.000
06:54:27 - INFO   	| calculated.analyze_found_images:730      	- 2.1.16r - 扫描到 'F'
06:54:27 - INFO   	| calculated.handle_f:836                  	- 2.1.16r - 按下'F'，等待10秒
06:54:37 - INFO   	| calculated.auto_map:771                  	- 2.1.16r - 执行map_4-1_0文件:3/3 {'fighting': 2}
06:54:37 - INFO   	| calculated.click:136                     	- 2.1.16r - 点击坐标(959, 539)
06:54:38 - INFO   	| map.auto_map:392                         	- 2.1.16r - map_4-1_0用时[1;92m『21.0秒』[0m,总计:[1;92m『2小时37分1.6秒』[0m
06:54:38 - INFO   	| log.webhook_and_log:61                   	- 2.1.16r - [0;96;40m艾迪恩代币-2[0m
06:54:38 - INFO   	| map.auto_map:243                         	- 2.1.16r - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_4-1_01
06:54:38 - INFO   	| map.auto_map:249                         	- 2.1.16r - need_allow_map_buy
06:54:38 - INFO   	| map.auto_map:249                         	- 2.1.16r - check
06:54:38 - INFO   	| map.auto_map:258                         	- 2.1.16r - 今天Monday，尝试购买
06:54:38 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\buy.png
06:55:10 - INFO   	| calculated.click_target:433              	- 2.1.16r - 查找图片超时 picture\buy.png ，最相似图片匹配值 0.9015197157859802，所需匹配值 0.93
06:55:10 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（1）
06:55:10 - INFO   	| log.webhook_and_log:61                   	- 2.1.16r - [0;96;40m艾迪恩代币-2[0m
06:55:10 - INFO   	| map.auto_map:243                         	- 2.1.16r - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_4-1_01
06:55:10 - INFO   	| map.auto_map:249                         	- 2.1.16r - need_allow_map_buy
06:55:10 - INFO   	| map.auto_map:249                         	- 2.1.16r - check
06:55:10 - INFO   	| map.auto_map:258                         	- 2.1.16r - 今天Monday，尝试购买
06:55:10 - INFO   	| map.auto_map:249                         	- 2.1.16r - picture\buy.png
06:55:43 - INFO   	| calculated.click_target:433              	- 2.1.16r - 查找图片超时 picture\buy.png ，最相似图片匹配值 0.9015313982963562，所需匹配值 0.93
06:55:43 - INFO   	| map.auto_map:365                         	- 2.1.16r - 传送点击（2）
06:55:43 - INFO   	| log.webhook_and_log:61                   	- 2.1.16r - [0;96;40m筑梦边境-1[0m
06:55:43 - INFO   	| map.auto_map:243                         	- 2.1.16r - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-1_1
06:55:43 - INFO   	| map.auto_map:249                         	- 2.1.16r - map
06:55:43 - INFO   	| map.map_init:34                          	- 2.1.16r - 打开地图
06:55:48 - INFO   	| calculated.on_interface:1216             	- 2.1.16r - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.876
06:55:50 - INFO   	| calculated.on_interface:1216             	- 2.1.16r - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.784
06:55:52 - INFO   	| calculated.on_interface:1216             	- 2.1.16r - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.876
06:55:55 - INFO   	| calculated.on_interface:1216             	- 2.1.16r - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.784
06:55:57 - INFO   	| calculated.on_interface:1216             	- 2.1.16r - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.876

**Comment by cjwjy007** [comment]
应该是个bug，遇到了相同的问题

**Comment by smjes3** [comment]
@vvincee7 你在现实酒店中的艾迪恩代币手动过去是否能够正常购买？

**Comment by vvincee7** [comment]
可以正常购买

**Comment by vvincee7** [comment]
> > 可以正常购买
> 
> 之前有在这里买过吗，第一次在这里买代币是会卡一次的。

  买过的，第一次卡剧情是很早之前了，当时需要先进行一次完整对话才能进商店

**Comment by smjes3** [comment]
> > > 可以正常购买
> > 
> > 
> > 之前有在这里买过吗，第一次在这里买代币是会卡一次的。
> 
> 买过的，第一次卡剧情是很早之前了，当时需要先进行一次完整对话才能进商店

那这个问题另建立一个issue跟进，和这个不是同一问题，他这个是地图问题。

**Comment by smjes3** [comment]
> ### 日志
> [2.1.17日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14905968/2.1.17.log)

#245 修复了该地图向左时间较少造成的路线错误问题。
