### ISSUE TITLE
[功能请求] 建议增加黄泉地图快速路线

### ISSUE THREAD

**Issue by mortal1976** [linruowuyin/Fhoe-Rail#242]
### 原因

现在的地图版本耗时太久

### 功能简述

希望在黄泉地图版本，增加普通全面模式和快速锄地模式设置，快速模式只扫荡距离传送点较近、怪物集中点，现在B战很多up的快速路线人工为10-20分钟，自动模式应该30-40分钟就够了，这样每天完成全面运行（含锄地）时间能大大缩短。

### 功能逻辑

黄泉地图版本，增加快速锄地模式，保留普通全面模式锄地

**Comment by smjes3** [comment]
暂无该计划。

原因：

1. 项目提倡的是完整锄地，以后地图陆续增多也许会开放排除某个星球的功能。
2. 录图测图是一个繁琐的过程，我们暂无更多精力且也无此计划。
3. 你所说的快速模式没有一个定式标准，比如你觉得哪个怪应该纳入，第三人也许觉得这个怪不该纳入快速模式中，没有一个“标准”，扯皮很麻烦。
4. 目前已经支持自定义地图文件夹，如果希望自己定义地图欢迎参与录图并PR。

另外推荐一个也不错的项目。录图相对应该会更友好些也可以考虑。
https://github.com/DoctorReid/StarRailOneDragon
