### ISSUE TITLE
release: 2.026 未成功进入战斗则会卡住

### ISSUE THREAD

**Issue by izumisagirii** [linruowuyin/Fhoe-Rail#25]
release: 2.026 未成功进入战斗则会卡住，回滚变正常
其余配置常规，已参考 #23 #24
2.0地图会有卡住情况，是否方便加入卡住的异常处理，直接abort，输出报错并下一张图

**Comment by linruowuyin** [comment]
出问题的那部分代码回滚了，方便的话提交一下pr，暂时没精力做，未来有空的话可能考虑
