### ISSUE TITLE
[路线错误] 4_4_11和4_4_12

### ISSUE THREAD

**Issue by saiyaku** [linruowuyin/Fhoe-Rail#250]
### 问题描述

> map_4-4_11文件:21/43 {'f': 10}
扫描F获取梦泡充能失败，卡在此处
<img width="971" alt="2" src="https://github.com/linruowuyin/Fhoe-Rail/assets/63626427/8aed78ee-53a0-4d7f-b6f7-33addec88996">

> map_4-4_11文件:35/43 {'r': 3.03}
导致生成梦泡桥梁失败。
<img width="971" alt="3" src="https://github.com/linruowuyin/Fhoe-Rail/assets/63626427/4548b81b-481b-4c40-983f-8c853064b70e">

> 16/43 {'w': 3.82}
疑似在下楼梯后方向走反，后续16-20路线错误。
<img width="971" alt="1" src="https://github.com/linruowuyin/Fhoe-Rail/assets/63626427/3754d702-cc23-41b6-97df-0c6d151df015">

4_4_12和4_4_11前期路线相同，同上。

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14929309/default.log)

**Comment by smjes3** [comment]
请完整完成支线任务：外包工

否则这里面的梦泡摆放是不一样的。
