### ISSUE TITLE
[Bug] 酒店梦境有个漏怪

### ISSUE THREAD

**Issue by vvincee7** [linruowuyin/Fhoe-Rail#251]
### 问题描述

漏怪，但是不清楚是哪一条线路的，这个漏怪不是一直出现，偶尔会出现，已上传截图

### 预期行为

把怪鲨掉

### 实际行为

漏怪

### 截图或录屏

![image](https://github.com/linruowuyin/Fhoe-Rail/assets/161065827/e00b2886-19bf-4911-b0ac-7b6e5768105f)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/161065827/1757ff33-d43c-48df-94db-03705fcd867b)

### 自动锄大地脚本版本

2.1.18

### 日志

不清楚是在哪一段路线的

**Comment by smjes3** [comment]
2.2.05修改了该图，理论上避免了漏这只巡逻怪。
