### ISSUE TITLE
[Bug] 18版本的一些漏怪

### ISSUE THREAD

**Issue by xibaibai9527** [linruowuyin/Fhoe-Rail#252]
### 问题描述

![Honkai  Star Rail Screenshot 2024 04 11 - 21 59 02 07](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/31f4050b-6d40-48d9-84ab-5f44dd7423c7)
![Honkai  Star Rail Screenshot 2024 04 11 - 21 59 20 31](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/0e505ba2-b422-4436-9c52-4a1494c971c6)

这个地方的怪每天都漏，我看了一下，是卡进左面广告牌了，一顿乱劈，实际上根本没砍到

![Honkai  Star Rail Screenshot 2024 04 11 - 22 00 45 06](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/4ba31f34-bd93-46be-a1ac-387b4f58c41c)
![Honkai  Star Rail Screenshot 2024 04 10 - 22 15 39 68](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/6bb0390f-d7ff-4e22-8556-b9326a949683)
![Honkai  Star Rail Screenshot 2024 04 10 - 22 15 42 95](https://github.com/linruowuyin/Fhoe-Rail/assets/19858971/01422125-288c-4ada-9677-fc8d572f0cae)

这里是18版本更新后才漏的，而且是全漏，根本没进来过。17r版本没这个问题

### 预期行为

-

### 实际行为

-

### 自动锄大地脚本版本

2.1.18

### 日志

-

**Comment by xibaibai9527** [comment]
今天有空把这两个地方看了一遍

第一个已经说了，那地方有三只怪，其中一只是卡在广告牌里面的。脚本直接过去把这只怪砍死了，然后在广告牌的凹陷处一直砍，另外两只怪完全没法碰到。

第二个4_4_4，在进门之前有两只怪，一个是镜子在凹造型，一个是巡逻的，角色走过去把镜子砍死，那是个半包的圆圈，角色似乎被卡住，在原地像无头苍蝇一样转圈，这时候巡逻的过来偷袭进战斗。从战斗出来之后，视角就变了，所以后续全部都没了。

**Comment by smjes3** [comment]
每次必漏的话有点问题。。是60帧运行吗？
我这里也是18版本测试下来每次都没漏。。

**Comment by xibaibai9527** [comment]
> 每次必漏的话有点问题。。是60帧运行吗？ 我这里也是18版本测试下来每次都没漏。。

是60帧，配置和注意事项里的推荐配置一模一样

用了差不多一个月，只有两三次没漏过，其余全漏
而具体漏的原因我上面也说了
而且3d房间那个，我杀光所有怪空跑一遍，发现也跑不进去3d房间

**Comment by smjes3** [comment]
尝试改了地图，看下你还是否会出现。
