### ISSUE TITLE
建议增加遇袭进战的监测优先级

### ISSUE THREAD

**Issue by smallmj** [linruowuyin/Fhoe-Rail#253]
目前发现有两种情况遇袭进战会出现问题：
1. 游戏刚启动的时候，进游戏画面如果直接被怪物攻击，会在战斗过程中出现脚本报错，直接退出
2.在角色攻击后的5秒检测时间过后，如果被怪物攻击，游戏中已经进战斗，但是脚本已经在执行下一个阶段的跑图流程，导致直到下一个传送点前的怪物被跳过

建议增加遇袭进战斗的判断优先级，包括刚进入游戏还在选地图或者用march7执行时的选队伍过程中，而且在任何时候进战斗都应该暂停脚本，直到战斗完成后再继续脚本流程

**Comment by smjes3** [comment]
目前方案只能识别到有计划的进入战斗，例如我在这里进行攻击，我预测了这里会进入战斗。会进行一段时间的识别。

且当前没有好的方案支持随时检测进入战斗。

目前方案就是不断优化地图让他不会在‘非计划’的时间内进入战斗。

**Comment by smjes3** [comment]
难点：
1、战斗界面的UI没有一个恒定值能够指示脚本当前正在战斗中，当前识图框架下，战斗界面的所有UI都是每个人不一样的，而右上角的UI识别率又太低。所以没有一种检测方式能够很好的告知脚本“当前在战斗”
2、如果跑动过程中进行遇袭检测，那么要增加异步处理，这块目前改动量太大。
