### ISSUE TITLE
[Bug] 在「白日夢」酒店 - 夢境中會跟小鳥對話導致卡住。

### ISSUE THREAD

**Issue by seriaati** [linruowuyin/Fhoe-Rail#254]
### 问题描述

在「白日夢」酒店 - 夢境中會跟小鳥對話導致卡住。

### 预期行为

應該不點擊 F 跟小鳥互動
或是，跟小鳥互動後應該把對話按完後繼續鋤地

### 实际行为

腳本跟小鳥互動後就停在對話的畫面

### 截图或录屏

![image](https://github.com/linruowuyin/Fhoe-Rail/assets/61446626/395bd722-b066-4cee-90cb-1196c79bb878)

### 自动锄大地脚本版本

2.1.18

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/14954782/default.log)

**Comment by smjes3** [comment]
检查截图左上角的门进入后继续往左走的门是否关闭状态。

**Comment by seriaati** [comment]
是關閉狀態沒錯，我現在按機關把它打開了。
