### ISSUE TITLE
[Bug] 关于凌晨四点检测月卡问题

### ISSUE THREAD

**Issue by VRmaple** [linruowuyin/Fhoe-Rail#255]
### 问题描述

我没在国内，由于处于不同时区，凌晨四点并不是月卡和游戏刷新时间，但由于月卡检测功能，检测完月卡直接判定锄完关机了，建议加个时区检测功能或者是给个设置是否在凌晨检测月卡

### 预期行为

继续锄大地

### 实际行为

关机了

### 自动锄大地脚本版本

2.1.18

### 日志

04:01:30 - INFO   	| calculated.fighting:609                  	- 2.1.18 - 未进入战斗
04:01:31 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-3_4文件:7/18 {'w': 8.696295022964478}
04:01:37 - INFO   	| calculated.auto_map:771                  	- 2.1.18 - 执行map_3-3_4文件:8/18 {'a': 3.1445508003234863}
04:06:22 - INFO   	| fhoe.print_info:100                      	- 2.1.18 - 
04:06:24 - INFO   	| fhoe.print_info:103                      	- 2.1.18 - 

    2024年04月13日 晴
    今天早上我告诉你我想你了，你没理我。今天中午我给你打电话，你不接，打第二个你就关机。晚上我在你公司楼下等你，你对我说的第一句话就是滚&quot;滚，别烦我，别浪费时间了&quot;，我真的好感动，你居然为我考虑了，怕我浪费时间。呜呜呜，这是我爱你的第74天。

04:06:24 - INFO   	| fhoe.print_info:104                      	- 2.1.18 - 
04:06:24 - INFO   	| fhoe.print_info:105                      	- 2.1.18 - ============================================================
04:06:24 - INFO   	| fhoe.print_info:106                      	- 2.1.18 - 开始运行
04:06:24 - INFO   	| fhoe.print_version:91                    	- 2.1.18 - 当前版本：2.1.18
04:06:24 - INFO   	| fhoe.print_version:92                    	- 2.1.18 - config.json
04:06:35 - INFO   	| fhoe.choose_map_debug:51                 	- 2.1.18 - 设置完成

**Comment by smjes3** [comment]
检测月卡并不会导致关机。导致关机看下是否是别的原因造成的，晚点会增加一个设置可以自行设置月卡刷新的“小时”与“分钟”，根据自己的实际时区设置。

**Comment by smjes3** [comment]
月卡检测是一个单独的模块，只影响接近月卡刷新时间时对锄地行为进行暂停，领取月卡后会继续进行，不涉及到结束锄地或者关机的逻辑。

**Comment by VRmaple** [comment]
> 月卡检测是一个单独的模块，只影响接近月卡刷新时间时对锄地行为进行暂停，领取月卡后会继续进行，不涉及到结束锄地或者关机的逻辑。

麻烦啦，我估计有可能是和三月七自动关机冲突了，我到时候试试看软件本身的自动关机会不会出现问题

**Comment by smjes3** [comment]
更新2.1.19，在设置中对月卡时间进行设置
