### ISSUE TITLE
[Bug] 黄泉跑图卡在惊梦酒吧的小鸟这里

### ISSUE THREAD

**Issue by SamuelWangCode** [linruowuyin/Fhoe-Rail#259]
### 问题描述

反复执行过多次，每次都会卡在惊梦酒吧这里，不知道为什么会在这里旁听，然后无法执行下去。
开启了购买道具和零食，但是还没有刷完图

### 预期行为

不应该进入旁听状态

### 实际行为

卡在旁听小鸟对话这里

### 截图或录屏

![image](https://github.com/linruowuyin/Fhoe-Rail/assets/38282063/315dc425-eec2-4d9e-9843-5e6cce53e9aa)

### 自动锄大地脚本版本

2.1.18

### 日志

[日志文件.2024-04-16_16-40-55_690000.log](https://github.com/linruowuyin/Fhoe-Rail/files/15011773/2024-04-16_16-40-55_690000.log)

**Comment by yanshiqwq** [comment]
![Screenshot_2024-04-18-01-27-10-117_com fsck k9](https://github.com/linruowuyin/Fhoe-Rail/assets/56720055/60a7d4ad-ee20-49e6-98c2-e3673b33ac11)
我也遇到了类似的

**Comment by akuan1997** [comment]
我也 
這情況持續好多天了

**Comment by yanshiqwq** [comment]
对比了一下我的两个号，小号没做完惊梦酒吧调酒活动大号做完了，可能和这个有关（？

**Comment by smjes3** [comment]
#254 
重复问题。
