### ISSUE TITLE
[Bug] 低帧率下选大地图星球的时候会失灵

### ISSUE THREAD

**Issue by Canda15** [linruowuyin/Fhoe-Rail#261]
### 问题描述

并不是脚本的问题。是崩铁本身在低于30帧下就会时不时出现选大地图失灵。就是指点这个地球，也有反应，但是不会进去。
希望能在每次 切到这个选星球的界面，能够给一点延迟等待加载。并且把 “点星球”改为 点“星球下面的名字”，如果是点星球下面的名字在低帧率下就没有见过失灵。

这个问题 是我在核显小主机上发现的。后续在本地有独显的主力机上限制帧率到10-15fps后复现了。
![图片](https://github.com/linruowuyin/Fhoe-Rail/assets/124772373/8792f9d2-ddf0-4700-92f9-1580c1aacf39)

### 预期行为

如上

### 实际行为

如上

### 自动锄大地脚本版本

2.1.19

### 日志

如上

**Comment by Canda15** [comment]
![图片](https://github.com/linruowuyin/Fhoe-Rail/assets/124772373/c6761d80-4311-4157-b92a-b451479d42bf)
点这个位置就没有问题

**Comment by ddd-zero** [comment]
我改了一下。测试几天看看

**Comment by ddd-zero** [comment]
测试了10-15fps下很多地方锄大地跑不到指定位置。感觉没必要更到正式版。你把那4个地球的png识别文件自己截图替换成下面的文字就行。

**Comment by smjes3** [comment]
低帧率会引起非常多问题，包括行走疾跑都有可能进错位置，这里只能建议你尝试更换更高帧率的机器进行。
