### ISSUE TITLE
[Bug] 合成奇巧零食失败：购买合成材料后，没有退出购买界面

### ISSUE THREAD

**Issue by yingxr** [linruowuyin/Fhoe-Rail#265]
### 问题描述

使用simple remote远程控制本地的第二个账户，使用三月七，本机分辨率2560*1440，远程分辨率1920*1080，游戏分辨率1920*1080全屏。

从游戏画面来看：

> 在仙舟购买奇巧零食的合成材料，即map_3_0_1；购买完成后，发生问题。

### 预期行为

map_3_0_1：识别到购买完成或购买量已达上限，退出购买界面。
继续执行map_3_0_2，合成奇巧零食100个。

### 实际行为

map_3_0_1：当购买成功时，看日志是退出了购买界面；
重复测试时，购买量达到上限，游戏画面显示，没有退出购买界面，日志中缺少esc操作，参考5月6日的两次log。
继续执行map_3_0_2，游戏画面没有进入背包-消耗品-奇巧零食-合成台，**没有合成奇巧零食**。
log提示奇巧零食图片识别失败。`查找图片超时 picture\qiqiao.png ，最相似图片匹配值 0.9283488392829895，所需匹配值 0.93`

补充：

> 在购买完成后，处于购买界面时，手动点击esc返回大地图，成功执行map_3_0_2，合成了奇巧零食。

### 自动锄大地脚本版本

2.1.20

### 日志

[日志文件.2024-05-05_04-09-44_055605.log](https://github.com/linruowuyin/Fhoe-Rail/files/15215388/2024-05-05_04-09-44_055605.log)
[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/15215392/default.log)

5月5日周日的log：

> 06:57:46 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_1
06:57:46 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
06:57:46 - INFO   	| map.auto_map:289                         	- 04290128 - picture\buy.png
06:57:47 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1328, 594)，坐标来源图片匹配度0.981
06:57:48 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
06:57:48 - INFO   	| map.auto_map:289                         	- 04290128 - await
06:57:50 - INFO   	| map.auto_map:289                         	- 04290128 - space
06:57:50 - INFO   	| map.auto_map:289                         	- 04290128 - await
06:57:54 - INFO   	| map.auto_map:289                         	- 04290128 - picture\liuti.png
06:57:55 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(911, 251)，坐标来源图片匹配度1.000
06:57:56 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
06:57:56 - INFO   	| map.auto_map:289                         	- 04290128 - picture\max.png
06:58:01 - INFO   	| calculated.on_interface:1260             	- 04290128 - 在 5 秒 的时间内未检测到无法购买，相似图片最高匹配值0.930
06:58:01 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1448, 634)，坐标来源图片匹配度1.000
06:58:01 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
06:58:03 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1139, 742)，坐标来源图片匹配度1.000
06:58:03 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（3）
06:58:03 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
06:58:05 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(963, 126)，坐标来源图片匹配度0.999
06:58:05 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（4）
06:58:05 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zhongzi.png
06:58:06 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(914, 252)，坐标来源图片匹配度0.999
06:58:07 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（5）
06:58:07 - INFO   	| map.auto_map:289                         	- 04290128 - picture\max.png
06:58:12 - INFO   	| calculated.on_interface:1260             	- 04290128 - 在 5 秒 的时间内未检测到无法购买，相似图片最高匹配值0.929
06:58:12 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1448, 634)，坐标来源图片匹配度1.000
06:58:12 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
06:58:14 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1139, 742)，坐标来源图片匹配度1.000
06:58:14 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（6）
06:58:14 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
06:58:16 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(963, 126)，坐标来源图片匹配度0.999
06:58:16 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（7）
06:58:16 - INFO   	| calculated.first_role_check:1284         	- 04290128 - 开始判断1号位
06:58:16 - INFO   	| calculated.auto_map:775                  	- 04290128 - 执行map_3-0_1文件:1/2 {'esc': 1}
06:58:19 - INFO   	| calculated.auto_map:775                  	- 04290128 - 执行map_3-0_1文件:2/2 {'fighting': 2}
06:58:19 - INFO   	| calculated.click:140                     	- 04290128 - 点击坐标(963, 126)
06:58:20 - INFO   	| map.auto_map:435                         	- 04290128 - map_3-0_1用时[1;92m『4.6秒』[0m,总计:[1;92m『2小时19分27.2秒』[0m
06:58:20 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
06:58:20 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
06:58:20 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
06:58:20 - INFO   	| map.auto_map:289                         	- 04290128 - b
06:58:21 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
06:58:28 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1187, 434)，坐标来源图片匹配度0.957
06:58:29 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
06:58:29 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
06:58:29 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
06:58:30 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(365, 393)，坐标来源图片匹配度0.932
06:58:30 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
06:58:30 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hechengji.png
06:58:37 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(888, 862)，坐标来源图片匹配度0.934
06:58:37 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
06:58:37 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（3）
06:58:37 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zengjia.png
06:58:39 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1321, 696)，坐标来源图片匹配度0.933
06:58:39 - INFO   	| calculated.click:144                     	- 04290128 - 将点击 100 次
06:58:55 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（4）
06:58:55 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hecheng.png
06:58:57 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(810, 402)，坐标来源图片匹配度0.951
06:58:57 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（5）
06:58:57 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
06:58:58 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(721, 742)，坐标来源图片匹配度0.959
06:58:59 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（6）
06:58:59 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
06:59:30 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\finish_fighting4.png ，最相似图片匹配值 0.9180865287780762，所需匹配值 0.93
06:59:30 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（7）
06:59:30 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
06:59:30 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
06:59:30 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
06:59:30 - INFO   	| map.auto_map:289                         	- 04290128 - b
06:59:31 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
06:59:38 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(867, 857)，坐标来源图片匹配度0.952
06:59:39 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
06:59:39 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（8）
06:59:39 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
07:00:10 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\qiqiao.png ，最相似图片匹配值 0.9282864928245544，所需匹配值 0.93
07:00:10 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（9）
07:00:10 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m过期邮包-1[0m
07:00:10 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_3

5月6日周一的log第一次：

> 09:31:05 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_1
09:31:05 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:31:05 - INFO   	| map.auto_map:289                         	- 04290128 - picture\buy.png
09:31:07 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1328, 594)，坐标来源图片匹配度0.981
09:31:07 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
09:31:07 - INFO   	| map.auto_map:289                         	- 04290128 - await
09:31:09 - INFO   	| map.auto_map:289                         	- 04290128 - space
09:31:09 - INFO   	| map.auto_map:289                         	- 04290128 - await
09:31:13 - INFO   	| map.auto_map:289                         	- 04290128 - picture\liuti.png
09:31:15 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(911, 251)，坐标来源图片匹配度1.000
09:31:15 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
09:31:15 - INFO   	| map.auto_map:289                         	- 04290128 - picture\max.png
09:31:20 - INFO   	| calculated.on_interface:1260             	- 04290128 - 在 5 秒 的时间内未检测到无法购买，相似图片最高匹配值0.926
09:31:20 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1448, 634)，坐标来源图片匹配度1.000
09:31:20 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
09:31:22 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1139, 742)，坐标来源图片匹配度1.000
09:31:22 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（3）
09:31:22 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
09:31:24 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(963, 126)，坐标来源图片匹配度0.999
09:31:24 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（4）
09:31:24 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zhongzi.png
09:31:26 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(914, 252)，坐标来源图片匹配度0.999
09:31:26 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（5）
09:31:26 - INFO   	| map.auto_map:289                         	- 04290128 - picture\max.png
09:31:31 - INFO   	| calculated.on_interface:1260             	- 04290128 - 在 5 秒 的时间内未检测到无法购买，相似图片最高匹配值0.926
09:31:31 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1448, 634)，坐标来源图片匹配度1.000
09:31:31 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
09:31:33 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1139, 742)，坐标来源图片匹配度1.000
09:31:33 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（6）
09:31:33 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
09:31:35 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(963, 126)，坐标来源图片匹配度0.999
09:31:35 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（7）
09:31:35 - INFO   	| calculated.first_role_check:1284         	- 04290128 - 开始判断1号位
09:31:35 - INFO   	| calculated.auto_map:775                  	- 04290128 - 执行map_3-0_1文件:1/2 {'esc': 1}
09:31:38 - INFO   	| calculated.auto_map:775                  	- 04290128 - 执行map_3-0_1文件:2/2 {'fighting': 2}
09:31:38 - INFO   	| calculated.click:140                     	- 04290128 - 点击坐标(963, 126)
09:31:39 - INFO   	| map.auto_map:435                         	- 04290128 - map_3-0_1用时[1;92m『4.6秒』[0m,总计:[1;92m『34.7秒』[0m
09:31:39 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
09:31:39 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
09:31:39 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:31:39 - INFO   	| map.auto_map:289                         	- 04290128 - b
09:31:40 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
09:31:47 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1187, 434)，坐标来源图片匹配度0.957
09:31:48 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:31:48 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
09:31:48 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
09:31:49 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(365, 393)，坐标来源图片匹配度0.932
09:31:49 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
09:31:50 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hechengji.png
09:31:56 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(888, 862)，坐标来源图片匹配度0.934
09:31:56 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:31:56 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（3）
09:31:56 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zengjia.png
09:31:58 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1321, 696)，坐标来源图片匹配度0.933
09:31:58 - INFO   	| calculated.click:144                     	- 04290128 - 将点击 100 次
09:32:14 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（4）
09:32:14 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hecheng.png
09:32:16 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(810, 402)，坐标来源图片匹配度0.951
09:32:16 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（5）
09:32:16 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
09:32:18 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(721, 742)，坐标来源图片匹配度0.959
09:32:18 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（6）
09:32:18 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
09:32:50 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\finish_fighting4.png ，最相似图片匹配值 0.918086588382721，所需匹配值 0.93
09:32:50 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（7）
09:32:50 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
09:32:50 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
09:32:50 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:32:50 - INFO   	| map.auto_map:289                         	- 04290128 - b
09:32:51 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
09:32:58 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(867, 857)，坐标来源图片匹配度0.952
09:32:58 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:32:58 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（8）
09:32:58 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
09:33:30 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\qiqiao.png ，最相似图片匹配值 0.9284244179725647，所需匹配值 0.93
09:33:30 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（9）
09:33:30 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m过期邮包-1[0m
09:33:30 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_3

5月6日周一的log第二次：

> 09:42:47 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_1
09:42:47 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:42:47 - INFO   	| map.auto_map:289                         	- 04290128 - picture\buy.png
09:42:49 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1328, 594)，坐标来源图片匹配度0.981
09:42:49 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
09:42:49 - INFO   	| map.auto_map:289                         	- 04290128 - await
09:42:51 - INFO   	| map.auto_map:289                         	- 04290128 - space
09:42:51 - INFO   	| map.auto_map:289                         	- 04290128 - await
09:42:55 - INFO   	| map.auto_map:289                         	- 04290128 - picture\liuti.png
09:42:57 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1151, 570)，坐标来源图片匹配度0.999
09:42:57 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
09:42:57 - INFO   	| map.auto_map:289                         	- 04290128 - picture\max.png
09:42:57 - INFO   	| calculated.on_interface:1251             	- 04290128 - 检测到无法购买，耗时 0.7 秒
09:42:57 - INFO   	| calculated.on_interface:1252             	- 04290128 - 检测图片序号为0，匹配度1.000，匹配位置为(1106, 721)
09:42:57 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
09:42:57 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
09:42:57 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:42:57 - INFO   	| map.auto_map:289                         	- 04290128 - b
09:42:59 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
09:43:06 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1055, 464)，坐标来源图片匹配度0.956
09:43:06 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:43:06 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
09:43:06 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
09:43:08 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(365, 393)，坐标来源图片匹配度0.932
09:43:08 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
09:43:08 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hechengji.png
09:43:15 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(882, 868)，坐标来源图片匹配度0.934
09:43:15 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:43:15 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（3）
09:43:15 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zengjia.png
09:43:16 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1321, 696)，坐标来源图片匹配度0.933
09:43:16 - INFO   	| calculated.click:144                     	- 04290128 - 将点击 100 次
09:43:33 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（4）
09:43:33 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hecheng.png
09:43:34 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(810, 402)，坐标来源图片匹配度0.951
09:43:34 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（5）
09:43:34 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
09:43:36 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(721, 742)，坐标来源图片匹配度0.959
09:43:36 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（6）
09:43:36 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
09:44:08 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\finish_fighting4.png ，最相似图片匹配值 0.9180865287780762，所需匹配值 0.93
09:44:08 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（7）
09:44:08 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
09:44:08 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
09:44:08 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:44:08 - INFO   	| map.auto_map:289                         	- 04290128 - b
09:44:09 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
09:44:16 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(860, 856)，坐标来源图片匹配度0.952
09:44:16 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:44:16 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（8）
09:44:16 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
09:44:48 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\qiqiao.png ，最相似图片匹配值 0.9283488392829895，所需匹配值 0.93
09:44:48 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（9）
09:44:48 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m过期邮包-1[0m
09:44:48 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_3

5月6日周一的log第三次：

> 09:53:47 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_1
09:53:47 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:53:47 - INFO   	| map.auto_map:289                         	- 04290128 - picture\buy.png
09:53:49 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1328, 594)，坐标来源图片匹配度0.981
09:53:49 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
09:53:49 - INFO   	| map.auto_map:289                         	- 04290128 - await
09:53:51 - INFO   	| map.auto_map:289                         	- 04290128 - space
09:53:51 - INFO   	| map.auto_map:289                         	- 04290128 - await
09:53:55 - INFO   	| map.auto_map:289                         	- 04290128 - picture\liuti.png
09:53:57 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1151, 570)，坐标来源图片匹配度0.999
09:53:57 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
09:53:57 - INFO   	| map.auto_map:289                         	- 04290128 - picture\max.png
09:53:58 - INFO   	| calculated.on_interface:1251             	- 04290128 - 检测到无法购买，耗时 0.8 秒
09:53:58 - INFO   	| calculated.on_interface:1252             	- 04290128 - 检测图片序号为0，匹配度1.000，匹配位置为(1106, 721)
09:53:58 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
09:53:58 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
09:53:58 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:53:58 - INFO   	| map.auto_map:289                         	- 04290128 - b
09:53:59 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
09:54:06 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1055, 464)，坐标来源图片匹配度0.956
09:54:06 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:54:06 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（1）
09:54:06 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
09:54:08 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1699, 386)，坐标来源图片匹配度0.930
09:54:08 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（2）
09:54:08 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hechengji.png
09:54:15 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(888, 862)，坐标来源图片匹配度0.934
09:54:15 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:54:15 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（3）
09:54:15 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zengjia.png
09:54:16 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1321, 696)，坐标来源图片匹配度0.933
09:54:16 - INFO   	| calculated.click:144                     	- 04290128 - 将点击 100 次
09:54:32 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（4）
09:54:32 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hecheng.png
09:54:34 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(810, 402)，坐标来源图片匹配度0.951
09:54:34 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（5）
09:54:34 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
09:54:36 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(721, 742)，坐标来源图片匹配度0.959
09:54:36 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（6）
09:54:36 - INFO   	| map.auto_map:289                         	- 04290128 - picture\finish_fighting4.png
09:55:08 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\finish_fighting4.png ，最相似图片匹配值 0.9180865287780762，所需匹配值 0.93
09:55:08 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（7）
09:55:08 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m零食合成-1[0m
09:55:08 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_2
09:55:08 - INFO   	| map.auto_map:289                         	- 04290128 - need_allow_snack_buy
09:55:08 - INFO   	| map.auto_map:289                         	- 04290128 - b
09:55:09 - INFO   	| map.auto_map:289                         	- 04290128 - picture\xiaohaoping.png
09:55:16 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(867, 857)，坐标来源图片匹配度0.952
09:55:16 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:55:16 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（8）
09:55:16 - INFO   	| map.auto_map:289                         	- 04290128 - picture\qiqiao.png
09:55:23 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(457, 559)，坐标来源图片匹配度0.935
09:55:23 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（9）
09:55:23 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hechengji.png
09:55:34 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1596, 525)，坐标来源图片匹配度0.941
09:55:34 - INFO   	| calculated.click_target:431              	- 04290128 - 阴阳变转
09:55:34 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（10）
09:55:34 - INFO   	| map.auto_map:289                         	- 04290128 - picture\zengjia.png
09:55:36 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(1135, 167)，坐标来源图片匹配度0.937
09:55:36 - INFO   	| calculated.click:144                     	- 04290128 - 将点击 100 次
09:55:52 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（11）
09:55:52 - INFO   	| map.auto_map:289                         	- 04290128 - picture\hecheng.png
09:55:53 - INFO   	| calculated.click:142                     	- 04290128 - 点击坐标(273, 1008)，坐标来源图片匹配度0.936
09:55:54 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（12）
09:55:54 - INFO   	| map.auto_map:289                         	- 04290128 - picture\round.png
09:56:25 - INFO   	| calculated.click_target:437              	- 04290128 - 查找图片超时 picture\round.png ，最相似图片匹配值 0.8416386842727661，所需匹配值 0.93
09:56:25 - INFO   	| map.auto_map:408                         	- 04290128 - 传送点击（13）
09:56:25 - INFO   	| log.webhook_and_log:61                   	- 04290128 - [0;96;40m过期邮包-1[0m
09:56:25 - INFO   	| map.auto_map:283                         	- 04290128 - 路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献，准备开始路线：map_3-0_3

**Comment by smjes3** [comment]
修复后的行为：

无论购买成功或失败，均会在按B打开背包前，不断ESC直到回到主界面
