### ISSUE TITLE
[路线错误] 朝露公馆路线错误

### ISSUE THREAD

**Issue by dConstantineb** [linruowuyin/Fhoe-Rail#268]
### 问题描述

朝露公馆第一个点位少了张图吧，我就说为什么有时候会乱滑动地图
![QQ图片20240509151058](https://github.com/linruowuyin/Fhoe-Rail/assets/87115639/86d26c79-b437-4f70-a288-8e36b9f28d3b)

### 日志

[Uploading 日志文件.log…]()

**Comment by dConstantineb** [comment]
还有地图261最后那个冰怪有概率因为旁边的罐子漏掉，建议加个"fighting": 2

**Comment by smjes3** [comment]
@dConstantineb 日志文件没有上传成功？用的版本是2.1.01吗，理论上这个修复了

261的没看懂，261那个文件就只有一个操作就是打罐子，你说的冰怪在哪里。
