### ISSUE TITLE
白日梦酒店地图传送失败

### ISSUE THREAD

**Issue by Tom-xia** [linruowuyin/Fhoe-Rail#27]
在完成白日梦5之后，角色所在位置拖住了地图，导致无法显示4-3_point_1梦境大堂传送点，导致传送失败。
白日梦6完成之后也有同样的问题。
红框处：手动选中梦境大堂后脚本继续运行
![BQYZ@)5%LL0V7$}CQX$LB`6](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/443e98a8-5eea-46ff-9c74-d48f9dcba64d)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/efb06caa-37da-4a50-a99a-3d1c27f440b2)
![YW@DRWK74NU(69U(KGLN5@2](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/0e14ff2d-f0ee-4c85-bebb-f59cd9034650)
![X E{$A%36U5L67HGZ240EEC](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/c24ba14c-ba31-4efe-8d4c-c8faabdf1e58)

**Comment by BROWNBRONY** [comment]
补充：白日梦9和10中间多了一个白日梦1；
白日梦3并不会传送而是卡主在地图页面

**Comment by Tom-xia** [comment]
补充，已更新到.28版本，但是似乎地图乱了QAQ 
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/62affc59-be01-448f-bef8-1183f6755baf)

**Comment by 0frostmourne0** [comment]
这是我自己改的地图，有空可以测试一下：
[map.zip](https://github.com/linruowuyin/Fhoe-Rail/files/14229481/map.zip)

按照目前的路线，4-3_07是没用的，05和06中间距离太远，需要右边的副本“中继”一下。
我把06和07互换了一下，改了点参数，目前测试正常。
此外大堂那个电梯用默认参数我这边是点不到的，所以我修改了4-3_01和4-3_07的参数，使其可以点到电梯。

**Comment by Tom-xia** [comment]
感谢分享，上述问题得到解决。但是经测试，梦境7与8的地图传送出现问题
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/857ad485-c25c-49ad-b130-3ac56aa68922)
如图所示，07完成后角色还处于3D地图，但脚本误认为在大地图，少点一次右上角的返回，导致传送到魔花锚点失败。我不知道在哪里加这个返回一次的参数，烦请指教

**Comment by 0frostmourne0** [comment]
我先改的8忘发了
[map_4-3_08.json](https://github.com/linruowuyin/Fhoe-Rail/files/14229718/map_4-3_08.json)
多检测一次`{
            "picture\\map_4-2_point_3.png": 1.5
        },`就行了

**Comment by linruowuyin** [comment]
问题简单修了下，明天喵喵应该还会更地图，感谢反馈
