### ISSUE TITLE
[路线错误] map_4-5_point_3 map_4-5_point_4

### ISSUE THREAD

**Issue by NeetMochi** [linruowuyin/Fhoe-Rail#271]
### 问题描述

克劳克影视乐园， 仓鼠球乐园点位因为活动新加了个图标导致传送识别有问题
![QQ截图20240510120426](https://github.com/linruowuyin/Fhoe-Rail/assets/96508493/1966ffe8-1943-4c0f-baa5-357b73e0adb1)

### 日志

06:20:17 - INFO   	| map.map_init:37                          	- 2.2.03 - 打开地图
06:20:20 - INFO   	| map.map_init:49                          	- 2.2.03 - 识别点位(625, 986)
06:20:20 - INFO   	| map.auto_map:289                         	- 2.2.03 - picture\map_4-5_point_4.png
06:20:21 - INFO   	| map.find_transfer_point:183              	- 2.2.03 - 开始移动地图，向下移动，当前所需匹配值0.975
06:20:26 - INFO   	| map.find_transfer_point:183              	- 2.2.03 - 开始移动地图，向左移动，当前所需匹配值0.975
06:20:32 - INFO   	| map.find_transfer_point:183              	- 2.2.03 - 开始移动地图，向上移动，当前所需匹配值0.975
06:20:35 - INFO   	| calculated.have_screenshot:275           	- 2.2.03 - 找到图片，匹配值：0.978
06:20:36 - INFO   	| calculated.click:142                     	- 2.2.03 - 点击坐标(863, 615)，坐标来源图片匹配度0.978
06:20:36 - INFO   	| map.auto_map:408                         	- 2.2.03 - 传送点击（1）
06:20:36 - INFO   	| map.auto_map:289                         	- 2.2.03 - picture\transfer.png
06:21:06 - INFO   	| calculated.click_target:437              	- 2.2.03 - 查找图片超时 picture\transfer.png ，最相似图片匹配值 0.8945740461349487，所需匹配值 0.93
06:21:06 - INFO   	| log.webhook_and_log:61                   	- 2.2.03 - [0;96;40m影视乐园-9[0m
06:21:06 - INFO   	| map.auto_map:283                         	- 2.2.03 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-5_9
06:21:06 - INFO   	| map.auto_map:289                         	- 2.2.03 - map
06:21:06 - INFO   	| map.map_init:37                          	- 2.2.03 - 打开地图
06:21:10 - INFO   	| calculated.on_interface:1275             	- 2.2.03 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
06:21:10 - INFO   	| calculated.on_interface:1276             	- 2.2.03 - 检测图片序号为0，匹配度0.993，匹配位置为(233, 64)
06:21:10 - INFO   	| map.map_init:37                          	- 2.2.03 - 打开地图
06:21:13 - INFO   	| map.map_init:49                          	- 2.2.03 - 识别点位(625, 986)
06:21:13 - INFO   	| map.auto_map:289                         	- 2.2.03 - picture\map_4-5_point_4.png
06:21:45 - INFO   	| calculated.click_target:437              	- 2.2.03 - 查找图片超时 picture\map_4-5_point_4.png ，最相似图片匹配值 0.9274783134460449，所需匹配值 0.93
06:21:45 - INFO   	| map.auto_map:408                         	- 2.2.03 - 传送点击（1）
06:21:45 - INFO   	| log.webhook_and_log:61                   	- 2.2.03 - [0;96;40m影视乐园-9[0m
06:21:45 - INFO   	| map.auto_map:283                         	- 2.2.03 - 路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献，准备开始路线：map_4-5_9
06:21:45 - INFO   	| map.auto_map:289                         	- 2.2.03 - map
06:21:45 - INFO   	| map.map_init:37                          	- 2.2.03 - 打开地图
06:21:49 - INFO   	| calculated.on_interface:1275             	- 2.2.03 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.0 秒
06:21:49 - INFO   	| calculated.on_interface:1276             	- 2.2.03 - 检测图片序号为0，匹配度0.996，匹配位置为(233, 64)
06:21:49 - INFO   	| map.map_init:37                          	- 2.2.03 - 打开地图
06:21:52 - INFO   	| map.map_init:49                          	- 2.2.03 - 识别点位(625, 986)
06:21:52 - INFO   	| map.auto_map:289                         	- 2.2.03 - picture\map_4-5_point_4.png
06:22:24 - INFO   	| calculated.click_target:437              	- 2.2.03 - 查找图片超时 picture\map_4-5_point_4.png ，最相似图片匹配值 0.9274783134460449，所需匹配值 0.93
06:22:24 - INFO   	| map.auto_map:408                         	- 2.2.03 - 传送点击（2）

**Comment by NeetMochi** [comment]
![QQ截图20240510121308](https://github.com/linruowuyin/Fhoe-Rail/assets/96508493/2649ac3c-a3a4-4be4-a1e5-1bef29dbae47)  刚看了下4-5_3也多了个二级

**Comment by smjes3** [comment]
修复
