### ISSUE TITLE
在梦境酒店经常出现退到大地图然后滑动地图找图标的情况

### ISSUE THREAD

**Issue by dConstantineb** [linruowuyin/Fhoe-Rail#285]
### 问题描述

在梦境酒店经常出现退到大地图然后滑动地图找图标的情况

### 预期行为

打开地图找锚点

### 实际行为

打开地图退到大地图再找锚点，找个der

### 自动锄大地脚本版本

2.1.12

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/15345119/default.log)

**Comment by smjes3** [comment]
日志提示有多个识图与实际图片不匹配，有可能是本机图片未更新为最新造成的，建议完全删除三月七中的Fhoe文件夹后再更新尝试。

**Comment by smjes3** [comment]
20:28:10 - map.auto_map:331 - 2.2.10 - picture\map_4-3_point_1.png
20:28:11 - calculated.have_screenshot:290 - 2.2.10 - 找到图片，匹配值：0.997
20:28:11 - calculated.click:149 - 2.2.10 - 点击坐标(1059, 688)，坐标来源图片匹配度0.997

举个例子，这个是正常识别picture\map_4-3_point_1.png的匹配值，应该都要在至少0.99以上，而你提供的日志有多个类似应该是高匹配值的图片是0.98以下的匹配值，属于严重图片匹配不正常。

有问题先更新版本，看新版本是否解决。看了下2.1.12都是一个半月之前的了，很多BUG都是期间修复的。
