### ISSUE TITLE
黄泉 白日梦酒店-梦境漏怪

### ISSUE THREAD

**Issue by jelly0925** [linruowuyin/Fhoe-Rail#287]
### 问题描述

这个区域每天都会遗漏

### 预期行为

跑图优化

### 实际行为

跑图经常卡角落

### 截图或录屏

![白日梦酒店-梦境漏怪01](https://github.com/linruowuyin/Fhoe-Rail/assets/3022023/9b80fa88-9f0c-44ba-bcb8-14431a106c5b)

### 自动锄大地脚本版本

2.2.10

### 日志

[2.2.10日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/15351224/2.2.10.log)

**Comment by smjes3** [comment]
将在2.2.11版本尝试修复
