### ISSUE TITLE
[Bug] 这几天次次在罗浮出现地图崩溃，昨天更新到2.2.1，然而还是没用

### ISSUE THREAD

**Issue by dConstantineb** [linruowuyin/Fhoe-Rail#292]
### 问题描述

这几天次次在罗浮出现地图崩溃，昨天更新到2.2.1，然而还是没用

### 预期行为

锄大地

### 实际行为

识别失败

### 截图或录屏

![图片](https://github.com/linruowuyin/Fhoe-Rail/assets/87115639/d381496a-baa0-42cc-924e-c89e528bc823)

### 自动锄大地脚本版本

2.2.1

### 日志

[日志文件.log](https://github.com/linruowuyin/Fhoe-Rail/files/15373212/default.log)

**Comment by smjes3** [comment]
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/33685788/42232f60-78f5-473a-8773-8b1b9951ceda)

这个是三月七设置中的超时时间过短，三月七强制结束了锄地脚本。

在三月七设置-锄大地-锄大地超时中，设置正确的超时时间。

**Comment by dConstantineb** [comment]
> ![image](https://private-user-images.githubusercontent.com/33685788/332002071-42232f60-78f5-473a-8773-8b1b9951ceda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTUyNzEsIm5iZiI6MTcxNjE5NDk3MSwicGF0aCI6Ii8zMzY4NTc4OC8zMzIwMDIwNzEtNDIyMzJmNjAtNzhmNS00NzNhLTg3NzMtOGIxYjk5NTFjZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA4NDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMTUyZmQwMDI2ODRiMGIzNDY2MzFhZmEwZDdmM2U2NWExNjdjMmMzN2QwOTM5MTk1NGMzNGMyYWEzMzZjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tGaUbkVPDfo0NQKsrVd7U_cCz3F_1rj_Mx2VKanA6CU)
> 
> 这个是三月七设置中的超时时间过短，三月七强制结束了锄地脚本。
> 
> 在三月七设置-锄大地-锄大地超时中，设置正确的超时时间。

那要多少？我三月七之前都用得好好的，没升过级

**Comment by smjes3** [comment]
看你日志是设置的一小时，这个根据你自己锄大地的练度决定的，一般不低于6小时比较好。你可以先设置8小时看下锄大地每次消耗多少时间，然后再进行缩小。

**Comment by smjes3** [comment]
你日志显示是12点20分开始锄大地，13点20分超时结束，为什么超时时间会是一小时我也不知道，这个要问三月七那里的作者。
三月七一旦超过超时时间会强制结束锄地脚本。
