### ISSUE TITLE
匹诺康尼-酒店-两个问题及解决方案

### ISSUE THREAD

**Issue by mainytht** [linruowuyin/Fhoe-Rail#30]
1  酒店-梦境中切换地图会 切换到 酒店-现实 可能是由于前面文字太多，把“白日梦酒店-梦境”小图片   换成“”酒店-梦境”能解决
2 前面按电梯的时候路线稍偏了一点，会划过柱子导致无法按上电梯。

**Comment by linruowuyin** [comment]
已采纳，感谢反馈
