### ISSUE TITLE
锄大地时，希望能在执行多次地图识别失败后退回星轨航图重新打开地图

### ISSUE THREAD

**Issue by lujie2464** [linruowuyin/Fhoe-Rail#310]
### 原因

黄泉专用锄大地时，经常不知道什么原因打开了错误的星球地图，导致地图图片识别错误。
事例：尤其是从“机械聚落”到“零食购买”，第一次运行锄大地时，结束了雅利洛六号“机械聚落”的锄大地之后，我有70%概率卡在雅利洛六号的地图上（疑似是因为在机械聚落-4中，黄泉跟小怪进入了战斗导致的，在小怪死后重新进行锄大地就不会卡住了）。之后会在雅利洛六号“机械聚落”的地图上进行所有"仙舟"地图的识别。从日志里看，会一直执行图片识别失败，移动地图的操作，但是不会退出“雅利洛六号”的地图重新打开“仙舟”地图。直到跳过了整个仙舟地图的锄大地，才会退出当前地图，打开“匹诺康尼“的地图。

### 功能简述

执行多次地图识别失败后退回星轨航图重新打开地图，再执行地图识别

### 功能逻辑

多次地图识别图片匹配失败，就执行一次退回星轨航图重新打开地图，再重新进行地图识别。如果仍然识别失败，再跳过当前地图。

**Comment by smjes3** [comment]
跳过整个仙舟是因为2.2.21的一个代码错误。稍后更新2.2.21r修复

**Comment by GelmirSurion** [comment]
我也遇到了这个问题，是昨天更新2.21版本后才出现的，仔细看了一下，表现为打完雅利洛之后，切仙舟地图的时候，会尝试打开仙舟地图，但这一下必然会失败，然后就卡在选择地图界面。同样的，如果从仙舟开始锄，锄完鳞渊境之后，也会在切匹诺康尼的时候必然失败。
