### ISSUE TITLE
[路线错误] 朝露公馆，黄泉模式，地图右上角3D区域会漏一只怪

### ISSUE THREAD

**Issue by qiulonglideziyou** [linruowuyin/Fhoe-Rail#311]
### 问题描述

朝露公馆，黄泉模式，地图右上角3D区域会漏一只怪
![QQ截图20240608125812](https://github.com/linruowuyin/Fhoe-Rail/assets/24731783/11a9b780-2b68-444e-8b43-9f857a446b1e)
![QQ截图20240608125803](https://github.com/linruowuyin/Fhoe-Rail/assets/24731783/5cdbaea6-4370-4790-98e7-1e7ceb8d6579)

### 日志

[日志文件.log](https://github.com/user-attachments/files/15746529/default.log)

**Comment by qiulonglideziyou** [comment]
版本2.2.20，迥星港-飞星小筑，漏一只怪不知道2.2.21更新没有（今天有卡死bug就回滚了）
![QQ图片20240608125555](https://github.com/linruowuyin/Fhoe-Rail/assets/24731783/8c361d0f-ec10-4d48-a5fe-3f8bff8bde50)

**Comment by smjes3** [comment]
飞星小筑的没有漏过。。如果要修复的话请另开一个issue，并且附上单独跑飞星小筑的录屏方便修复。
