### ISSUE TITLE
[路线错误] 黄泉地图漏怪

### ISSUE THREAD

**Issue by MyAngelKokkoro** [linruowuyin/Fhoe-Rail#315]
### 问题描述

残响回廊的这个怪是最近一个月的锄地都有漏
迴星港的和之前的issue一样，偶发漏怪，就不放截图了
丹鼎司这个位置的怪是最近一周的版本有漏怪，可能有部分按键错误
![QQ图片20240618113528](https://github.com/linruowuyin/Fhoe-Rail/assets/166719271/0eb7d47a-14b6-4e7c-a9c1-e0c973477e67)

![QQ图片20240618113513](https://github.com/linruowuyin/Fhoe-Rail/assets/166719271/04c8263d-7b3a-4ec9-a9d9-acb9e666038b)

### 日志

[日志文件.log](https://github.com/user-attachments/files/15880054/default.log)

**Comment by smjes3** [comment]
1、残响回廊的需要录制视频看下漏怪原因，看了日志和本地录屏目前没问题
2、迴星港也需要录制视频，看了日志和本地录屏没问题
3、丹鼎司的已在2.3.01修复

**Comment by smjes3** [comment]
#318
