### ISSUE TITLE
[路线错误] [有录像、日志、config] 完整运行多地图漏怪、偶发卡死

### ISSUE THREAD

**Issue by qiulonglideziyou** [linruowuyin/Fhoe-Rail#318]
### 问题描述

本次为从开拓之尾开始运行全部地图。
看了3个小时路线，先辛苦大大修bug了！
1、【残响回廊-古战场前线】今日新发现的，不能判断是偶发还是常驻。
2、【迥星港-飞星小筑（map3-1）】，单独运行锄大地独跑3-1不会漏怪，但是从其他星球过来执行3-1就会漏这只。
3、【鳞渊境-孽兽之形·凝滞虚影】今日新发现的，不能判断是偶发还是常驻。
4、【白日梦酒店梦境-珍藏之蕾·逆造花萼（金）】今日新发现的，不能判断是偶发还是常驻。怀疑是因为门口第一只怪没秘技杀到，被怪袭击了，所以路线走错了。
5、【朝露公馆-城市沙盘-嗔怒之形·凝滞虚影】今日偶发卡死。

视频投稿地址https://www.bilibili.com/video/BV1AYgbegECG/

### 日志

[日志文件.log](https://github.com/user-attachments/files/15934641/default.log)
[config.json](https://github.com/user-attachments/files/15934721/config.json)

**Comment by smjes3** [comment]
1、2、5均进行了尝试性修复，因为本机无法复现，只能根据你提供的视频进行了一些微调。稍后更新2.3.02后再看看。

第3点为2.3版本更新后出现的问题，本机能复现且在2.3.02中修复
第4点同上

**Comment by qiulonglideziyou** [comment]
2.3.02版本5、【朝露公馆-城市沙盘-嗔怒之形·凝滞虚影】仍旧卡死
[日志文件.log](https://github.com/user-attachments/files/15942127/default.log)
录像：https://www.bilibili.com/video/BV1QGgBeyEiq/

1、2、3、4本次未漏怪

**Comment by smjes3** [comment]
你昨天的5好像不是今天这个5吧，昨天的5你看修复了吗
今天你发的这个视频【朝露公馆-迎宾处】运行至右上角3D区域仍旧卡死。我晚点修一下你更新2.3.03看看

**Comment by qiulonglideziyou** [comment]
> 你昨天的5好像不是今天这个5吧，昨天的5你看修复了吗 今天你发的这个视频【朝露公馆-迎宾处】运行至右上角3D区域仍旧卡死。我晚点修一下你更新2.3.03看看

昨天的5已修复！可能今天早上太困了看差了，但是昨天跑的时候，今天报的错误这块也全卡住漏掉了。
