### ISSUE TITLE
[Bug] 2.3漏怪反馈

### ISSUE THREAD

**Issue by BROWNBRONY** [linruowuyin/Fhoe-Rail#320]
### 问题描述

完整运行后有部分地图概率漏怪和必定漏怪

### 预期行为

不漏怪

### 实际行为

完整运行后有部分地图概率漏怪和必定漏怪

### 截图或录屏

测试1号位：阮梅、托帕
1.筑梦边境（概率3只）：建议此段多运行1-2遍
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/dd228e3b-cf8c-42bf-9eed-6f86251fbb05)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/610a304e-20e5-4dd1-aae9-9954bb48a27b)
2.白日梦酒店下（几乎必定2-4只）：秘境里左侧2-4只往往漏掉。而右侧1只往往却可以锄掉（小概率也会漏）
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/071e0a37-32b2-4ed1-af2d-ebdaf5df8c15)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/453faf32-3242-4ff5-bac8-385b28d0f7dd)
3.白日梦酒店左下（几乎必定3-5只）：秘境里中间、右边电视机和右边的狗大概率漏掉，有的时候锄1剩1（小概率）
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/aae4b4e3-caf5-4a79-a6fd-67fd5c63cad9)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/5783df9a-7967-49e2-b14a-5e0a2c712c80)
4.大剧院右（几乎必定1-3只）汽水狗必漏，其余两只概率会漏
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/2d884a2b-28aa-450d-a95e-bf62e528eb1b)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/678af618-9b42-4a44-95ef-19113d223a15)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/e679cf59-7826-4b16-bec5-33704bf3ca35)
5.大剧院中右秘境（必定1只）会飞的迷因:建议走到隔岸正中央用远程角色普攻击杀。另一只胖的迷因在上版本也是必漏
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/4372cf5b-d42f-4972-91ce-381981cac4af)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/e7d584bf-ad29-4fba-9b0a-5429e9bbcd55)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/e200a09d-4b1d-4485-9d9b-52086132f86f)
6.收容舱段（必定1只）2.3仍然有漏
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/081c71dd-283f-413e-b3b2-813c095e6112)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/57a980ce-97c2-4d5a-a5b0-b58e04f2cf47)

### 自动锄大地脚本版本

2.3.01

### 日志

[日志文件.log](https://github.com/user-attachments/files/15935410/default.log)

**Comment by BROWNBRONY** [comment]
好，近日会补录视频

**Comment by BROWNBRONY** [comment]
大剧院和白日梦酒店漏怪点相关视频（白日梦酒店疑似缺少相关锄地路线）
链接: https://pan.baidu.com/s/1ZsVFnqoApxCzBTYagogYIg?pwd=y7bq 提取码: y7bq 

[日志文件.log](https://github.com/user-attachments/files/16010564/default.log)

新增概率漏怪地点：三条烟花鱼有概率会漏（本次运行没有，但地图路线概率会卡模型建议多运行1-2遍）
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/c3f00bab-381e-48ea-ae3e-45986483828d)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/a0ebdb09-0299-4969-88bc-1f8460ebff94)

**Comment by smjes3** [comment]
- 白日梦左相关1.mkv
-- 前半段没看出问题，后半段修复了

- 白日梦下相关1.mkv
-- 没看出问题

- 白日梦下相关2.mkv
-- 没看出问题

- 白日梦左相关2.mkv
-- 前半段的遇袭问题优化了路线，后半段的遇袭问题需要提供下4-3_4（酒店梦境-4）的视频，看下为什么那个怪没有被清理掉

- 大剧院.mkv
-- 已修复

**Comment by BROWNBRONY** [comment]
白日梦+朝露录像“链接: https://pan.baidu.com/s/1A1Iagt5y2A1H9qrdznciLg?pwd=7h9k 提取码: 7h9k 

新增朝露公馆漏怪（3只）
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/1cb9c39e-d6a5-4973-bd08-63d6081e1d87)

烟花鱼漏怪：
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/50e3a9b1-6536-4f54-9299-97d3edf9da9e)
[烟花鱼.zip](https://github.com/user-attachments/files/16025017/default.zip)

压缩包覆盖原文件后运行的日志：[日志文件.log](https://github.com/user-attachments/files/16024988/default.log)
压缩包解压后单独运行的日志：[日志文件.log](https://github.com/user-attachments/files/16025036/default.log)

疑似缺少锄地路线即白日梦酒店左、下秘境的上版本锄地路线疑似漏掉一部分怪，如左秘境的右侧（进门右手边）3只怪、下秘境漏掉右侧两只怪（进门右手边），由于前置路线过长，不知是因卡模型引起漏怪还是原路线里没有覆盖到，故存疑。

**Comment by BROWNBRONY** [comment]
[收容舱段.zip](https://github.com/user-attachments/files/16025468/default.zip)

**Comment by smjes3** [comment]
白日梦+朝露公馆录像给的链接给错了，你给的和上次白日梦的内容一模一样。

疑似缺少锄地路线的回答：首先不存在原路线没有覆盖到。会查看你说的漏怪的点相应的路线回复给你具体的路线，方便你录屏以共同修正漏怪。

现在比较需要的是酒店梦境-4的录像，可以解决多个地图的漏怪问题（因为这里漏怪，导致的后续遇袭+路线错乱）

**Comment by BROWNBRONY** [comment]
抱歉，重新上传：链接: https://pan.baidu.com/s/1Lvd0vdtfB-moPpb7FHvBTQ?pwd=e4pc 提取码: e4pc 
（当天先运行的覆盖版再补录的独立版）不清楚是否因为覆盖后有些文件没有删干净，因此录2个版本
[酒店4.zip](https://github.com/user-attachments/files/16045841/4.zip)
帧率是60

**Comment by smjes3** [comment]
酒店-4，漏怪原因：场景细节过高。
请前往设置-图像-场景细节，设置为非常低。

**Comment by smjes3** [comment]
- 白日梦酒店.mkv
00:01:14处由于你电脑瞬间卡顿造成了w距离比预计的长，这种造成的漏怪目前无法避免。
同样视频你可以看到，有3次出生在电梯附近，交互上电梯后w一段距离d的操作，其中有2次w到指定位置向右正常进入了房间，有1次w过早结束没有到指定位置，导致向右撞墙了。这也是卡顿引起的。

- 朝露公馆.mkv
和之前的烟花鱼、收容舱段一样，我需要本机验证托帕会不会出现，如果确实是托帕腿短的话会优化路线。
不过基于今天的新发现有可能会是卡顿造成移动不到位。

- 解压后单独运行（没有覆盖原文件），白日梦+朝露公馆.mp4
全程太卡只看了一半，没什么参考意义。


建议你可以先将场景细节设置为**非常低**，这非常重要，因为场景细节高会造成地图中多出模型物件，导致破坏路线。

**Comment by BROWNBRONY** [comment]
已修改场景设置，后续降低cpu占有尝试解决卡顿问题。近日会反馈2.3.04版本运行情况

**Comment by BROWNBRONY** [comment]
补充：
今日1号位用阮梅也出现烟花鱼和收容舱段漏怪的问题
大剧院中右秘境也出现先前提及2只漏怪问题
[日志文件.log](https://github.com/user-attachments/files/16082014/default.log)
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/147940901/83a6e2e6-6fca-42d5-9667-62cf9cd463a3)

酒店下秘境没有漏怪，右秘境漏右侧1只汽水狗

**Comment by smjes3** [comment]
看了日志是2.3.03的，2.3.04修复了：
1、大剧院右秘境2只漏怪问题
2、酒店梦境的一些容易遇袭的怪优化路线

暂不处理的（本机测试通过，没有更多证据指向是路线问题，但可以以后优化兼容路线）：
1、烟花鱼
2、收容舱段

**Comment by BROWNBRONY** [comment]
​
・自己紹介（名前、学歴、仕事内容、応募理由、性格等）&nbsp;

・現在、日本語は使用していますか？どのような場面で使用していますか？&nbsp;

・日本語を勉強しようと思ったきっかけは何ですか？&nbsp;

・過去の職歴について&nbsp;

・なぜ日本で働きたいですか？&nbsp;

・日本でやりたい仕事はなんですか？&nbsp;

・＜販売職希望の場合＞この先長く販売職を続けていく予定ですか？&nbsp;

・販売職などサービス業の経験はありますか？（正社員でもアルバイトでも）&nbsp;

・販売職はシフト制で土日祝日、中国の連休が休めないこともありますが問題ないですか？早番、遅番は問題ないですか？&nbsp;

・日本での希望勤務地（郊外含め問題ないか、指定エリアのみか）&nbsp;

・自分の強みを生かして日本でやりたいこと、将来的に日本でやりたいことは何ですか？&nbsp;

・日本でどれくらいの期間働きたいですか？将来の計画（キャリアビジョン）はありますか？&nbsp;

・いつ頃日本に来れますか？&nbsp;

・自分の長所、短所&nbsp;

・趣味、好きなこと&nbsp;

・これまでの経験で大変だったこと、それをどう乗り越えたか&nbsp;


非的龙龙
***@***.***







                       
Original Email
                       
                     

From:"smjes3"< ***@***.*** &gt;;

Sent Time:2024/7/3 22:14

To:"linruowuyin/Fhoe-Rail"< ***@***.*** &gt;;

Cc recipient:"BROWNBRONY"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [linruowuyin/Fhoe-Rail] [Bug] 2.3漏怪反馈 (Issue #320)




 
看了日志是2.3.03的，2.3.04修复了：
 1、大剧院右秘境2只漏怪问题
 2、酒店梦境的一些容易遇袭的怪优化路线
 
暂不处理的（本机测试通过，没有更多证据指向是路线问题，但可以以后优化兼容路线）：
 1、烟花鱼
 2、收容舱段
