### ISSUE TITLE
[路线错误] 2.3.01黄泉地图漏怪

### ISSUE THREAD

**Issue by MyAngelKokkoro** [linruowuyin/Fhoe-Rail#321]
### 问题描述

1. 白日梦酒店右下梦境区域漏怪，回看录屏时发现是门口的迷因少砍一刀，没砍到导致入战，后续视角全错
2. 大剧院3d地图区域漏怪，回看录屏时发现是被梦泡卡住，导致没有后续
![QQ截图20240622133325](https://github.com/linruowuyin/Fhoe-Rail/assets/166719271/5419aba1-e248-4346-a199-3943a45df067)
![B4HIV2GXRF23G0` ~}{G1HT](https://github.com/linruowuyin/Fhoe-Rail/assets/166719271/c16a36a3-2ef0-40cd-ac25-8b107a454c8d)

### 日志

[日志文件.log](https://github.com/user-attachments/files/15935480/default.log)

**Comment by smjes3** [comment]
第一个在2.3.02应该修复了，你更新看看
第二个我验证一下然后换个路线晚点更新。

**Comment by smjes3** [comment]
#322
