### ISSUE TITLE
[路线错误] 2.3.03黄泉路线漏怪反馈

### ISSUE THREAD

**Issue by qiulonglideziyou** [linruowuyin/Fhoe-Rail#323]
### 问题描述

1、城郊雪原-巡猎之蕾·拟造花萼（赤），左侧小屋漏怪，这个点大概隔一天漏一次。感觉第一次走到那只漏掉的小怪下面比较好。
2、上次修过的【鳞渊境-孽兽之形·凝滞虚影】今又漏了一次。
录像：https://www.bilibili.com/video/BV1jj3reYEDw/

### 日志

[日志文件.log](https://github.com/user-attachments/files/15996972/default.log)

**Comment by qiulonglideziyou** [comment]
第一个点今天又漏了

第二个点今天没漏，看来是偶发情况

**Comment by smjes3** [comment]
#324
