### ISSUE TITLE
[功能请求] 支持幽囚狱锄大地

### ISSUE THREAD

**Issue by JosephZheng1998** [linruowuyin/Fhoe-Rail#328]
### 原因

2.4 更新幽囚狱地图 里面有怪

### 功能逻辑

录制 2.4 幽囚狱地图

**Comment by Hylouis233** [comment]
+1, 跪求

**Comment by MyAngelKokkoro** [comment]
+1

**Comment by smjes3** [comment]
目前只更新了黄泉版本的，且因为有个机关目前还在想处理方式，所以有个平台上还会漏1只

**Comment by kevin-chengce** [comment]
希望可以更新非黄泉路线地图

**Comment by smjes3** [comment]
> 希望可以更新非黄泉路线地图

有小伙伴帮助更新了非黄泉地图，请稍后更新2.5.03试试
