### ISSUE TITLE
[Bug] 请问脚本运行时有没有暂停键？AttributeError: 'NoneType' object has no atrribute 'key'

### ISSUE THREAD

**Issue by valris** [linruowuyin/Fhoe-Rail#329]
### 问题描述
1，请问脚本运行时有没有暂停键？锄地耗时很长，可能需要中途手动操作。
2，打开自选地图.bat可以运行。
打开Fhoe-Rail.exe会闪退，我录屏才截到了这些红色英文字符。
请问这是什么状况？非常感谢。

### 预期行为

Fhoe-Rail.exe不闪退

### 实际行为

Fhoe-Rail.exe 红字并闪退了

### 截图或录屏

![2024-08-12  1](https://github.com/user-attachments/assets/0184a15a-04ff-43e3-9310-07668632171b)

### 自动锄大地脚本版本

2.3.04

### 日志

[Uploading 日志文件.log…]()

**Comment by smjes3** [comment]
检查目录下config.json中的配置
"main_map": "1"
如果不是这个请贴出你的设置，报错与这个配置错误有关。

**Comment by i-cecreamer** [comment]
F8暂停，F7继续
