### ISSUE TITLE
总是卡在,鳞渊境-5 的最后.

### ISSUE THREAD

**Issue by magian1127** [linruowuyin/Fhoe-Rail#33]
map_3-7_5.json
结束以后, 要跳转到 鳞渊境-6 的时候就卡主了. 什么提示也没.
以前就有这个问题, 但是后面也就2个怪,就无所谓了.

现在用了最新版本. 
会不停的提示
打开地图
打开地图

手动打开一下地图,后续就正常了..

不知道是不是 快捷键触发问题.. 能不能加个判断,,重复 打开地图 还是打不开的话 用鼠标点击地图打开

**Comment by linruowuyin** [comment]
不是打不开，是在判断地图有没有打开，脚本是按m打开地图，下一步会去找地图最小化图标，找不到就一直打开地图，直到打开地图为止。跳转到 鳞渊境-6 的时候就卡也是识别不到传送点图标，建议自己截图替换再试一下，如果有开启hdr之类的需要关闭。如果是普遍有这个问题的话会专门修的，个例的话没办法（

**Comment by magian1127** [comment]
1 结束map_3-7_5.json 后
2 程序视图打开地图, 然后打不开,就不停的输出 "打开地图" (他打不开的,我等了15分钟)
3 此时,我手动打开一下地图.
4 程序就正常正常工作了
5 可能是我电脑没有键盘的原因(挂这个的电脑没有)
6 但是,其他地方没有这个问题,只会发生在要 去 鳞渊境-6 的地方.
7 没有HDR

我再研究下吧..
