### ISSUE TITLE
[Bug] 2.4.02漏怪反馈

### ISSUE THREAD

**Issue by i-cecreamer** [linruowuyin/Fhoe-Rail#334]
### 问题描述

幽囚狱2个地方脚本没有去，以及路线优化问题

### 预期行为

不漏怪

### 实际行为

幽囚狱跑图漏怪和2个地方没有包含以及朝露公馆4-4-1最后一只怪偶尔会没锄到

### 截图或录屏

![幽囚狱无路线1](https://github.com/user-attachments/assets/8a8d406f-49dc-4aba-b690-ae0d6cba6afd)
![幽囚狱无路线1地图](https://github.com/user-attachments/assets/f9b6cd98-ab82-4255-9168-c6255462c329)
![幽囚狱无路线2](https://github.com/user-attachments/assets/8b757ea1-11a1-4f6a-ab20-7ba0cd3e70c9)
![幽囚狱无路线地图2](https://github.com/user-attachments/assets/4fa02ae8-f2c6-4002-8493-aa11b40b4f05)
![幽囚狱脚本漏怪1](https://github.com/user-attachments/assets/199610a5-7faa-4f40-b761-fbbd987cc383)
![幽囚狱脚本漏怪1地图](https://github.com/user-attachments/assets/b348599f-fa51-4296-928e-0c4b4f92581c)
![朝露公馆](https://github.com/user-attachments/assets/b6e990ce-53f0-418e-abbf-ffbb0dd2680d)
![朝露公馆 (2)](https://github.com/user-attachments/assets/d9480620-a1b1-421f-9593-425d13de4793)

### 自动锄大地脚本版本

2.4.02

### 日志

[231.log](https://github.com/user-attachments/files/16644590/231.log)

**Comment by i-cecreamer** [comment]
幽囚狱跑图漏怪以及朝露公馆4-4-1最后一只怪偶尔会没锄到这个问题这两天暂时没遇到，不排除可能当时电脑卡了

**Comment by smjes3** [comment]
你列了3个问题，按顺序列了一下
1、幽囚狱某个二楼漏怪（确实存在，这块还没有好办法解决目前，担心控制开关出错导致更大范围漏怪）
2、幽囚狱某个右侧漏怪（确实存在，原因同上）
3、幽囚狱某个左侧区域漏怪（我自己号测试偶尔存在，再观察观察）
4、朝露公馆4-4-1漏怪（我自己测试似乎没有发生过，再观察观察）

**Comment by i-cecreamer** [comment]
> 你列了4个问题，按顺序列了一下 1、幽囚狱某个二楼漏怪（确实存在，这块还没有好办法解决目前，担心控制开关出错导致更大范围漏怪） 2、幽囚狱某个右侧漏怪（确实存在，原因同上） 3、幽囚狱某个左侧区域漏怪（我自己号测试偶尔存在，再观察观察） 4、朝露公馆4-4-1漏怪（我自己测试似乎没有发生过，再观察观察）

漏的2只隐形怪可在3-8-5处加入一条，因为路线相同不需要改控制开关，在电梯处往后走就是两只隐形怪，剩下优化我也无能为力了
![QQ截图20240825132747](https://github.com/user-attachments/assets/cd7506a4-0e1b-4d56-bcd2-53805bfac054)

**Comment by i-cecreamer** [comment]
另附一个小建议，柳丁镇的上方传送点因活动导致无法传送，希望加一个二级菜单，毕竟活动还有半个月
![QQ截图20240825133746](https://github.com/user-attachments/assets/2e8d318d-2c27-43d0-973a-95cf5ebc5a09)
