### ISSUE TITLE
[Bug] 降低月卡识别的难度

### ISSUE THREAD

**Issue by MyAngelKokkoro** [linruowuyin/Fhoe-Rail#335]
### 问题描述

想着挂4点定时续锄，结果 “找不到与月卡图片相符的图，图片匹配度：0.90 需要 > 0.91“，没点到月卡导致后续无法运行

### 预期行为

点击月卡

### 实际行为

没点击月卡

### 自动锄大地脚本版本

2.4.02

### 日志

[日志文件.log](https://github.com/user-attachments/files/16920556/default.log)

**Comment by smjes3** [comment]
我这里自测是没问题的，你看下你那里是否必然会出现这个问题

`
04:01:00 - INFO   	| calculated.try_click_pass:1164           	- 2.4.02 - 点击月卡
04:01:00 - INFO   	| calculated.click:148                     	- 2.4.02 - 点击坐标(1014, 912)
04:01:01 - INFO   	| calculated.try_click_pass:1168           	- 2.4.02 - 识别到月卡，图片匹配度: 0.98 (1014, 912)
04:01:05 - INFO   	| calculated.try_click_pass:1164           	- 2.4.02 - 点击月卡
04:01:05 - INFO   	| calculated.click:148                     	- 2.4.02 - 点击坐标(1014, 912)
04:01:05 - INFO   	| calculated.try_click_pass:1168           	- 2.4.02 - 识别到月卡，图片匹配度: 0.98 (1014, 912)
`

**Comment by smjes3** [comment]
我这里自测是没问题的，你看下你那里是否必然会出现这个问题

04:01:00 - INFO   	| calculated.try_click_pass:1164           	- 2.4.02 - 点击月卡
04:01:00 - INFO   	| calculated.click:148                     	- 2.4.02 - 点击坐标(1014, 912)
04:01:01 - INFO   	| calculated.try_click_pass:1168           	- 2.4.02 - 识别到月卡，图片匹配度: 0.98 (1014, 912)
04:01:05 - INFO   	| calculated.try_click_pass:1164           	- 2.4.02 - 点击月卡
04:01:05 - INFO   	| calculated.click:148                     	- 2.4.02 - 点击坐标(1014, 912)
04:01:05 - INFO   	| calculated.try_click_pass:1168           	- 2.4.02 - 识别到月卡，图片匹配度: 0.98 (1014, 912)

**Comment by MyAngelKokkoro** [comment]
不是必然出现，这一周一共有过两次

**Comment by MyAngelKokkoro** [comment]
不是必然出现，最近七天出现过两次
