### ISSUE TITLE
[路线错误] 匹诺康尼大剧院会点击到NPC按钮导致进入对话无法继续

### ISSUE THREAD

**Issue by 0xingchen0** [linruowuyin/Fhoe-Rail#339]
### 问题描述

![IMG_3913](https://github.com/user-attachments/assets/c0c16f03-0249-4c1b-a93d-ee359b410989)
![IMG_3618](https://github.com/user-attachments/assets/9c585acc-4d46-4165-b015-3ed0567fdd2f)

### 日志

07:08:51 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:40/81 {'d': 1.5}
07:08:52 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:41/81 {'w': 3}
07:08:55 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:42/81 {'d': 1.1}
07:08:56 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:43/81 {'e': 2}
07:08:56 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.0 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:08:57 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:44/81 {'e': 2}
07:08:58 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.0 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:08:58 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:45/81 {'w': 3}
07:08:59 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.0 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:08:59 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:08:59 - INFO   	| calculated.detect_fight_status:506       	- 2.5.03 - 开始识别是否进入战斗
07:09:00 - INFO   	| calculated.no_in_fight_status:495        	- 2.5.03 - 未战斗识别，匹配度0.861，需要0.95
07:09:00 - INFO   	| calculated.fight_elapsed:562             	- 2.5.03 - 战斗开始
07:09:05 - INFO   	| calculated.fight_elapsed:596             	- 2.5.03 - 开启自动战斗
07:09:20 - INFO   	| calculated.fight_elapsed:613             	- 2.5.03 - 开启自动战斗（通过行动条识别）
07:19:00 - INFO   	| calculated.fight_elapsed:632             	- 2.5.03 - 战斗超时
07:19:02 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:46/81 {'f': 1}
07:19:02 - INFO   	| calculated.check_f_img:722               	- 2.5.03 - 扫描'F'图标
07:19:09 - INFO   	| calculated.analyze_found_images:779      	- 2.5.03 - 扫描失败！
07:19:09 - INFO   	| calculated.handle_f:903                  	- 2.5.03 - 检测到非正常'F'情况，不执行并跳过'F'
07:19:09 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:47/81 {'s': 4}
07:19:12 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:48/81 {'a': 1}
07:19:13 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:49/81 {'w': 0.3}
07:19:13 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:50/81 {'a': 4}
07:19:16 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:51/81 {'f': 1}
07:19:16 - INFO   	| calculated.check_f_img:722               	- 2.5.03 - 扫描'F'图标
07:19:21 - INFO   	| calculated.analyze_found_images:779      	- 2.5.03 - 扫描失败！
07:19:21 - INFO   	| calculated.handle_f:903                  	- 2.5.03 - 检测到非正常'F'情况，不执行并跳过'F'
07:19:21 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:52/81 {'1': 2}
07:19:23 - INFO   	| calculated.auto_map:820                  	- 2.5.03 - 执行map_4-7_8文件:53/81 {'main': 2}
07:19:27 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:19:28 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.837
07:19:30 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:19:30 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.837
07:19:32 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最高匹配值0.860
07:19:33 - INFO   	| calculated.on_interface:1367             	- 2.5.03 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.837
07:19:35 - INFO   	| calculated.on_interface:1367

**Comment by smjes3** [comment]
是否必定出现？

**Comment by 0xingchen0** [comment]
> 是否必定出现？

目前运行六次出现两次
