### ISSUE TITLE
30r版本在战斗中会不断的中断战斗

### ISSUE THREAD

**Issue by ddd-zero** [linruowuyin/Fhoe-Rail#34]
进入战斗后会这样，按esc暂停。![image](https://github.com/linruowuyin/Fhoe-Rail/assets/57771987/9a517c85-0350-4721-aa30-17ac2354329a)

**Comment by 0frostmourne0** [comment]
确实存在这个情况，筑梦没跑完已经ESC 3次了……

**Comment by jowilksasella** [comment]
耐心等待大概一分多鐘，它就會自動退出這個界面了。不過自動戰鬥會被取消。

**Comment by Tom-xia** [comment]
同样有这个问题，但是我这边并不会自动退出这个界面。另外，手动退出这个界面后，自动战斗也会被取消
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/06866701-fc4b-43d5-8ffb-e6373d1c28c2)

**Comment by DragonQuestXI** [comment]
我也遇到了类似的问题
自动战斗被取消，进入查看怪物素材的页面导致没法继续

**Comment by linruowuyin** [comment]
看一下31版本有没有这个情况，识别错误导致的

**Comment by ddd-zero** [comment]
我测试了一次。似乎没有暂停了
