### ISSUE TITLE
[路线错误] 幽囚狱 3-8-5地图路线错误

### ISSUE THREAD

**Issue by zjkx8** [linruowuyin/Fhoe-Rail#341]
### 问题描述

**该问题单独锄地&连续运行均为必现**

3-8-5地图,电梯旁边按钮 ,未考虑到人物停止时向前运动的惯性,导致与电梯按钮错开.
但由于会短暂出现F图标,导致程序默认会执行按下F的指令,实际并未正确下层,后续逻辑全部错误
![image](https://github.com/user-attachments/assets/521f3030-890b-48fb-a277-9684d6f0a32d)

此外,即使我通过快速手动调整,到下一层一样会卡在这里,同样存在路线BUG,无法正确传送,导致整张地图都被跳过
![image](https://github.com/user-attachments/assets/2a2c97db-f736-4c41-990f-02fa3d7ed12d)

### 日志

05:21:31 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:5/60 {'s': 8}
05:21:36 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:6/60 {'d': 6}
05:21:41 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:7/60 {'a': 1}
05:21:42 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:8/60 {'w': 0.3}
05:21:42 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:9/60 {'d': 4}
05:21:45 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:10/60 {'w': 4}
05:21:48 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:11/60 {'s': 0.8}
05:21:49 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:12/60 {'d': 0.13}
05:21:49 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:13/60 {'f': 2}
05:21:49 - INFO   	| calculated.check_f_img:722               	- 2.5.04 - 扫描'F'图标
05:21:49 - INFO   	| calculated.check_f_img:732               	- 2.5.04 - 扫描'F'：target，匹配度：1.000
05:21:51 - INFO   	| calculated.check_f_img:732               	- 2.5.04 - 扫描'F'：target，匹配度：1.000
05:21:51 - INFO   	| calculated.analyze_found_images:777      	- 2.5.04 - 扫描到 'F'
05:21:51 - INFO   	| calculated.handle_f:894                  	- 2.5.04 - 按下'F'，等待10秒
05:22:01 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:14/60 {'s': 2}
05:22:03 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:15/60 {'d': 4}
05:22:06 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:16/60 {'s': 0.8}
05:22:07 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:17/60 {'d': 0.2}
05:22:07 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:18/60 {'f': 2}
05:22:07 - INFO   	| calculated.check_f_img:722               	- 2.5.04 - 扫描'F'图标
05:22:13 - INFO   	| calculated.analyze_found_images:779      	- 2.5.04 - 扫描失败！
05:22:13 - INFO   	| calculated.handle_f:903                  	- 2.5.04 - 检测到非正常'F'情况，不执行并跳过'F'
05:22:13 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:19/60 {'w': 6}
05:22:17 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:20/60 {'d': 1}
05:22:18 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:21/60 {'w': 4}
05:22:21 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:22/60 {'a': 2}
05:22:23 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:23/60 {'w': 2}
05:22:25 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:24/60 {'a': 2}
05:22:27 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:25/60 {'w': 2}
05:22:29 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:26/60 {'a': 0.8}
05:22:30 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:27/60 {'w': 3}
05:22:32 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:28/60 {'d': 0.15}
05:22:32 - INFO   	| calculated.auto_map:820                  	- 2.5.04 - 执行map_3-8_5文件:29/60 {'e': 2}

**Comment by smjes3** [comment]
本机多次测试并未发现此问题。

**Comment by zjkx8** [comment]
> 本机多次测试发现此问题。 偶发的系统卡顿会造成推理比预想的要多，这个暂时无法解决。

大佬辛苦了,这个问题我用黄泉模式又测试了十次左右,单次运行从3-8-5,从幽囚狱最下层传送过去,每次都是对齐不了,问题是必现的,期间并无卡顿,如果是我设备问题的话就算了,感谢.

**Comment by smjes3** [comment]
尝试增加了一个攻击动作消除跑步的惯性，看下是否修复成功，2.5.05版本。

**Comment by zjkx8** [comment]
> 尝试增加一个攻击消除动作的惯性，看下修复是否成功，2.5.05版本。

问题已解决!辛苦大佬
