### ISSUE TITLE
[Bug] 星铁2.6人物移动底层改动造成的锄大地位移不准确

### ISSUE THREAD

**Issue by smjes3** [linruowuyin/Fhoe-Rail#343]
### 问题描述

星铁人物移动底层改动造成的锄大地位移不准确

### 预期行为

正确位移

### 实际行为

移动跑步衔接与2.5版本不一致

### 自动锄大地脚本版本

2.5

### 日志

。

**Comment by valris** [comment]
是的，乱破版本更新后，全乱了。

1，之前的脚本逻辑是，移动秒数大于2秒（大概是 我不确定），就会走一段时间后自动进入奔跑模式，现在是有时候跑，有时候不跑了。
举个例子，匹诺康尼大剧院→第9条路线，向上2.5秒，向右10秒，向右10秒居然不跑，改走路了。
2，向左0.5秒居然移动得比乱破版本前的0.5秒移动得远！？！

这一巨大变动，使得移动距离时长时短，很多路线都报废了。
