### ISSUE TITLE
[功能请求]能否添加一个跳过一些星球或者路线的功能

### ISSUE THREAD

**Issue by smallmj** [linruowuyin/Fhoe-Rail#349]
其实全员已经满级了，已经没有锄大地的需求了，单纯就是想每周能自动去买过期邮报和代币

**Comment by smjes3** [comment]
config.json中对forbid_map进行配置，目前只支持跳过地图，例如：
"forbid_map": [‘工造司’,'收容舱段','工造司（金人）'],
代表跳过工造司，收容舱段，和工造司金人的路线。
名称需要与map文件夹中json文件的"name"字段的一致，写工造司的话就会跳过工造司-1，-2，-3……不能单独跳过某个例如工造司-2。

**Comment by coooooin** [comment]
"forbid_map": ['晖长石号','城郊雪原','基座舱段','收容舱段','支援舱段','禁闭舱段','边缘道路','残响回廊','永冬岭','大矿区','铆钉镇','机器聚落','迴星港','太卜司','工造司','绥 园','丹鼎司','鳞渊境','幽囚狱','筑梦边境','稚子的梦','酒店梦境','朝露公馆','影视乐园','热砂海选会场','大剧院']

把这段的单引号换成双引就行了
