### ISSUE TITLE
[Bug] 经常卡死不动（

### ISSUE THREAD

**Issue by WhyPilotXia** [linruowuyin/Fhoe-Rail#350]
### 问题描述

经常卡死不动（无法开始）

### 预期行为

正常开始，漏怪漏图什么的不重要了，但是无法开始就有点难受

### 实际行为

经常卡死不动（无法开始）

### 截图或录屏

视频：
https://fast.uc.cn/s/811e05d87bcb4 点击链接接收文件 [锄大地错误QQ2024124-182148-HD.mp4]
日志：
18:22:36 - calculated.on_interface:1428 - 2.6.03 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.815
18:22:36 - calculated.on_interface:1419 - 2.6.03 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
18:22:36 - calculated.on_interface:1420 - 2.6.03 - 检测图片序号为0，匹配度0.995，匹配位置为(780, 273)
18:22:36 - map.map_init:38 - 2.6.03 - 打开地图
18:22:42 - calculated.on_interface:1428 - 2.6.03 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最 高匹配值0.895
18:22:44 - calculated.on_interface:1428 - 2.6.03 - 在 0.0 秒 的时间内未检测到，相似图片最高匹配值0.815
18:22:44 - calculated.on_interface:1419 - 2.6.03 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.1 秒
18:22:44 - calculated.on_interface:1420 - 2.6.03 - 检测图片序号为0，匹配度0.995，匹配位置为(780, 273)
18:22:44 - map.map_init:38 - 2.6.03 - 打开地图
18:22:49 - calculated.on_interface:1428 - 2.6.03 - 在 2 秒 的时间内未检测到游戏主界面，非战斗/传送/黑屏状态，相似图片最 高匹配值0.895

### 自动锄大地脚本版本

2.6.03

### 日志

[日志文件.log](https://github.com/user-attachments/files/18006432/default.log)

**Comment by WhyPilotXia** [comment]
游戏使用1920*1080分辨率，之前是到流云渡就会卡死（刚开始能运行，到这就进入类似现在视频里面状态）

这次是直接无法开始了qwq

**Comment by WhyPilotXia** [comment]
使用原版运行出现相同错误：https://fast.uc.cn/s/d40cbc07d16e4 点击链接接收文件 [锄大地错误2.mp4]

**Comment by Excels1orN** [comment]
应该是地图上多了个星穹列车，无法识别吧？

**Comment by HackettHsu** [comment]
我是直接刚开始检索到差分宇宙那里就卡住了

**Comment by WhyPilotXia** [comment]
> 我是直接刚开始检索到差分宇宙那里就卡住了

我差分宇宙也会卡死，但是以前都是打完锄大地挂机回来发现电脑卡在差分，就知道说明打完了，对我其实不影响

**Comment by HackettHsu** [comment]
准确的说，我每次锄大地开始时都会到差分宇宙面前过一下，以前都是正常过完差分宇宙直接就去空间站开始锄地了。但这次更新后，就卡在差分宇宙前面，一直重复开地图-关地图的操作

**Comment by WhyPilotXia** [comment]
> 准确的说，我每次锄大地开始时都会到差分宇宙面前过一下，以前都是正常过完差分宇宙直接就去空间站开始锄地了。但这次更新后，就卡在差分宇宙前面，一直重复开地图-关地图的操作

哈哈哈，那我之前是相反，出完大地才去差分宇宙那边卡着，所以没事。现在是锄大地重复开关地图了

**Comment by kevin-chengce** [comment]
同问题 无法开始

**Comment by czcmh** [comment]
同问题 无法开始

**Comment by 0frostmourne0** [comment]
参考 https://github.com/linruowuyin/Fhoe-Rail/issues/351
