### ISSUE TITLE
2.7版本临时解决方法

### ISSUE THREAD

**Issue by 0frostmourne0** [linruowuyin/Fhoe-Rail#351]
2.7更新后锄地失效了，表现为反复开关地图

没详细log只能靠猜……
根据现象判断应该是打开地图后没识别，导致触发超时ESC功能。
原因是米哈游吧地图缩小的按钮改细了……

下载压缩包覆盖原文件即可解决问题
[picture.zip](https://github.com/user-attachments/files/18011654/picture.zip)
如果不行可能是分辨率不一样或者其他原因，可以尝试自己截图替换 /picture/contraction.png

目前似乎没发现其他问题

**Comment by smjes3** [comment]
更新2.7.01版本，#352

**Comment by GelmirSurion** [comment]
直接下2.7.01和这个图片的都没用，自己截了一个好了

**Comment by smjes3** [comment]
#354 2.7.02 使用了压缩包的图片文件进行替换。
