### ISSUE TITLE
[Bug] 不能正常使用奇巧零食

### ISSUE THREAD

**Issue by yjay303** [linruowuyin/Fhoe-Rail#353]
### 问题描述

这版本新加了一个补充秘技点的消耗品,奇巧零食被挤到第二页,导致锄大地时秘技点消耗完后不能正常使用奇巧零食

### 预期行为

使用奇巧零食补充秘技点

### 实际行为

打开消耗品页面后停顿一段时间之后关掉窗口

### 截图或录屏

(https://github.com/user-attachments/assets/988dfb09-998d-41f6-8bbf-fa589700fb91)

### 自动锄大地脚本版本

2.7.01

### 日志

[日志文件.2024-12-04_00-57-09_789341.log](https://github.com/user-attachments/files/18017582/2024-12-04_00-57-09_789341.log)

**Comment by smjes3** [comment]
#354  2.7.02尝试下滑最多4次查找零食，但是手头没有能测试的账号，需要你自己测试下是否可用

**Comment by yjay303** [comment]
已解决
