### ISSUE TITLE
白日梦地图疑似重复

### ISSUE THREAD

**Issue by Tom-xia** [linruowuyin/Fhoe-Rail#37]
已更新到2.035版本
如图示：白日梦地图存在重复，不太清楚大佬是不是地图设计有意为之。
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/d7df8a20-4af0-4ff8-bc96-e56d9d83b629)

目前遇到的问题是：「白日梦」酒店梦境-1脚本运行 上完电梯后，就打开地图开始运行酒店梦境-1脚本。可是并没有进入梦境地图，而是误点进入稚子的梦地图。此时脚本仍在正常运行，但角色实际上已经卡死在错误的地图里打圈圈了。
望大佬有空检查一下
![image](https://github.com/linruowuyin/Fhoe-Rail/assets/51754284/19a6751a-7438-46fe-8c2b-6f6330283505)

**Comment by linruowuyin** [comment]
map文件夹下是否有4-X-0X格式的文件？如有请删除。统一格式为X-X-X，0是之前规范化字典用的，覆盖会出现这样的问题
