### ISSUE TITLE
買完過期郵包後會卡住，不能執行自動關機

### ISSUE THREAD

**Issue by jowilksasella** [linruowuyin/Fhoe-Rail#39]
09:42:50 - INFO	| log.webhook_and_log:38 - 3.1 -  [0;96;40m过期邮包2[0m
09:42:50 - INFO	| map.auto_map:89 - 3.1 -  路线领航员：[1;95mlrwy[0m 感谢她(们)的无私奉献
09:42:50 - DEBUG	| map.auto_map:92 - 3.1 -  picture\buy.png
09:42:51 - DEBUG	| calculated.click:51 - 3.1 -  (1329, 595)
09:42:52 - INFO	| map.auto_map:100 - 3.1 -  传送点击（1）
09:42:54 - DEBUG	| map.auto_map:92 - 3.1 -  picture\parcel.png
09:42:55 - DEBUG	| calculated.click:51 - 3.1 -  (364, 324)
09:42:56 - INFO	| map.auto_map:100 - 3.1 -  传送点击（2）
09:42:58 - DEBUG	| map.auto_map:92 - 3.1 -  picture\max.png
09:42:59 - DEBUG	| calculated.click:51 - 3.1 -  (1448, 633)
09:43:00 - INFO	| map.auto_map:100 - 3.1 -  传送点击（3）
09:43:02 - DEBUG	| map.auto_map:92 - 3.1 -  picture\confirm.png
09:43:03 - DEBUG	| calculated.click:51 - 3.1 -  (1168, 739)
09:43:04 - INFO	| map.auto_map:100 - 3.1 -  传送点击（4）

**Comment by jowilksasella** [comment]
抱歉，沒看到原來新的release中有說到這個問題

**Comment by linruowuyin** [comment]
后面会修，不过一周只有一次，所以不是很急

**Comment by linruowuyin** [comment]
修了
