### ISSUE TITLE
关于筑梦边境地图传点辨认(已照着新地图注意事项调整过路线)

### ISSUE THREAD

**Issue by Ptyun** [linruowuyin/Fhoe-Rail#42]
关于筑梦边境地图传点辨认(已照着新地图注意事项调整过路线)
但还是常常卡住,会等很久之后挑了一个传点
但看起来跑的路线是错误的(或者说是其他传点的路线?)
想请教一下该如何解决?

**Comment by linruowuyin** [comment]
程序设计缺陷，等待更新修复

**Comment by Ptyun** [comment]
原来如此 感谢~!
