### ISSUE TITLE
传送时间不足

### ISSUE THREAD

**Issue by AndiJingzhiXie** [linruowuyin/Fhoe-Rail#44]
低性能电脑经常遇到地图还没有传送完程序已经开始移动的情况，导致后续一系列移动都位置对不上。
可以留更多时间给地图传送吗？比如10-15s。或者允许用户自己修改传送时间

**Comment by linruowuyin** [comment]
有bug，原因不明，不是你电脑的问题，在回档了，明天起来看qaq

**Comment by linruowuyin** [comment]
暂时45版本是安全的，4647不知道是哪个地方的代码导致地图都打不开，传送不过去

**Comment by AndiJingzhiXie** [comment]
我似乎2.045版本仍然有这个问题....?

**Comment by smjes3** [comment]
2.055版本已修复，可以尝试使用看看。
