### ISSUE TITLE
匹诺康尼的怪会使摄像机朝向变化

### ISSUE THREAD

**Issue by ShinaKaria** [linruowuyin/Fhoe-Rail#45]
测试了匹诺康尼的怪物 和眩晕房的怪 以及仙舟和雅丽洛的怪
雅丽洛、仙舟 开怪后都不会使得摄像机朝向开怪角度 路线不会受影响
匹诺康尼无论是一般地图还是眩晕房的怪 开怪后完成战斗 会使摄像机朝向角色开怪角度
这也是匹诺康尼路线容易卡顿 不稳定的原因

**Comment by linruowuyin** [comment]
是的，目前没什么好办法orz

**Comment by smjes3** [comment]
可以实现，但是当前方案是例如3D图内有3组怪，攻击第1组后，返回传送点重跑到第2组……持续下去。
如果实现摄像机重置，3D图相关的地图要重新录。

另外有一点是摄像机重置目前可靠性我不太敢确定，项目本身也是尽量避免视角移动的，都是利用wasd，能将误差减小到最低。

摄像机的优点是如果成熟的话，全部跑完的时间会减小较多。

**Comment by Klamist** [comment]
> 例如3D图内有3组怪，攻击第1组后，返回传送点重跑到第2组……持续下去
是的，看了一下20多个json……失误率极低，一趟几乎全打完。
我自己魔改的版本目前就用的fastrun的箭头方向识别，但准度一直差一点。然后我改成转向函数每次定位2遍，现在用起来感觉还是挺精准了。下周我试试，看跑一圈的时间和失误率如何……

**Comment by smjes3** [comment]
魔改了ASU模拟宇宙项目的视角调整功能，实现了视角重置。
在地图中配置
{
    "view_reset": 0.1
}
会与传送后的基准视角比对，然后将视角恢复为初始状态

#276
