### ISSUE TITLE
开启了自动战斗但会被点击取消

### ISSUE THREAD

**Issue by Forevercyj** [linruowuyin/Fhoe-Rail#6]
在游戏设置中已经启用了连续自动战斗，但每次开启游戏后，自动战斗的按钮会被点击，即被取消了自动战斗。
原因估计是之前不知道某种情况下弹出的命令窗让我选是否自动战队，我当时选了“否”（第三个选项是“我啷个晓得”）。但至今不知道这个命令该如何调出或设置。

谢谢！

**Comment by yaochenli007** [comment]
再初始化一下就行

**Comment by Forevercyj** [comment]
> 再初始化一下就行

如何初始化呢

**Comment by Forevercyj** [comment]
修改 3rdparty\Fhoe-Rail\config.json 或删除后重新配置
