### ISSUE TITLE
如何联系作者优化地图

### ISSUE THREAD

**Issue by dConstantineb** [linruowuyin/Fhoe-Rail#62]
残响回廊-2的【map2-3-2】应该在加上`
        {
            "a": 2.200461387634277
        },
        {
            "w": 2.2172138690948486
        },`
不然有时候小怪跑太远打不到

**Comment by MatchaC** [comment]
#66 已经提交了PR
这个点确实经常漏怪，主要原因就是怪站在下坡最远处背对玩家导致超时
你这个修改确实能保证下坡最远处的怪能打到，但走的太远上坡的怪有可能会丢失仇恨
我改成怪巡逻中线偏下坡的位置，这样下坡能直接打到，上坡也会自己追过来
