### ISSUE TITLE
漏怪导致连续跳过怪和地图

### ISSUE THREAD

**Issue by Twilight-Z** [linruowuyin/Fhoe-Rail#64]
有些时候怪刚好在巡逻最远的地方要往回走，导致角色刚好A不到。
怪走得慢，回来A角色时程序已经识别为战斗结束/无怪。
导致跳怪，甚至大的地图之后走不到能识别下一个传送点的位置，把后面点全跳了。如罗浮仙舟各大地图。
甚至运气不好把下一个地图都跳了。
建议给个增加战斗等待时间，3、4秒检测不到战斗后再A一下，再检测不到就再继续下一步。
或者在怪巡逻范围前后中间两点都A一下，如100米，先走到25米A一下，75米再A一下。
或者检测不到战斗可以加个再输入上一步的按键多走两步加多A一下的步骤。
或者检测不到战斗就截图小地图判断一下红点，过去打一下。

感谢。

**Comment by smjes3** [comment]
2.061版本修复了一些识别问题，理论上由于代码造成的跳怪应该已经不太存在。

- 3、4秒检测不到再A一下。不做。
-- 因为每个角色A的向前距离不一样，容易造成地图路线偏差。且当前已有识别被怪物发现时自动A一下，如果没发现怪物向前A一下也不解决根本问题。如果还有跳怪希望给出日志或者漏的怪的地点，我们对地图路线进行优化或改进。

- 巡逻两点A一下目前已有做。但是有可能缺了一些怪物的，希望给出具体怪物位置。

- 检测不到战斗输入上一步按键多走两步多A一下，不做。
-- 必然造成路线误差。

- 检测不到战斗截图小地图判断红点过去打一下，不做。
-- 当前没有好的方案支持小地图移动后，还能保证路线不误差。
