### ISSUE TITLE
传送识别问题

### ISSUE THREAD

**Issue by 0frostmourne0** [linruowuyin/Fhoe-Rail#72]
地图 map_4-1_1 和 map_4-3_1 在点击传送后的黑屏过程中，脚本就已经开始执行移动命令，导致跑不到点位。
筑梦边境只会漏第一只，酒店则会因为无法上电梯而漏掉二楼的很多怪。
但手动指定酒店1重新跑则可以正常上电梯，脚本一口气跑下来就会出问题。

附log：
>22:58:56 - INFO	| log.webhook_and_log:38 - 3.1 -  [0;96;40m筑梦边境-1[0m
22:58:56 - INFO	| map.auto_map:97 - 3.1 -  路线领航员：[1;95m喵不可言[0m 感谢她(们)的无私奉献
22:58:56 - DEBUG	| map.auto_map:101 - 3.1 -  map
22:58:58 - INFO	| map.map_init:40 - 3.1 -  打开地图
22:59:02 - DEBUG	| map.map_init:34 - 3.1 -  (625, 986)
22:59:02 - INFO	| map.map_init:35 - 3.1 -  地图最小化，识别图片匹配度0.998
22:59:02 - DEBUG	| map.auto_map:101 - 3.1 -  picture\orientation_1.png
22:59:04 - DEBUG	| calculated.click:54 - 3.1 -  (1641, 139)
22:59:05 - INFO	| map.auto_map:142 - 3.1 -  传送点击（1）
22:59:06 - DEBUG	| map.auto_map:101 - 3.1 -  picture\orientation_5.png
22:59:08 - DEBUG	| calculated.click:54 - 3.1 -  (1368, 402)
22:59:09 - INFO	| map.auto_map:142 - 3.1 -  传送点击（2）
22:59:10 - DEBUG	| map.auto_map:101 - 3.1 -  picture\map_4-1.png
22:59:13 - DEBUG	| calculated.click:54 - 3.1 -  (1541, 636)
22:59:13 - INFO	| map.auto_map:142 - 3.1 -  传送点击（3）
22:59:15 - DEBUG	| map.auto_map:101 - 3.1 -  picture\map_4-1_point_1.png
22:59:17 - DEBUG	| calculated.click:54 - 3.1 -  (1159, 192)
22:59:17 - INFO	| map.auto_map:142 - 3.1 -  传送点击（4）
22:59:19 - DEBUG	| map.auto_map:101 - 3.1 -  picture\transfer.png
22:59:21 - DEBUG	| calculated.click:54 - 3.1 -  (1655, 970)
22:59:23 - INFO	| calculated.blackscreen_check:619 - 3.1 -  当前黑屏，值为186.313 > 25
22:59:24 - INFO	| calculated.run_mapload_check:681 - 3.1 -  地图载毕，用时 2.8 秒
22:59:26 - INFO	| map.auto_map:134 - 3.1 -  地图加载前的传送点为 picture\map_4-1_point_1.png
22:59:26 - INFO	| map.auto_map:142 - 3.1 -  传送点击（5）
22:59:29 - INFO	| calculated.auto_map:451 - 3.1 -  执行map_4-1_1文件:1/18 {'d': 3.699821662902832}
22:59:32 - INFO	| calculated.auto_map:451 - 3.1 -  执行map_4-1_1文件:2/18 {'fighting': 1}
22:59:32 - INFO	| calculated.fighting:257 - 3.1 -  识别中

上述log为[2.060](https://github.com/linruowuyin/Fhoe-Rail/releases/tag/2.060)版本生成。
在执行  {'d': 3.699821662902832} 这一步的时候，游戏还处于黑屏状态。

这几天的版本都会漏同样的几只怪，所以就观察了一下。
该问题只在更换地图时会发生，在同一张地图内传送则没有问题，猜测可能是挂机设备老旧传送过慢造成的。

**Comment by smjes3** [comment]
检查发现问题确实存在，晚些会发布一个修复版本。
