### ISSUE TITLE
对跳转过程识别失败

### ISSUE THREAD

**Issue by SauceFlavoredLatte** [linruowuyin/Fhoe-Rail#73]
<img width="427" alt="无标题" src="https://github.com/linruowuyin/Fhoe-Rail/assets/161800463/90b624c0-fe2f-4cb7-b33c-686e70b3ee8c">

**Comment by smjes3** [comment]
在程序文件夹下有一个logs文件夹，里面的对应log复制出来看一下。

**Comment by SauceFlavoredLatte** [comment]
<img width="521" alt="log" src="https://github.com/linruowuyin/Fhoe-Rail/assets/161800463/a7dbdad0-d84c-4076-a5af-a306e3f939d6">

**Comment by smjes3** [comment]
查询代码没有发现这个什么时候改成temp了。。解决了这个先关闭。

**Comment by SauceFlavoredLatte** [comment]
是崩铁1.2时期远古版本的遗留问题
