### ISSUE TITLE
脚本能支持开启疾跑么，让跑图的速度更快一些

### ISSUE THREAD

**Issue by njzybaby** [linruowuyin/Fhoe-Rail#74]
目前新地图越开越多，跑图时间也加长了，如果在跑图过程中慢走能切换到疾跑，应该能提点锄大地速度。
3D图复杂可以不开疾跑，主要尤其是雅利洛和罗浮那种简单的路线，就是纯粹路程长。
目前一天跑完脚本也要四个多小时，以后再开新图得奔6小时去了，TAT

**Comment by Canda15** [comment]
以前的肯定不可能加了。要不全部重录按键。工作量太大了吧。一直没用疾跑估计是精度问题

**Comment by smjes3** [comment]
目前还在考虑方案中。如果全部重录肯定不现实。

当前有在考虑是否能用某种算法对原有的路线或进行少量改动的同时，能够同时兼容开启疾跑。

**Comment by njzybaby** [comment]
https://github.com/DoctorReid/StarRailOneDragon

这个方案可以开疾跑，全部锄完大约2个半小时，但确实有漏怪问题，不过漏的不多，最大的问题是这个作品暂时不支持锄3D图。
咱们这个脚本锄得最齐全，但就是比较慢，目前跑完大概四个半小时吧，如果能两相结合，给电脑省点时间和电就好了。

**Comment by smjes3** [comment]
已增加了疾跑模式。
