### ISSUE TITLE
4.3.19结束后卡住

### ISSUE THREAD

**Issue by Tom-xia** [linruowuyin/Fhoe-Rail#77]
4.3.19结束后角色所在位置靠近地图边缘导致拖住了地图，无法直接执行4.3.20的map_4-3_point_1传送图标。
建议先传送到map_4-3_point_4；在走map_4-3_point_4这里的电梯，之后往map_4-3_point_1传送点再跑一段路，就可以执行map_4-3_point_1传送了。
自己修改4.3.20代码失败了QAQ，不知道是不是因为一个json文件里只能执行一次传送。希望大佬指教
[map_4-3_20.json](https://github.com/linruowuyin/Fhoe-Rail/files/14471366/map_4-3_20.json)

**Comment by Tom-xia** [comment]
附上自己按照上述设想修改之后的代码，个人觉得设想应该是可行的，就是不会实现，求教

**Comment by smjes3** [comment]
加了自动拖地图，现在会拖过去找对的传送点。
