### ISSUE TITLE
入画后不会等待

### ISSUE THREAD

**Issue by bin1129** [linruowuyin/Fhoe-Rail#78]
最新的2.061版本在地图3-4-6开局入画后没有等待入画完成就开始行动了，导致后面路线全都对不上了，上一个版本是正常的

**Comment by 0frostmourne0** [comment]
> 13:59:11 - INFO   	| calculated.run_mapload_check:801         	- 2.061 - 地图载毕，用时 4.0 秒
13:59:13 - INFO   	| map.auto_map:136                         	- 2.061 - 地图加载前的传送点为 picture\map_3-4_point_2.png
13:59:13 - INFO   	| map.auto_map:144                         	- 2.061 - 传送点击（2）
13:59:15 - INFO   	| calculated.auto_map:523                  	- 2.061 - 执行map_3-4_6文件:1/16 {'d': 0.26}
13:59:16 - INFO   	| calculated.auto_map:523                  	- 2.061 - 执行map_3-4_6文件:2/16 {'a': 1.8}
13:59:17 - INFO   	| calculated.auto_map:523                  	- 2.061 - 执行map_3-4_6文件:3/16 {'s': 0.77}
13:59:18 - INFO   	| calculated.auto_map:523                  	- 2.061 - 执行map_3-4_6文件:4/16 {'f': 10}
13:59:18 - INFO   	| calculated.check_f_img:471               	- 2.061 - 扫描'F'图标
13:59:19 - DEBUG  	| calculated.check_f_img:483               	- 2.061 - 扫描'F'：target，匹配度：0.972
13:59:19 - DEBUG  	| calculated.check_f_img:483               	- 2.061 - 扫描'F'：target_Teleport，匹配度：0.999
13:59:19 - INFO   	| calculated.check_f_img:498               	- 2.061 - 扫描到 入画
13:59:19 - INFO   	| calculated.handle_f:566                  	- 2.061 - 按下'F'，等待主界面检测
13:59:20 - INFO   	| calculated.on_main_interface:845         	- 2.061 - 检测到游戏主界面，非战斗/传送/黑屏状态，耗时 0.3 秒
13:59:20 - DEBUG  	| calculated.on_main_interface:846         	- 2.061 - 检测图片序号为0，匹配位置为(233, 64)
13:59:22 - INFO   	| calculated.auto_map:523                  	- 2.061 - 执行map_3-4_6文件:5/16 {'d': 0.16}

同样的问题，“按F”和“主界面检测”中间缺少延迟，导致还没开始传送就以为传送完了。

**Comment by smjes3** [comment]
感谢反馈，晚些时候会给入画到入画结束检测之间加上2秒延迟。
