### ISSUE TITLE
[2.064]更新后依然无法识别传送完成，死循环卡死，10次以后才能继续。

### ISSUE THREAD

**Issue by jy02664402** [linruowuyin/Fhoe-Rail#85]
最近版本，就算是刚刚更新的2.064也依然会在流云渡的卡死，传送完成后无法识别，原地罚站至少执行10次重试才能继续。该问题已经不止在一个传送点出现。
![QQ截图20240305022824](https://github.com/linruowuyin/Fhoe-Rail/assets/58306105/21e8ba41-2aac-4f1f-bbef-c317ea9f6620)

**Comment by smjes3** [comment]
#86 
是由于阈值提高造成的，已回退至原先的识别阈值。
中午已发现这个问题并修复，请稍等合并后的新包。
