### ISSUE TITLE
map_4-3_20中存在问题，电梯够不着

### ISSUE THREAD

**Issue by jowilksasella** [linruowuyin/Fhoe-Rail#93]
不知道是不是因为新功能疾跑的问题
[map_4-3_20.json](https://github.com/linruowuyin/Fhoe-Rail/files/14545076/map_4-3_20.json)
需要把第23行的d改成2.0才够得着电梯，不然会卡住

无论有没有开疾跑，1.8都是够不着电梯的
（个人认为可能是原本打算疾跑1.8秒？但是1.8秒不会触发疾跑）

**Comment by jowilksasella** [comment]
map_4-3_22跟map_4-3_24都有这个问题

**Comment by linruowuyin** [comment]
哪个角色跑图呢

**Comment by jowilksasella** [comment]
> 哪个角色跑图呢

阮梅

**Comment by smjes3** [comment]
疾跑后的点理论上和走路差距不大，且2秒以内不会触发疾跑。这个地图修复下即可。

**Comment by jowilksasella** [comment]
> 疾跑后的点理论上和走路差距不大，且2秒以内不会触发疾跑。这个地图修复下即可。

嗯，改成2.0就够得着了。只是反馈一下而已。不过好像只有我够不着？没看到有同样的issue

**Comment by smjes3** [comment]
查了不是地图问题，我代码有做一些疾跑的偏移处理，导致非疾跑也会有一点偏差，现在改好了。
